FROM tomcat:8-jre8

ENV JAVA_OPTS "-Dspring.profiles.active=production-mysql -Ddatasource.jndi-name=java:comp/env/jdbc/oagiDB"

RUN ["rm", "-f", "/usr/local/tomcat/conf/context.xml"]
ADD context.xml /usr/local/tomcat/conf/context.xml

RUN ["rm", "-rf", "/usr/local/tomcat/webapps/ROOT"]
ADD srt-webapp-1.1.0.war /usr/local/tomcat/webapps/ROOT.war

ADD mysql-connector-java-5.1.46.jar /usr/local/tomcat/lib/mysql-connector-java-5.1.46.jar

CMD ["catalina.sh", "run"]
