# AOP
spring:
  aop:
    proxy-target-class: true

# DataSource
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@docker:1521/xe.oracle.docker
    username: oagi
    password: oagi
    platform: oracle

    continue-on-error: true
    initialize: false

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        id:
          new_generator_mappings: true
        cache:
          use_second_level_cache: false

  batch:
    initializer:
      enabled: false

logging:
  level:
    org.oagi.srt: INFO
    org.springframework: INFO
    org.hibernate.SQL: INFO

# Staging environment
---
spring:
  profiles: staging

# DataSource
  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/OAGISRTDB
    username: oagi
    password: oagi
    platform: oracle