import { MethodKey } from '@/lib/reference-data';

import { MethodPageClient } from './method-page-client';

const RESOURCE_METHODS: Record<string, MethodKey[]> = {
  accounts: ['list', 'retrieve', 'who_am_i'],
  libraries: ['list', 'retrieve'],
  releases: ['list', 'retrieve', 'retrieve_working'],
  namespaces: ['list', 'retrieve'],
  core_components: [
    'list',
    'get_acc',
    'create_acc',
    'update_acc',
    'add_acc_tags',
    'remove_acc_tags',
    'change_acc_state',
    'transfer_acc_ownership',
    'revise_acc',
    'cancel_acc',
    'discard_acc',
    'add_ascc_to_acc',
    'reorder_ascc_in_acc',
    'update_ascc',
    'remove_ascc',
    'add_bcc_to_acc',
    'reorder_bcc_in_acc',
    'update_bcc',
    'remove_bcc',
    'get_asccp',
    'create_asccp',
    'update_asccp',
    'change_asccp_state',
    'transfer_asccp_ownership',
    'change_asccp_role_of_acc',
    'add_asccp_tags',
    'remove_asccp_tags',
    'revise_asccp',
    'cancel_asccp',
    'discard_asccp',
    'get_bccp',
    'create_bccp',
    'update_bccp',
    'change_bccp_state',
    'transfer_bccp_ownership',
    'change_bccp_bdt',
    'add_bccp_tags',
    'remove_bccp_tags',
    'revise_bccp',
    'cancel_bccp',
    'discard_bccp',
  ],
  business_information_entities: [
    'get_top_level_asbiep_list',
    'get_top_level_asbiep',
    'create_top_level_asbiep',
    'update_top_level_asbiep',
    'update_top_level_asbiep_state',
    'delete_top_level_asbiep',
    'transfer_top_level_asbiep_ownership',
    'assign_biz_ctx_to_top_level_asbiep',
    'unassign_biz_ctx_from_top_level_asbiep',
    'get_asbie_by_asbie_id',
    'get_asbie_by_based_ascc_manifest_id',
    'create_asbie',
    'update_asbie',
    'reuse_top_level_asbiep',
    'remove_reused_top_level_asbiep',
    'get_bbie_by_bbie_id',
    'get_bbie_by_based_bcc_manifest_id',
    'create_bbie',
    'update_bbie',
    'create_bbie_sc',
    'update_bbie_sc',
  ],
  data_types: [
    'list',
    'retrieve',
    'create_dt',
    'update_dt',
    'create_dt_sc',
    'update_dt_sc',
    'delete_dt_sc',
    'add_dt_tags',
    'remove_dt_tags',
    'change_dt_state',
    'transfer_dt_ownership',
    'revise_dt',
    'cancel_dt',
    'discard_dt',
  ],
  xbts: ['retrieve'],
  code_lists: [
    'list',
    'retrieve',
    'create_code_list',
    'update_code_list',
    'retrieve_code_list_value',
    'create_code_list_value',
    'update_code_list_value',
    'delete_code_list_value',
    'transfer_code_list_ownership',
    'change_code_list_state',
    'revise_code_list',
    'cancel_code_list',
    'discard_code_list',
  ],
  agency_id_lists: ['list', 'retrieve'],
  tags: ['list'],
  context_categories: ['create', 'update', 'delete', 'list', 'retrieve'],
  context_schemes: [
    'create',
    'update',
    'delete',
    'list',
    'retrieve',
    'create_value',
    'update_value',
    'delete_value',
    'retrieve_value_by_id',
  ],
  business_contexts: [
    'create',
    'update',
    'delete',
    'list',
    'retrieve',
    'create_value',
    'update_value',
    'delete_value',
    'retrieve_value_by_id',
  ],
};

export function generateStaticParams(): Array<{ resource: string; method: MethodKey }> {
  return Object.entries(RESOURCE_METHODS).flatMap(([resource, methods]) =>
    methods.map((method) => ({ resource, method })),
  );
}

export default async function MethodPage({
  params,
}: {
  params: Promise<{ resource: string; method: MethodKey }>;
}) {
  const { resource, method } = await params;
  return <MethodPageClient resource={resource} method={method} />;
}
