/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.e2e.impl.api.jooq.entity.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.oagi.score.e2e.impl.api.jooq.entity.tables.AccManifest;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class AccManifestRecord extends UpdatableRecordImpl<AccManifestRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.acc_manifest.acc_manifest_id</code>.
     */
    public void setAccManifestId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.acc_manifest.acc_manifest_id</code>.
     */
    public ULong getAccManifestId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>oagi.acc_manifest.release_id</code>.
     */
    public void setReleaseId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.acc_manifest.release_id</code>.
     */
    public ULong getReleaseId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>oagi.acc_manifest.acc_id</code>.
     */
    public void setAccId(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.acc_manifest.acc_id</code>.
     */
    public ULong getAccId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>oagi.acc_manifest.based_acc_manifest_id</code>.
     */
    public void setBasedAccManifestId(ULong value) {
        set(3, value);
    }

    /**
     * Getter for <code>oagi.acc_manifest.based_acc_manifest_id</code>.
     */
    public ULong getBasedAccManifestId() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>oagi.acc_manifest.den</code>. DEN (dictionary entry
     * name) of the ACC. It can be derived as OBJECT_CLASS_QUALIFIER + "_ " +
     * OBJECT_CLASS_TERM + ". Details".
     */
    public void setDen(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>oagi.acc_manifest.den</code>. DEN (dictionary entry
     * name) of the ACC. It can be derived as OBJECT_CLASS_QUALIFIER + "_ " +
     * OBJECT_CLASS_TERM + ". Details".
     */
    public String getDen() {
        return (String) get(4);
    }

    /**
     * Setter for <code>oagi.acc_manifest.conflict</code>. This indicates that
     * there is a conflict between self and relationship.
     */
    public void setConflict(Byte value) {
        set(5, value);
    }

    /**
     * Getter for <code>oagi.acc_manifest.conflict</code>. This indicates that
     * there is a conflict between self and relationship.
     */
    public Byte getConflict() {
        return (Byte) get(5);
    }

    /**
     * Setter for <code>oagi.acc_manifest.log_id</code>. A foreign key pointed
     * to a log for the current record.
     */
    public void setLogId(ULong value) {
        set(6, value);
    }

    /**
     * Getter for <code>oagi.acc_manifest.log_id</code>. A foreign key pointed
     * to a log for the current record.
     */
    public ULong getLogId() {
        return (ULong) get(6);
    }

    /**
     * Setter for <code>oagi.acc_manifest.replacement_acc_manifest_id</code>.
     * This refers to a replacement manifest if the record is deprecated.
     */
    public void setReplacementAccManifestId(ULong value) {
        set(7, value);
    }

    /**
     * Getter for <code>oagi.acc_manifest.replacement_acc_manifest_id</code>.
     * This refers to a replacement manifest if the record is deprecated.
     */
    public ULong getReplacementAccManifestId() {
        return (ULong) get(7);
    }

    /**
     * Setter for <code>oagi.acc_manifest.prev_acc_manifest_id</code>.
     */
    public void setPrevAccManifestId(ULong value) {
        set(8, value);
    }

    /**
     * Getter for <code>oagi.acc_manifest.prev_acc_manifest_id</code>.
     */
    public ULong getPrevAccManifestId() {
        return (ULong) get(8);
    }

    /**
     * Setter for <code>oagi.acc_manifest.next_acc_manifest_id</code>.
     */
    public void setNextAccManifestId(ULong value) {
        set(9, value);
    }

    /**
     * Getter for <code>oagi.acc_manifest.next_acc_manifest_id</code>.
     */
    public ULong getNextAccManifestId() {
        return (ULong) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccManifestRecord
     */
    public AccManifestRecord() {
        super(AccManifest.ACC_MANIFEST);
    }

    /**
     * Create a detached, initialised AccManifestRecord
     */
    public AccManifestRecord(ULong accManifestId, ULong releaseId, ULong accId, ULong basedAccManifestId, String den, Byte conflict, ULong logId, ULong replacementAccManifestId, ULong prevAccManifestId, ULong nextAccManifestId) {
        super(AccManifest.ACC_MANIFEST);

        setAccManifestId(accManifestId);
        setReleaseId(releaseId);
        setAccId(accId);
        setBasedAccManifestId(basedAccManifestId);
        setDen(den);
        setConflict(conflict);
        setLogId(logId);
        setReplacementAccManifestId(replacementAccManifestId);
        setPrevAccManifestId(prevAccManifestId);
        setNextAccManifestId(nextAccManifestId);
        resetTouchedOnNotNull();
    }
}
