/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.e2e.impl.api.jooq.entity.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.oagi.score.e2e.impl.api.jooq.entity.tables.CtxSchemeValue;


/**
 * This table stores the context scheme values for a particular context scheme
 * in the CTX_SCHEME table.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CtxSchemeValueRecord extends UpdatableRecordImpl<CtxSchemeValueRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.ctx_scheme_value.ctx_scheme_value_id</code>.
     * Primary, internal database key.
     */
    public void setCtxSchemeValueId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.ctx_scheme_value.ctx_scheme_value_id</code>.
     * Primary, internal database key.
     */
    public ULong getCtxSchemeValueId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>oagi.ctx_scheme_value.guid</code>. A globally unique
     * identifier (GUID).
     */
    public void setGuid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.ctx_scheme_value.guid</code>. A globally unique
     * identifier (GUID).
     */
    public String getGuid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>oagi.ctx_scheme_value.value</code>. A short value for
     * the scheme value similar to the code list value.
     */
    public void setValue(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.ctx_scheme_value.value</code>. A short value for
     * the scheme value similar to the code list value.
     */
    public String getValue() {
        return (String) get(2);
    }

    /**
     * Setter for <code>oagi.ctx_scheme_value.meaning</code>. The description,
     * explanatiion of the scheme value.
     */
    public void setMeaning(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>oagi.ctx_scheme_value.meaning</code>. The description,
     * explanatiion of the scheme value.
     */
    public String getMeaning() {
        return (String) get(3);
    }

    /**
     * Setter for <code>oagi.ctx_scheme_value.owner_ctx_scheme_id</code>.
     * Foreign key to the CTX_SCHEME table. It identifies the context scheme, to
     * which this scheme value belongs.
     */
    public void setOwnerCtxSchemeId(ULong value) {
        set(4, value);
    }

    /**
     * Getter for <code>oagi.ctx_scheme_value.owner_ctx_scheme_id</code>.
     * Foreign key to the CTX_SCHEME table. It identifies the context scheme, to
     * which this scheme value belongs.
     */
    public ULong getOwnerCtxSchemeId() {
        return (ULong) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CtxSchemeValueRecord
     */
    public CtxSchemeValueRecord() {
        super(CtxSchemeValue.CTX_SCHEME_VALUE);
    }

    /**
     * Create a detached, initialised CtxSchemeValueRecord
     */
    public CtxSchemeValueRecord(ULong ctxSchemeValueId, String guid, String value, String meaning, ULong ownerCtxSchemeId) {
        super(CtxSchemeValue.CTX_SCHEME_VALUE);

        setCtxSchemeValueId(ctxSchemeValueId);
        setGuid(guid);
        setValue(value);
        setMeaning(meaning);
        setOwnerCtxSchemeId(ownerCtxSchemeId);
        resetChangedOnNotNull();
    }
}
