/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.e2e.impl.api.jooq.entity.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.oagi.score.e2e.impl.api.jooq.entity.tables.OasDocSecurity;


/**
 * Root-level Security Requirement entry for an OpenAPI document.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class OasDocSecurityRecord extends UpdatableRecordImpl<OasDocSecurityRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.oas_doc_security.oas_doc_security_id</code>. The
     * primary key of the record.
     */
    public void setOasDocSecurityId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.oas_doc_security.oas_doc_security_id</code>. The
     * primary key of the record.
     */
    public ULong getOasDocSecurityId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>oagi.oas_doc_security.guid</code>. The GUID of the
     * record.
     */
    public void setGuid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.oas_doc_security.guid</code>. The GUID of the
     * record.
     */
    public String getGuid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>oagi.oas_doc_security.oas_doc_id</code>. The owning
     * OpenAPI document; one entry of the document's root-level security array.
     */
    public void setOasDocId(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.oas_doc_security.oas_doc_id</code>. The owning
     * OpenAPI document; one entry of the document's root-level security array.
     */
    public ULong getOasDocId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>oagi.oas_doc_security.requirement_group</code>. Index of
     * the Security Requirement Object within the security array (OR). Rows
     * sharing a group are ANDed into one requirement object.
     */
    public void setRequirementGroup(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>oagi.oas_doc_security.requirement_group</code>. Index of
     * the Security Requirement Object within the security array (OR). Rows
     * sharing a group are ANDed into one requirement object.
     */
    public Integer getRequirementGroup() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>oagi.oas_doc_security.oas_security_scheme_id</code>. FK
     * to oas_security_scheme. The scheme this entry references (its scheme_name
     * is the components.securitySchemes key). NULL marks an empty requirement
     * object {} (anonymous / optional).
     */
    public void setOasSecuritySchemeId(ULong value) {
        set(4, value);
    }

    /**
     * Getter for <code>oagi.oas_doc_security.oas_security_scheme_id</code>. FK
     * to oas_security_scheme. The scheme this entry references (its scheme_name
     * is the components.securitySchemes key). NULL marks an empty requirement
     * object {} (anonymous / optional).
     */
    public ULong getOasSecuritySchemeId() {
        return (ULong) get(4);
    }

    /**
     * Setter for <code>oagi.oas_doc_security.created_by</code>. The user who
     * creates the record.
     */
    public void setCreatedBy(ULong value) {
        set(5, value);
    }

    /**
     * Getter for <code>oagi.oas_doc_security.created_by</code>. The user who
     * creates the record.
     */
    public ULong getCreatedBy() {
        return (ULong) get(5);
    }

    /**
     * Setter for <code>oagi.oas_doc_security.last_updated_by</code>. The user
     * who last updates the record.
     */
    public void setLastUpdatedBy(ULong value) {
        set(6, value);
    }

    /**
     * Getter for <code>oagi.oas_doc_security.last_updated_by</code>. The user
     * who last updates the record.
     */
    public ULong getLastUpdatedBy() {
        return (ULong) get(6);
    }

    /**
     * Setter for <code>oagi.oas_doc_security.creation_timestamp</code>. The
     * timestamp when the record is created.
     */
    public void setCreationTimestamp(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>oagi.oas_doc_security.creation_timestamp</code>. The
     * timestamp when the record is created.
     */
    public LocalDateTime getCreationTimestamp() {
        return (LocalDateTime) get(7);
    }

    /**
     * Setter for <code>oagi.oas_doc_security.last_update_timestamp</code>. The
     * timestamp when the record is last updated.
     */
    public void setLastUpdateTimestamp(LocalDateTime value) {
        set(8, value);
    }

    /**
     * Getter for <code>oagi.oas_doc_security.last_update_timestamp</code>. The
     * timestamp when the record is last updated.
     */
    public LocalDateTime getLastUpdateTimestamp() {
        return (LocalDateTime) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OasDocSecurityRecord
     */
    public OasDocSecurityRecord() {
        super(OasDocSecurity.OAS_DOC_SECURITY);
    }

    /**
     * Create a detached, initialised OasDocSecurityRecord
     */
    public OasDocSecurityRecord(ULong oasDocSecurityId, String guid, ULong oasDocId, Integer requirementGroup, ULong oasSecuritySchemeId, ULong createdBy, ULong lastUpdatedBy, LocalDateTime creationTimestamp, LocalDateTime lastUpdateTimestamp) {
        super(OasDocSecurity.OAS_DOC_SECURITY);

        setOasDocSecurityId(oasDocSecurityId);
        setGuid(guid);
        setOasDocId(oasDocId);
        setRequirementGroup(requirementGroup);
        setOasSecuritySchemeId(oasSecuritySchemeId);
        setCreatedBy(createdBy);
        setLastUpdatedBy(lastUpdatedBy);
        setCreationTimestamp(creationTimestamp);
        setLastUpdateTimestamp(lastUpdateTimestamp);
        resetTouchedOnNotNull();
    }
}
