/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.e2e.impl.api.jooq.entity.tables.records;


import java.time.LocalDateTime;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.oagi.score.e2e.impl.api.jooq.entity.tables.OasTag;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class OasTagRecord extends UpdatableRecordImpl<OasTagRecord> implements Record8<ULong, String, String, String, ULong, ULong, LocalDateTime, LocalDateTime> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.oas_tag.oas_tag_id</code>. The primary key of the
     * record.
     */
    public void setOasTagId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.oas_tag.oas_tag_id</code>. The primary key of the
     * record.
     */
    public ULong getOasTagId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>oagi.oas_tag.guid</code>. The GUID of the record.
     */
    public void setGuid(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.oas_tag.guid</code>. The GUID of the record.
     */
    public String getGuid() {
        return (String) get(1);
    }

    /**
     * Setter for <code>oagi.oas_tag.name</code>. REQUIRED. The name of the tag.
     */
    public void setName(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.oas_tag.name</code>. REQUIRED. The name of the tag.
     */
    public String getName() {
        return (String) get(2);
    }

    /**
     * Setter for <code>oagi.oas_tag.description</code>. A short description for
     * the tag. CommonMark syntax MAY be used for rich text representation.
     */
    public void setDescription(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>oagi.oas_tag.description</code>. A short description for
     * the tag. CommonMark syntax MAY be used for rich text representation.
     */
    public String getDescription() {
        return (String) get(3);
    }

    /**
     * Setter for <code>oagi.oas_tag.created_by</code>. The user who creates the
     * record.
     */
    public void setCreatedBy(ULong value) {
        set(4, value);
    }

    /**
     * Getter for <code>oagi.oas_tag.created_by</code>. The user who creates the
     * record.
     */
    public ULong getCreatedBy() {
        return (ULong) get(4);
    }

    /**
     * Setter for <code>oagi.oas_tag.last_updated_by</code>. The user who last
     * updates the record.
     */
    public void setLastUpdatedBy(ULong value) {
        set(5, value);
    }

    /**
     * Getter for <code>oagi.oas_tag.last_updated_by</code>. The user who last
     * updates the record.
     */
    public ULong getLastUpdatedBy() {
        return (ULong) get(5);
    }

    /**
     * Setter for <code>oagi.oas_tag.creation_timestamp</code>. The timestamp
     * when the record is created.
     */
    public void setCreationTimestamp(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>oagi.oas_tag.creation_timestamp</code>. The timestamp
     * when the record is created.
     */
    public LocalDateTime getCreationTimestamp() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>oagi.oas_tag.last_update_timestamp</code>. The timestamp
     * when the record is last updated.
     */
    public void setLastUpdateTimestamp(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>oagi.oas_tag.last_update_timestamp</code>. The timestamp
     * when the record is last updated.
     */
    public LocalDateTime getLastUpdateTimestamp() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row8<ULong, String, String, String, ULong, ULong, LocalDateTime, LocalDateTime> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    @Override
    public Row8<ULong, String, String, String, ULong, ULong, LocalDateTime, LocalDateTime> valuesRow() {
        return (Row8) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return OasTag.OAS_TAG.OAS_TAG_ID;
    }

    @Override
    public Field<String> field2() {
        return OasTag.OAS_TAG.GUID;
    }

    @Override
    public Field<String> field3() {
        return OasTag.OAS_TAG.NAME;
    }

    @Override
    public Field<String> field4() {
        return OasTag.OAS_TAG.DESCRIPTION;
    }

    @Override
    public Field<ULong> field5() {
        return OasTag.OAS_TAG.CREATED_BY;
    }

    @Override
    public Field<ULong> field6() {
        return OasTag.OAS_TAG.LAST_UPDATED_BY;
    }

    @Override
    public Field<LocalDateTime> field7() {
        return OasTag.OAS_TAG.CREATION_TIMESTAMP;
    }

    @Override
    public Field<LocalDateTime> field8() {
        return OasTag.OAS_TAG.LAST_UPDATE_TIMESTAMP;
    }

    @Override
    public ULong component1() {
        return getOasTagId();
    }

    @Override
    public String component2() {
        return getGuid();
    }

    @Override
    public String component3() {
        return getName();
    }

    @Override
    public String component4() {
        return getDescription();
    }

    @Override
    public ULong component5() {
        return getCreatedBy();
    }

    @Override
    public ULong component6() {
        return getLastUpdatedBy();
    }

    @Override
    public LocalDateTime component7() {
        return getCreationTimestamp();
    }

    @Override
    public LocalDateTime component8() {
        return getLastUpdateTimestamp();
    }

    @Override
    public ULong value1() {
        return getOasTagId();
    }

    @Override
    public String value2() {
        return getGuid();
    }

    @Override
    public String value3() {
        return getName();
    }

    @Override
    public String value4() {
        return getDescription();
    }

    @Override
    public ULong value5() {
        return getCreatedBy();
    }

    @Override
    public ULong value6() {
        return getLastUpdatedBy();
    }

    @Override
    public LocalDateTime value7() {
        return getCreationTimestamp();
    }

    @Override
    public LocalDateTime value8() {
        return getLastUpdateTimestamp();
    }

    @Override
    public OasTagRecord value1(ULong value) {
        setOasTagId(value);
        return this;
    }

    @Override
    public OasTagRecord value2(String value) {
        setGuid(value);
        return this;
    }

    @Override
    public OasTagRecord value3(String value) {
        setName(value);
        return this;
    }

    @Override
    public OasTagRecord value4(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public OasTagRecord value5(ULong value) {
        setCreatedBy(value);
        return this;
    }

    @Override
    public OasTagRecord value6(ULong value) {
        setLastUpdatedBy(value);
        return this;
    }

    @Override
    public OasTagRecord value7(LocalDateTime value) {
        setCreationTimestamp(value);
        return this;
    }

    @Override
    public OasTagRecord value8(LocalDateTime value) {
        setLastUpdateTimestamp(value);
        return this;
    }

    @Override
    public OasTagRecord values(ULong value1, String value2, String value3, String value4, ULong value5, ULong value6, LocalDateTime value7, LocalDateTime value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached OasTagRecord
     */
    public OasTagRecord() {
        super(OasTag.OAS_TAG);
    }

    /**
     * Create a detached, initialised OasTagRecord
     */
    public OasTagRecord(ULong oasTagId, String guid, String name, String description, ULong createdBy, ULong lastUpdatedBy, LocalDateTime creationTimestamp, LocalDateTime lastUpdateTimestamp) {
        super(OasTag.OAS_TAG);

        setOasTagId(oasTagId);
        setGuid(guid);
        setName(name);
        setDescription(description);
        setCreatedBy(createdBy);
        setLastUpdatedBy(lastUpdatedBy);
        setCreationTimestamp(creationTimestamp);
        setLastUpdateTimestamp(lastUpdateTimestamp);
        resetChangedOnNotNull();
    }
}
