/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.repo.api.impl.jooq.entity.tables.records;


import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.oagi.score.repo.api.impl.jooq.entity.tables.CdtScAwdPriXpsTypeMap;


/**
 * The purpose of this table is the same as that of the
 * CDT_AWD_PRI_XPS_TYPE_MAP, but it is for the supplementary component (SC). It
 * allows for the concrete mapping between the CDT Primitives and types in a
 * particular expression such as XML Schema, JSON. 
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CdtScAwdPriXpsTypeMapRecord extends UpdatableRecordImpl<CdtScAwdPriXpsTypeMapRecord> implements Record3<ULong, ULong, ULong> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>oagi.cdt_sc_awd_pri_xps_type_map.cdt_sc_awd_pri_xps_type_map_id</code>.
     * Internal, primary database key.
     */
    public void setCdtScAwdPriXpsTypeMapId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>oagi.cdt_sc_awd_pri_xps_type_map.cdt_sc_awd_pri_xps_type_map_id</code>.
     * Internal, primary database key.
     */
    public ULong getCdtScAwdPriXpsTypeMapId() {
        return (ULong) get(0);
    }

    /**
     * Setter for
     * <code>oagi.cdt_sc_awd_pri_xps_type_map.cdt_sc_awd_pri_id</code>. Foreign
     * key to the CDT_SC_AWD_PRI table.
     */
    public void setCdtScAwdPriId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>oagi.cdt_sc_awd_pri_xps_type_map.cdt_sc_awd_pri_id</code>. Foreign
     * key to the CDT_SC_AWD_PRI table.
     */
    public ULong getCdtScAwdPriId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>oagi.cdt_sc_awd_pri_xps_type_map.xbt_id</code>. Foreign
     * key to the Xbt table. It identifies an XML schema built-in type that maps
     * to the CDT SC Allowed Primitive identified in the CDT_SC_AWD_PRI column.
     */
    public void setXbtId(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.cdt_sc_awd_pri_xps_type_map.xbt_id</code>. Foreign
     * key to the Xbt table. It identifies an XML schema built-in type that maps
     * to the CDT SC Allowed Primitive identified in the CDT_SC_AWD_PRI column.
     */
    public ULong getXbtId() {
        return (ULong) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row3<ULong, ULong, ULong> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    @Override
    public Row3<ULong, ULong, ULong> valuesRow() {
        return (Row3) super.valuesRow();
    }

    @Override
    public Field<ULong> field1() {
        return CdtScAwdPriXpsTypeMap.CDT_SC_AWD_PRI_XPS_TYPE_MAP.CDT_SC_AWD_PRI_XPS_TYPE_MAP_ID;
    }

    @Override
    public Field<ULong> field2() {
        return CdtScAwdPriXpsTypeMap.CDT_SC_AWD_PRI_XPS_TYPE_MAP.CDT_SC_AWD_PRI_ID;
    }

    @Override
    public Field<ULong> field3() {
        return CdtScAwdPriXpsTypeMap.CDT_SC_AWD_PRI_XPS_TYPE_MAP.XBT_ID;
    }

    @Override
    public ULong component1() {
        return getCdtScAwdPriXpsTypeMapId();
    }

    @Override
    public ULong component2() {
        return getCdtScAwdPriId();
    }

    @Override
    public ULong component3() {
        return getXbtId();
    }

    @Override
    public ULong value1() {
        return getCdtScAwdPriXpsTypeMapId();
    }

    @Override
    public ULong value2() {
        return getCdtScAwdPriId();
    }

    @Override
    public ULong value3() {
        return getXbtId();
    }

    @Override
    public CdtScAwdPriXpsTypeMapRecord value1(ULong value) {
        setCdtScAwdPriXpsTypeMapId(value);
        return this;
    }

    @Override
    public CdtScAwdPriXpsTypeMapRecord value2(ULong value) {
        setCdtScAwdPriId(value);
        return this;
    }

    @Override
    public CdtScAwdPriXpsTypeMapRecord value3(ULong value) {
        setXbtId(value);
        return this;
    }

    @Override
    public CdtScAwdPriXpsTypeMapRecord values(ULong value1, ULong value2, ULong value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CdtScAwdPriXpsTypeMapRecord
     */
    public CdtScAwdPriXpsTypeMapRecord() {
        super(CdtScAwdPriXpsTypeMap.CDT_SC_AWD_PRI_XPS_TYPE_MAP);
    }

    /**
     * Create a detached, initialised CdtScAwdPriXpsTypeMapRecord
     */
    public CdtScAwdPriXpsTypeMapRecord(ULong cdtScAwdPriXpsTypeMapId, ULong cdtScAwdPriId, ULong xbtId) {
        super(CdtScAwdPriXpsTypeMap.CDT_SC_AWD_PRI_XPS_TYPE_MAP);

        setCdtScAwdPriXpsTypeMapId(cdtScAwdPriXpsTypeMapId);
        setCdtScAwdPriId(cdtScAwdPriId);
        setXbtId(xbtId);
    }
}
