/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.repo.api.impl.jooq.entity.tables.records;


import java.time.LocalDateTime;

import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.oagi.score.repo.api.impl.jooq.entity.tables.ModuleXbtManifest;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ModuleXbtManifestRecord extends UpdatableRecordImpl<ModuleXbtManifestRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.module_xbt_manifest.module_xbt_manifest_id</code>.
     * Primary key.
     */
    public void setModuleXbtManifestId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.module_xbt_manifest.module_xbt_manifest_id</code>.
     * Primary key.
     */
    public ULong getModuleXbtManifestId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>oagi.module_xbt_manifest.module_set_release_id</code>. A
     * foreign key of the module set release record.
     */
    public void setModuleSetReleaseId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.module_xbt_manifest.module_set_release_id</code>. A
     * foreign key of the module set release record.
     */
    public ULong getModuleSetReleaseId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>oagi.module_xbt_manifest.xbt_manifest_id</code>. A
     * foreign key of the xbt manifest record.
     */
    public void setXbtManifestId(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.module_xbt_manifest.xbt_manifest_id</code>. A
     * foreign key of the xbt manifest record.
     */
    public ULong getXbtManifestId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>oagi.module_xbt_manifest.module_id</code>. This
     * indicates a module.
     */
    public void setModuleId(ULong value) {
        set(3, value);
    }

    /**
     * Getter for <code>oagi.module_xbt_manifest.module_id</code>. This
     * indicates a module.
     */
    public ULong getModuleId() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>oagi.module_xbt_manifest.created_by</code>. Foreign key
     * to the APP_USER table. It indicates the user who created this record.
     */
    public void setCreatedBy(ULong value) {
        set(4, value);
    }

    /**
     * Getter for <code>oagi.module_xbt_manifest.created_by</code>. Foreign key
     * to the APP_USER table. It indicates the user who created this record.
     */
    public ULong getCreatedBy() {
        return (ULong) get(4);
    }

    /**
     * Setter for <code>oagi.module_xbt_manifest.last_updated_by</code>. Foreign
     * key to the APP_USER table referring to the last user who updated the
     * record.
     */
    public void setLastUpdatedBy(ULong value) {
        set(5, value);
    }

    /**
     * Getter for <code>oagi.module_xbt_manifest.last_updated_by</code>. Foreign
     * key to the APP_USER table referring to the last user who updated the
     * record.
     */
    public ULong getLastUpdatedBy() {
        return (ULong) get(5);
    }

    /**
     * Setter for <code>oagi.module_xbt_manifest.creation_timestamp</code>. The
     * timestamp when the record was first created.
     */
    public void setCreationTimestamp(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>oagi.module_xbt_manifest.creation_timestamp</code>. The
     * timestamp when the record was first created.
     */
    public LocalDateTime getCreationTimestamp() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>oagi.module_xbt_manifest.last_update_timestamp</code>.
     * The timestamp when the record was last updated.
     */
    public void setLastUpdateTimestamp(LocalDateTime value) {
        set(7, value);
    }

    /**
     * Getter for <code>oagi.module_xbt_manifest.last_update_timestamp</code>.
     * The timestamp when the record was last updated.
     */
    public LocalDateTime getLastUpdateTimestamp() {
        return (LocalDateTime) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ModuleXbtManifestRecord
     */
    public ModuleXbtManifestRecord() {
        super(ModuleXbtManifest.MODULE_XBT_MANIFEST);
    }

    /**
     * Create a detached, initialised ModuleXbtManifestRecord
     */
    public ModuleXbtManifestRecord(ULong moduleXbtManifestId, ULong moduleSetReleaseId, ULong xbtManifestId, ULong moduleId, ULong createdBy, ULong lastUpdatedBy, LocalDateTime creationTimestamp, LocalDateTime lastUpdateTimestamp) {
        super(ModuleXbtManifest.MODULE_XBT_MANIFEST);

        setModuleXbtManifestId(moduleXbtManifestId);
        setModuleSetReleaseId(moduleSetReleaseId);
        setXbtManifestId(xbtManifestId);
        setModuleId(moduleId);
        setCreatedBy(createdBy);
        setLastUpdatedBy(lastUpdatedBy);
        setCreationTimestamp(creationTimestamp);
        setLastUpdateTimestamp(lastUpdateTimestamp);
        resetChangedOnNotNull();
    }
}
