ALTER TABLE ABIE DROP CONSTRAINT ABIE_FK1;
ALTER TABLE ABIE DROP CONSTRAINT ABIE_FK2;
ALTER TABLE ABIE DROP CONSTRAINT ABIE_FK3;
ALTER TABLE ABIE DROP CONSTRAINT ABIE_FK4;
ALTER TABLE ABIE DROP CONSTRAINT ABIE_FK5;
ALTER TABLE ACC DROP CONSTRAINT ACC_FK1;
ALTER TABLE ACC DROP CONSTRAINT ACC_FK2;
ALTER TABLE ACC DROP CONSTRAINT ACC_FK3;
ALTER TABLE ACC DROP CONSTRAINT ACC_FK4;
ALTER TABLE ACC DROP CONSTRAINT ACC_FK5;
ALTER TABLE ACC DROP CONSTRAINT ACC_FK6;
ALTER TABLE ACC DROP CONSTRAINT ACC_FK7;
ALTER TABLE ACC DROP CONSTRAINT ACC_FK8;
ALTER TABLE AGENCY_ID_LIST DROP CONSTRAINT AGENCY_ID_LIST_FK1;
ALTER TABLE AGENCY_ID_LIST DROP CONSTRAINT AGENCY_ID_LIST_FK2;
ALTER TABLE ASBIEP DROP CONSTRAINT ASBIEP_FK1;
ALTER TABLE ASBIEP DROP CONSTRAINT ASBIEP_FK2;
ALTER TABLE ASBIEP DROP CONSTRAINT ASBIEP_FK3;
ALTER TABLE ASBIEP DROP CONSTRAINT ASBIEP_FK4;
ALTER TABLE ASBIEP DROP CONSTRAINT ASBIEP_FK5;
ALTER TABLE ASBIE DROP CONSTRAINT ASBIE_FK1;
ALTER TABLE ASBIE DROP CONSTRAINT ASBIE_FK2;
ALTER TABLE ASBIE DROP CONSTRAINT ASBIE_FK3;
ALTER TABLE ASBIE DROP CONSTRAINT ASBIE_FK4;
ALTER TABLE ASBIE DROP CONSTRAINT ASBIE_FK5;
ALTER TABLE ASBIE DROP CONSTRAINT ASBIE_FK6;
ALTER TABLE ASCCP DROP CONSTRAINT ASCCP_FK1;
ALTER TABLE ASCCP DROP CONSTRAINT ASCCP_FK2;
ALTER TABLE ASCCP DROP CONSTRAINT ASCCP_FK3;
ALTER TABLE ASCCP DROP CONSTRAINT ASCCP_FK4;
ALTER TABLE ASCCP DROP CONSTRAINT ASCCP_FK5;
ALTER TABLE ASCCP DROP CONSTRAINT ASCCP_FK6;
ALTER TABLE ASCCP DROP CONSTRAINT ASCCP_FK7;
ALTER TABLE ASCCP DROP CONSTRAINT ASCCP_FK8;
ALTER TABLE ASCC DROP CONSTRAINT ASCC_FK1;
ALTER TABLE ASCC DROP CONSTRAINT ASCC_FK2;
ALTER TABLE ASCC DROP CONSTRAINT ASCC_FK3;
ALTER TABLE ASCC DROP CONSTRAINT ASCC_FK4;
ALTER TABLE ASCC DROP CONSTRAINT ASCC_FK5;
ALTER TABLE ASCC DROP CONSTRAINT ASCC_FK6;
ALTER TABLE ASCC DROP CONSTRAINT ASCC_FK7;
ALTER TABLE BBIEP DROP CONSTRAINT BBIEP_FK1;
ALTER TABLE BBIEP DROP CONSTRAINT BBIEP_FK2;
ALTER TABLE BBIEP DROP CONSTRAINT BBIEP_FK3;
ALTER TABLE BBIEP DROP CONSTRAINT BBIEP_FK4;
ALTER TABLE BBIE DROP CONSTRAINT BBIE_FK1;
ALTER TABLE BBIE DROP CONSTRAINT BBIE_FK2;
ALTER TABLE BBIE DROP CONSTRAINT BBIE_FK3;
ALTER TABLE BBIE DROP CONSTRAINT BBIE_FK4;
ALTER TABLE BBIE DROP CONSTRAINT BBIE_FK5;
ALTER TABLE BBIE DROP CONSTRAINT BBIE_FK6;
ALTER TABLE BBIE DROP CONSTRAINT BBIE_FK7;
ALTER TABLE BBIE DROP CONSTRAINT BBIE_FK8;
ALTER TABLE BBIE DROP CONSTRAINT BBIE_FK9;
ALTER TABLE BBIE_SC DROP CONSTRAINT BBIE_SC_FK1;
ALTER TABLE BBIE_SC DROP CONSTRAINT BBIE_SC_FK2;
ALTER TABLE BBIE_SC DROP CONSTRAINT BBIE_SC_FK3;
ALTER TABLE BBIE_SC DROP CONSTRAINT BBIE_SC_FK4;
ALTER TABLE BBIE_SC DROP CONSTRAINT BBIE_SC_FK5;
ALTER TABLE BBIE_SC DROP CONSTRAINT BBIE_SC_FK6;
ALTER TABLE BCCP DROP CONSTRAINT BCCP_FK1;
ALTER TABLE BCCP DROP CONSTRAINT BCCP_FK2;
ALTER TABLE BCCP DROP CONSTRAINT BCCP_FK3;
ALTER TABLE BCCP DROP CONSTRAINT BCCP_FK4;
ALTER TABLE BCCP DROP CONSTRAINT BCCP_FK5;
ALTER TABLE BCCP DROP CONSTRAINT BCCP_FK6;
ALTER TABLE BCCP DROP CONSTRAINT BCCP_FK7;
ALTER TABLE BCCP DROP CONSTRAINT BCCP_FK8;
ALTER TABLE BCC DROP CONSTRAINT BCC_FK1;
ALTER TABLE BCC DROP CONSTRAINT BCC_FK2;
ALTER TABLE BCC DROP CONSTRAINT BCC_FK3;
ALTER TABLE BCC DROP CONSTRAINT BCC_FK4;
ALTER TABLE BCC DROP CONSTRAINT BCC_FK5;
ALTER TABLE BCC DROP CONSTRAINT BCC_FK6;
ALTER TABLE BCC DROP CONSTRAINT BCC_FK7;
ALTER TABLE BDT_PRI_RESTRI DROP CONSTRAINT BDT_PRI_RESTRI_FK1;
ALTER TABLE BDT_PRI_RESTRI DROP CONSTRAINT BDT_PRI_RESTRI_FK2;
ALTER TABLE BDT_PRI_RESTRI DROP CONSTRAINT BDT_PRI_RESTRI_FK3;
ALTER TABLE BDT_PRI_RESTRI DROP CONSTRAINT BDT_PRI_RESTRI_FK4;
ALTER TABLE BDT_SC_PRI_RESTRI DROP CONSTRAINT BDT_SC_PRI_RESTRI_FK1;
ALTER TABLE BDT_SC_PRI_RESTRI DROP CONSTRAINT BDT_SC_PRI_RESTRI_FK2;
ALTER TABLE BDT_SC_PRI_RESTRI DROP CONSTRAINT BDT_SC_PRI_RESTRI_FK3;
ALTER TABLE BDT_SC_PRI_RESTRI DROP CONSTRAINT BDT_SC_PRI_RESTRI_FK4;
ALTER TABLE BIE_USER_EXT_REVISION DROP CONSTRAINT BIE_USER_EXT_REVISION_FK1;
ALTER TABLE BIE_USER_EXT_REVISION DROP CONSTRAINT BIE_USER_EXT_REVISION_FK2;
ALTER TABLE BIE_USER_EXT_REVISION DROP CONSTRAINT BIE_USER_EXT_REVISION_FK3;
ALTER TABLE BIE_USER_EXT_REVISION DROP CONSTRAINT BIE_USER_EXT_REVISION_FK4;
ALTER TABLE BIZ_CTX DROP CONSTRAINT BIZ_CTX_FK1;
ALTER TABLE BIZ_CTX DROP CONSTRAINT BIZ_CTX_FK2;
ALTER TABLE BIZ_CTX_VALUE DROP CONSTRAINT BIZ_CTX_VALUE_FK1;
ALTER TABLE BIZ_CTX_VALUE DROP CONSTRAINT BIZ_CTX_VALUE_FK2;
ALTER TABLE BLOB_CONTENT DROP CONSTRAINT BLOB_CONTENT_FK1;
ALTER TABLE BLOB_CONTENT DROP CONSTRAINT BLOB_CONTENT_FK2;
ALTER TABLE CDT_AWD_PRI_XPS_TYPE_MAP DROP CONSTRAINT CDT_AWD_PRI_XPS_TYPE_MAP_FK1;
ALTER TABLE CDT_AWD_PRI_XPS_TYPE_MAP DROP CONSTRAINT CDT_AWD_PRI_XPS_TYPE_MAP_FK2;
ALTER TABLE CDT_SC_AWD_PRI DROP CONSTRAINT CDT_SC_AWD_PRI_FK1;
ALTER TABLE CDT_SC_AWD_PRI DROP CONSTRAINT CDT_SC_AWD_PRI_FK2;
ALTER TABLE CDT_SC_AWD_PRI_XPS_TYPE_MAP DROP CONSTRAINT CDT_SC_AWD_PRI_XPS_TYPE_MAP_FK1;
ALTER TABLE CDT_SC_AWD_PRI_XPS_TYPE_MAP DROP CONSTRAINT CDT_SC_AWD_PRI_XPS_TYPE_MAP_FK2;
ALTER TABLE CODE_LIST DROP CONSTRAINT CODE_LIST_FK1;
ALTER TABLE CODE_LIST DROP CONSTRAINT CODE_LIST_FK2;
ALTER TABLE CODE_LIST DROP CONSTRAINT CODE_LIST_FK3;
ALTER TABLE CODE_LIST DROP CONSTRAINT CODE_LIST_FK4;
ALTER TABLE CODE_LIST DROP CONSTRAINT CODE_LIST_FK5;
ALTER TABLE CODE_LIST_VALUE DROP CONSTRAINT CODE_LIST_VALUE_FK1;
ALTER TABLE CTX_SCHEME DROP CONSTRAINT CTX_SCHEME_FK1;
ALTER TABLE CTX_SCHEME DROP CONSTRAINT CTX_SCHEME_FK2;
ALTER TABLE CTX_SCHEME DROP CONSTRAINT CTX_SCHEME_FK3;
ALTER TABLE CTX_SCHEME_VALUE DROP CONSTRAINT CTX_SCHEME_VALUE_FK1;
ALTER TABLE DT DROP CONSTRAINT DT_FK1;
ALTER TABLE DT DROP CONSTRAINT DT_FK2;
ALTER TABLE DT DROP CONSTRAINT DT_FK3;
ALTER TABLE DT DROP CONSTRAINT DT_FK4;
ALTER TABLE DT DROP CONSTRAINT DT_FK5;
ALTER TABLE DT DROP CONSTRAINT DT_FK6;
ALTER TABLE DT DROP CONSTRAINT DT_FK7;
ALTER TABLE DT DROP CONSTRAINT DT_FK8;
ALTER TABLE DT_SC DROP CONSTRAINT DT_SC_FK1;
ALTER TABLE DT_SC DROP CONSTRAINT DT_SC_FK2;
ALTER TABLE MODULE_DEP DROP CONSTRAINT MODULE_DEP_FK1;
ALTER TABLE MODULE_DEP DROP CONSTRAINT MODULE_DEP_FK2;
ALTER TABLE MODULE DROP CONSTRAINT MODULE_FK1;
ALTER TABLE MODULE DROP CONSTRAINT MODULE_FK2;
ALTER TABLE NAMESPACE DROP CONSTRAINT NAMESPACE_FK1;
ALTER TABLE NAMESPACE DROP CONSTRAINT NAMESPACE_FK2;
ALTER TABLE NAMESPACE DROP CONSTRAINT NAMESPACE_FK3;
ALTER TABLE RELEASE DROP CONSTRAINT RELEASE_FK1;
ALTER TABLE TOP_LEVEL_ABIE DROP CONSTRAINT TOP_LEVEL_ABIE_FK1;
ALTER TABLE TOP_LEVEL_ABIE DROP CONSTRAINT TOP_LEVEL_ABIE_FK2;
ALTER TABLE XBT DROP CONSTRAINT XBT_FK1;


DROP TABLE IF EXISTS ABIE;
CREATE TABLE IF NOT EXISTS ABIE
(
  ABIE_ID                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  GUID                    VARCHAR(41) NOT NULL,
  BASED_ACC_ID            BIGINT NOT NULL,
  BIZ_CTX_ID              BIGINT NOT NULL,
  DEFINITION              CLOB,
  CREATED_BY              BIGINT NOT NULL,
  LAST_UPDATED_BY         BIGINT NOT NULL,
  CREATION_TIMESTAMP      TIMESTAMP WITH TIME ZONE NOT NULL,
  LAST_UPDATE_TIMESTAMP   TIMESTAMP WITH TIME ZONE NOT NULL,
  STATE                   INTEGER,
  CLIENT_ID               BIGINT,
  VERSION                 VARCHAR(45),
  STATUS                  VARCHAR(45),
  REMARK                  VARCHAR(225),
  BIZ_TERM                VARCHAR(225),
  OWNER_TOP_LEVEL_ABIE_ID BIGINT NOT NULL
);

DROP TABLE IF EXISTS ACC;
CREATE TABLE IF NOT EXISTS ACC
(
  ACC_ID                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  GUID                   VARCHAR(41) NOT NULL,
  OBJECT_CLASS_TERM      VARCHAR(100) NOT NULL,
  DEN                    VARCHAR(200) NOT NULL,
  DEFINITION             CLOB,
  BASED_ACC_ID           BIGINT,
  OBJECT_CLASS_QUALIFIER VARCHAR(100),
  OAGIS_COMPONENT_TYPE   NUMERIC(10),
  MODULE_ID              BIGINT,
  NAMESPACE_ID           BIGINT,
  CREATED_BY             BIGINT NOT NULL,
  OWNER_USER_ID          BIGINT NOT NULL,
  LAST_UPDATED_BY        BIGINT NOT NULL,
  CREATION_TIMESTAMP     TIMESTAMP WITH TIME ZONE NOT NULL,
  LAST_UPDATE_TIMESTAMP  TIMESTAMP WITH TIME ZONE NOT NULL,
  STATE                  NUMERIC(10) NOT NULL,
  REVISION_NUM           NUMERIC(10) NOT NULL,
  REVISION_TRACKING_NUM  NUMERIC(10) NOT NULL,
  REVISION_ACTION        NUMERIC(3),
  RELEASE_ID             BIGINT,
  CURRENT_ACC_ID         BIGINT,
  IS_DEPRECATED          CHAR(1),
  IS_ABSTRACT            CHAR(1)
);

DROP TABLE IF EXISTS AGENCY_ID_LIST;
CREATE TABLE IF NOT EXISTS AGENCY_ID_LIST
(
  AGENCY_ID_LIST_ID       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  GUID                    VARCHAR(41),
  ENUM_TYPE_GUID          VARCHAR(41) NOT NULL,
  NAME                    VARCHAR(100),
  LIST_ID                 VARCHAR(10),
  AGENCY_ID_LIST_VALUE_ID BIGINT,
  VERSION_ID              VARCHAR(10),
  MODULE_ID               BIGINT,
  DEFINITION              CLOB
);

DROP TABLE IF EXISTS AGENCY_ID_LIST_VALUE;
CREATE TABLE IF NOT EXISTS AGENCY_ID_LIST_VALUE
(
  AGENCY_ID_LIST_VALUE_ID BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  VALUE                   VARCHAR(150) NOT NULL,
  NAME                    VARCHAR(150),
  DEFINITION              CLOB,
  OWNER_LIST_ID BIGINT NOT NULL
);

DROP TABLE IF EXISTS APP_USER;
CREATE TABLE IF NOT EXISTS APP_USER
(
  APP_USER_ID               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  LOGIN_ID                  VARCHAR(45) NOT NULL,
  PASSWORD                  VARCHAR(100) NOT NULL,
  NAME                      VARCHAR(100),
  ORGANIZATION              VARCHAR(100),
  OAGIS_DEVELOPER_INDICATOR CHAR(1) NOT NULL
);

DROP TABLE IF EXISTS ASBIE;
CREATE TABLE IF NOT EXISTS ASBIE
(
  ASBIE_ID                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  GUID                    VARCHAR(41) NOT NULL,
  FROM_ABIE_ID            BIGINT NOT NULL,
  TO_ASBIEP_ID            BIGINT NOT NULL,
  BASED_ASCC_ID           BIGINT NOT NULL,
  DEFINITION              CLOB,
  CARDINALITY_MIN         NUMERIC(10) NOT NULL,
  CARDINALITY_MAX         NUMERIC(10) NOT NULL,
  IS_NILLABLE             CHAR(1) NOT NULL,
  REMARK                  VARCHAR(225),
  CREATED_BY              BIGINT NOT NULL,
  LAST_UPDATED_BY         BIGINT NOT NULL,
  CREATION_TIMESTAMP      TIMESTAMP WITH TIME ZONE NOT NULL,
  LAST_UPDATE_TIMESTAMP   TIMESTAMP WITH TIME ZONE NOT NULL,
  SEQ_KEY                 NUMERIC(10,2) NOT NULL,
  IS_USED                 CHAR(1) NOT NULL,
  OWNER_TOP_LEVEL_ABIE_ID BIGINT NOT NULL
);

DROP TABLE IF EXISTS ASBIEP;
CREATE TABLE IF NOT EXISTS ASBIEP
(
  ASBIEP_ID               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  GUID                    VARCHAR(41) NOT NULL,
  BASED_ASCCP_ID          BIGINT NOT NULL,
  ROLE_OF_ABIE_ID         BIGINT NOT NULL,
  DEFINITION              CLOB,
  REMARK                  VARCHAR(225),
  BIZ_TERM                VARCHAR(225),
  CREATED_BY              BIGINT NOT NULL,
  LAST_UPDATED_BY         BIGINT NOT NULL,
  CREATION_TIMESTAMP      TIMESTAMP WITH TIME ZONE NOT NULL,
  LAST_UPDATE_TIMESTAMP   TIMESTAMP WITH TIME ZONE NOT NULL,
  OWNER_TOP_LEVEL_ABIE_ID BIGINT NOT NULL
);

DROP TABLE IF EXISTS ASCC;
CREATE TABLE IF NOT EXISTS ASCC
(
  ASCC_ID               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  GUID                  VARCHAR(41) NOT NULL,
  CARDINALITY_MIN       NUMERIC(10) NOT NULL,
  CARDINALITY_MAX       NUMERIC(10) NOT NULL,
  SEQ_KEY               NUMERIC(10) NOT NULL,
  FROM_ACC_ID           BIGINT NOT NULL,
  TO_ASCCP_ID           BIGINT NOT NULL,
  DEN                   VARCHAR(200) NOT NULL,
  DEFINITION            CLOB,
  IS_DEPRECATED         CHAR(1) NOT NULL,
  CREATED_BY            BIGINT NOT NULL,
  OWNER_USER_ID         BIGINT NOT NULL,
  LAST_UPDATED_BY       BIGINT NOT NULL,
  CREATION_TIMESTAMP    TIMESTAMP WITH TIME ZONE NOT NULL,
  LAST_UPDATE_TIMESTAMP TIMESTAMP WITH TIME ZONE NOT NULL,
  STATE                 NUMERIC(10) NOT NULL,
  REVISION_NUM          NUMERIC(10) NOT NULL,
  REVISION_TRACKING_NUM NUMERIC(10) NOT NULL,
  REVISION_ACTION       NUMERIC(3),
  RELEASE_ID            BIGINT,
  CURRENT_ASCC_ID       BIGINT
);

DROP TABLE IF EXISTS ASCCP;
CREATE TABLE IF NOT EXISTS ASCCP
(
  ASCCP_ID              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  GUID                  VARCHAR(41) NOT NULL,
  PROPERTY_TERM         VARCHAR(60),
  DEFINITION            CLOB,
  ROLE_OF_ACC_ID        BIGINT,
  DEN                   VARCHAR(200),
  CREATED_BY            BIGINT NOT NULL,
  OWNER_USER_ID         BIGINT NOT NULL,
  LAST_UPDATED_BY       BIGINT NOT NULL,
  CREATION_TIMESTAMP    TIMESTAMP WITH TIME ZONE NOT NULL,
  LAST_UPDATE_TIMESTAMP TIMESTAMP WITH TIME ZONE NOT NULL,
  STATE                 NUMERIC(10) NOT NULL,
  MODULE_ID             BIGINT,
  NAMESPACE_ID          BIGINT,
  REUSABLE_INDICATOR    CHAR(1),
  IS_DEPRECATED         CHAR(1) NOT NULL,
  REVISION_NUM          NUMERIC(10) NOT NULL,
  REVISION_TRACKING_NUM NUMERIC(10) NOT NULL,
  REVISION_ACTION       NUMERIC(3),
  RELEASE_ID            BIGINT,
  CURRENT_ASCCP_ID      BIGINT,
  IS_NILLABLE           CHAR(1)
);

DROP TABLE IF EXISTS BBIE;
CREATE TABLE IF NOT EXISTS BBIE
(
  BBIE_ID                 BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  GUID                    VARCHAR(41) NOT NULL,
  BASED_BCC_ID            BIGINT NOT NULL,
  FROM_ABIE_ID            BIGINT NOT NULL,
  TO_BBIEP_ID             BIGINT NOT NULL,
  BDT_PRI_RESTRI_ID       BIGINT,
  CODE_LIST_ID            BIGINT,
  AGENCY_ID_LIST_ID       BIGINT,
  CARDINALITY_MIN         NUMERIC(10) NOT NULL,
  CARDINALITY_MAX         NUMERIC(10),
  DEFAULT_VALUE           CLOB,
  IS_NILLABLE             CHAR(1) NOT NULL,
  FIXED_VALUE             CLOB,
  IS_NULL                 CHAR(1) NOT NULL,
  DEFINITION              CLOB,
  REMARK                  VARCHAR(225),
  CREATED_BY              BIGINT NOT NULL,
  LAST_UPDATED_BY         BIGINT NOT NULL,
  CREATION_TIMESTAMP      TIMESTAMP WITH TIME ZONE NOT NULL,
  LAST_UPDATE_TIMESTAMP   TIMESTAMP WITH TIME ZONE NOT NULL,
  SEQ_KEY                 NUMERIC(10,2),
  IS_USED                 CHAR(1),
  OWNER_TOP_LEVEL_ABIE_ID BIGINT NOT NULL
);

DROP TABLE IF EXISTS BBIEP;
CREATE TABLE IF NOT EXISTS BBIEP
(
  BBIEP_ID                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  GUID                    VARCHAR(41) NOT NULL,
  BASED_BCCP_ID           BIGINT NOT NULL,
  DEFINITION              CLOB,
  REMARK                  VARCHAR(225),
  BIZ_TERM                VARCHAR(225),
  CREATED_BY              BIGINT NOT NULL,
  LAST_UPDATED_BY         BIGINT NOT NULL,
  CREATION_TIMESTAMP      TIMESTAMP WITH TIME ZONE NOT NULL,
  LAST_UPDATE_TIMESTAMP   TIMESTAMP WITH TIME ZONE NOT NULL,
  OWNER_TOP_LEVEL_ABIE_ID BIGINT NOT NULL
);

DROP TABLE IF EXISTS BBIE_SC;
CREATE TABLE IF NOT EXISTS BBIE_SC
(
  BBIE_SC_ID              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  GUID                    VARCHAR(41) NOT NULL,
  BBIE_ID                 BIGINT NOT NULL,
  DT_SC_ID                BIGINT NOT NULL,
  DT_SC_PRI_RESTRI_ID     BIGINT,
  CODE_LIST_ID            BIGINT,
  AGENCY_ID_LIST_ID       BIGINT,
  CARDINALITY_MIN         NUMERIC(10) NOT NULL,
  CARDINALITY_MAX         NUMERIC(10) NOT NULL,
  DEFAULT_VALUE           CLOB,
  FIXED_VALUE             CLOB,
  DEFINITION              CLOB,
  REMARK                  VARCHAR(225),
  BIZ_TERM                VARCHAR(225),
  IS_USED                 CHAR(1) NOT NULL,
  OWNER_TOP_LEVEL_ABIE_ID BIGINT NOT NULL
);

DROP TABLE IF EXISTS BCC;
CREATE TABLE IF NOT EXISTS BCC
(
  BCC_ID                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  GUID                  VARCHAR(41) NOT NULL,
  CARDINALITY_MIN       NUMERIC(10) NOT NULL,
  CARDINALITY_MAX       NUMERIC(10),
  TO_BCCP_ID            BIGINT NOT NULL,
  FROM_ACC_ID           BIGINT NOT NULL,
  SEQ_KEY               NUMERIC(10),
  ENTITY_TYPE           NUMERIC(10),
  DEN                   VARCHAR(200) NOT NULL,
  DEFINITION            CLOB,
  CREATED_BY            BIGINT NOT NULL,
  OWNER_USER_ID         BIGINT NOT NULL,
  LAST_UPDATED_BY       BIGINT NOT NULL,
  CREATION_TIMESTAMP    TIMESTAMP WITH TIME ZONE NOT NULL,
  LAST_UPDATE_TIMESTAMP TIMESTAMP WITH TIME ZONE NOT NULL,
  STATE                 NUMERIC(10) NOT NULL,
  REVISION_NUM          NUMERIC(10) NOT NULL,
  REVISION_TRACKING_NUM NUMERIC(10) NOT NULL,
  REVISION_ACTION       NUMERIC(3),
  RELEASE_ID            BIGINT,
  CURRENT_BCC_ID        BIGINT,
  IS_DEPRECATED         CHAR(1) NOT NULL,
  IS_NILLABLE           CHAR(1) NOT NULL,
  DEFAULT_VALUE         CLOB
);

DROP TABLE IF EXISTS BCCP;
CREATE TABLE IF NOT EXISTS BCCP
(
  BCCP_ID               BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  GUID                  VARCHAR(41) NOT NULL,
  PROPERTY_TERM         VARCHAR(60) NOT NULL,
  REPRESENTATION_TERM   VARCHAR(20) NOT NULL,
  BDT_ID                BIGINT NOT NULL,
  DEN                   VARCHAR(200) NOT NULL,
  DEFINITION            CLOB,
  MODULE_ID             BIGINT,
  NAMESPACE_ID          BIGINT,
  IS_DEPRECATED         CHAR(1) NOT NULL,
  CREATED_BY            BIGINT NOT NULL,
  OWNER_USER_ID         BIGINT NOT NULL,
  LAST_UPDATED_BY       BIGINT NOT NULL,
  CREATION_TIMESTAMP    TIMESTAMP WITH TIME ZONE NOT NULL,
  LAST_UPDATE_TIMESTAMP TIMESTAMP WITH TIME ZONE NOT NULL,
  STATE                 NUMERIC(10) NOT NULL,
  REVISION_NUM          NUMERIC(10) NOT NULL,
  REVISION_TRACKING_NUM NUMERIC(10) NOT NULL,
  REVISION_ACTION       NUMERIC(10),
  RELEASE_ID            BIGINT,
  CURRENT_BCCP_ID       BIGINT,
  IS_NILLABLE           CHAR(1),
  DEFAULT_VALUE         CLOB
);

DROP TABLE IF EXISTS BDT_PRI_RESTRI;
CREATE TABLE IF NOT EXISTS BDT_PRI_RESTRI
(
  BDT_PRI_RESTRI_ID           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  BDT_ID                      BIGINT NOT NULL,
  CDT_AWD_PRI_XPS_TYPE_MAP_ID BIGINT,
  CODE_LIST_ID                BIGINT,
  AGENCY_ID_LIST_ID           BIGINT,
  IS_DEFAULT                  CHAR(1) NOT NULL
);

DROP TABLE IF EXISTS BDT_SC_PRI_RESTRI;
CREATE TABLE IF NOT EXISTS BDT_SC_PRI_RESTRI
(
  BDT_SC_PRI_RESTRI_ID           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  BDT_SC_ID                      BIGINT NOT NULL,
  CDT_SC_AWD_PRI_XPS_TYPE_MAP_ID BIGINT,
  CODE_LIST_ID                   BIGINT,
  AGENCY_ID_LIST_ID              BIGINT,
  IS_DEFAULT                     CHAR(1) NOT NULL
);

DROP TABLE IF EXISTS BIE_USER_EXT_REVISION;
CREATE TABLE IF NOT EXISTS BIE_USER_EXT_REVISION
(
  BIE_USER_EXT_REVISION_ID BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  TOP_LEVEL_ABIE_ID        BIGINT NOT NULL,
  EXT_ABIE_ID              BIGINT,
  EXT_ACC_ID               BIGINT NOT NULL,
  USER_EXT_ACC_ID          BIGINT NOT NULL,
  REVISED_INDICATOR        CHAR(1) NOT NULL
);

DROP TABLE IF EXISTS BIZ_CTX;
CREATE TABLE IF NOT EXISTS BIZ_CTX
(
  BIZ_CTX_ID            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  GUID                  VARCHAR(41) NOT NULL,
  NAME                  VARCHAR(100),
  CREATED_BY            BIGINT NOT NULL,
  LAST_UPDATED_BY       BIGINT NOT NULL,
  CREATION_TIMESTAMP    TIMESTAMP WITH TIME ZONE NOT NULL,
  LAST_UPDATE_TIMESTAMP TIMESTAMP WITH TIME ZONE NOT NULL
);

DROP TABLE IF EXISTS BIZ_CTX_VALUE;
CREATE TABLE IF NOT EXISTS BIZ_CTX_VALUE
(
  BIZ_CTX_VALUE_ID    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  BIZ_CTX_ID          BIGINT NOT NULL,
  CTX_SCHEME_VALUE_ID BIGINT NOT NULL
);

DROP TABLE IF EXISTS BLOB_CONTENT;
CREATE TABLE IF NOT EXISTS BLOB_CONTENT
(
  BLOB_CONTENT_ID BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  CONTENT         BLOB NOT NULL,
  RELEASE_ID      BIGINT NOT NULL,
  MODULE_ID       BIGINT NOT NULL
);

DROP TABLE IF EXISTS CDT_AWD_PRI;
CREATE TABLE IF NOT EXISTS CDT_AWD_PRI
(
  CDT_AWD_PRI_ID BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  CDT_ID         BIGINT NOT NULL,
  CDT_PRI_ID     BIGINT NOT NULL,
  IS_DEFAULT     CHAR (1) NOT NULL
);

DROP TABLE IF EXISTS CDT_AWD_PRI_XPS_TYPE_MAP;
CREATE TABLE IF NOT EXISTS CDT_AWD_PRI_XPS_TYPE_MAP
(
  CDT_AWD_PRI_XPS_TYPE_MAP_ID BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  CDT_AWD_PRI_ID              BIGINT NOT NULL,
  XBT_ID                      BIGINT NOT NULL
);

DROP TABLE IF EXISTS CDT_PRI;
CREATE TABLE IF NOT EXISTS CDT_PRI
(
  CDT_PRI_ID BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  NAME       VARCHAR(45) NOT NULL
);

DROP TABLE IF EXISTS CDT_SC_AWD_PRI;
CREATE TABLE IF NOT EXISTS CDT_SC_AWD_PRI
(
  CDT_SC_AWD_PRI_ID BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  CDT_SC_ID         BIGINT NOT NULL,
  CDT_PRI_ID        BIGINT NOT NULL,
  IS_DEFAULT        CHAR(1) NOT NULL
);

DROP TABLE IF EXISTS CDT_SC_AWD_PRI_XPS_TYPE_MAP;
CREATE TABLE IF NOT EXISTS CDT_SC_AWD_PRI_XPS_TYPE_MAP
(
  CDT_SC_AWD_PRI_XPS_TYPE_MAP_ID BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  CDT_SC_AWD_PRI_ID              BIGINT NOT NULL,
  XBT_ID                         BIGINT NOT NULL
);

DROP TABLE IF EXISTS CLIENT;
CREATE TABLE IF NOT EXISTS CLIENT
(
  CLIENT_ID BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  NAME      VARCHAR(200)
);

DROP TABLE IF EXISTS CODE_LIST;
CREATE TABLE IF NOT EXISTS CODE_LIST
(
  CODE_LIST_ID          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  GUID                  VARCHAR(41) NOT NULL,
  ENUM_TYPE_GUID        VARCHAR(41),
  NAME                  VARCHAR(100),
  LIST_ID               VARCHAR(100) NOT NULL,
  AGENCY_ID             BIGINT,
  VERSION_ID            VARCHAR(10) NOT NULL,
  DEFINITION            CLOB,
  REMARK                VARCHAR(225),
  DEFINITION_SOURCE     VARCHAR(100),
  BASED_CODE_LIST_ID    BIGINT,
  EXTENSIBLE_INDICATOR  CHAR(1) NOT NULL,
  MODULE_ID             BIGINT,
  CREATED_BY            BIGINT NOT NULL,
  LAST_UPDATED_BY       BIGINT NOT NULL,
  CREATION_TIMESTAMP    TIMESTAMP WITH TIME ZONE NOT NULL,
  LAST_UPDATE_TIMESTAMP TIMESTAMP WITH TIME ZONE NOT NULL,
  STATE                 VARCHAR(10)
);

DROP TABLE IF EXISTS CODE_LIST_VALUE;
CREATE TABLE IF NOT EXISTS CODE_LIST_VALUE
(
  CODE_LIST_VALUE_ID  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  CODE_LIST_ID        BIGINT NOT NULL,
  VALUE               VARCHAR(100) NOT NULL,
  NAME                VARCHAR(100),
  DEFINITION          CLOB,
  DEFINITION_SOURCE   VARCHAR(100),
  USED_INDICATOR      CHAR(1) NOT NULL,
  LOCKED_INDICATOR    CHAR(1) NOT NULL,
  EXTENSION_INDICATOR CHAR(1) NOT NULL
);

DROP TABLE IF EXISTS CTX_CATEGORY;
CREATE TABLE IF NOT EXISTS CTX_CATEGORY
(
  CTX_CATEGORY_ID BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  GUID            VARCHAR(41) NOT NULL,
  NAME            VARCHAR(45),
  DESCRIPTION     CLOB
);

DROP TABLE IF EXISTS CTX_SCHEME;
CREATE TABLE IF NOT EXISTS CTX_SCHEME
(
  CTX_SCHEME_ID         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  GUID                  VARCHAR(41) NOT NULL,
  SCHEME_ID             VARCHAR(45) NOT NULL,
  SCHEME_NAME           VARCHAR(255),
  DESCRIPTION           CLOB,
  SCHEME_AGENCY_ID      VARCHAR(45) NOT NULL,
  SCHEME_VERSION_ID     VARCHAR(45) NOT NULL,
  CTX_CATEGORY_ID       BIGINT NOT NULL,
  CREATED_BY            BIGINT NOT NULL,
  LAST_UPDATED_BY       BIGINT NOT NULL,
  CREATION_TIMESTAMP    TIMESTAMP WITH TIME ZONE NOT NULL,
  LAST_UPDATE_TIMESTAMP TIMESTAMP WITH TIME ZONE NOT NULL
);

DROP TABLE IF EXISTS CTX_SCHEME_VALUE;
CREATE TABLE IF NOT EXISTS CTX_SCHEME_VALUE
(
  CTX_SCHEME_VALUE_ID BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  GUID                VARCHAR(41) NOT NULL,
  VALUE               VARCHAR(45) NOT NULL,
  MEANING             CLOB,
  OWNER_CTX_SCHEME_ID BIGINT
);

DROP TABLE IF EXISTS DT;
CREATE TABLE IF NOT EXISTS DT
(
  DT_ID                        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  GUID                         VARCHAR(41) NOT NULL,
  TYPE                         NUMERIC(10),
  VERSION_NUM                  VARCHAR(45) NOT NULL,
  PREVIOUS_VERSION_DT_ID       BIGINT,
  DATA_TYPE_TERM               VARCHAR(45),
  QUALIFIER                    VARCHAR(100),
  BASED_DT_ID                  BIGINT,
  DEN                          VARCHAR(200) NOT NULL,
  CONTENT_COMPONENT_DEN        VARCHAR(200),
  DEFINITION                   CLOB,
  CONTENT_COMPONENT_DEFINITION CLOB,
  REVISION_DOC                 CLOB,
  STATE                        NUMERIC(10),
  MODULE_ID                    BIGINT,
  CREATED_BY                   BIGINT NOT NULL,
  OWNER_USER_ID                BIGINT NOT NULL,
  LAST_UPDATED_BY              BIGINT NOT NULL,
  CREATION_TIMESTAMP           TIMESTAMP WITH TIME ZONE NOT NULL,
  LAST_UPDATE_TIMESTAMP        TIMESTAMP WITH TIME ZONE NOT NULL,
  REVISION_NUM                 NUMERIC(10) NOT NULL,
  REVISION_TRACKING_NUM        NUMERIC(10) NOT NULL,
  REVISION_ACTION              NUMERIC(3),
  RELEASE_ID                   BIGINT,
  CURRENT_BDT_ID               BIGINT,
  IS_DEPRECATED                CHAR(1) NOT NULL
);

DROP TABLE IF EXISTS DT_SC;
CREATE TABLE IF NOT EXISTS DT_SC
(
  DT_SC_ID            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  GUID                VARCHAR(41) NOT NULL,
  PROPERTY_TERM       VARCHAR(60),
  REPRESENTATION_TERM VARCHAR(20),
  DEFINITION          CLOB,
  OWNER_DT_ID         BIGINT,
  CARDINALITY_MIN     NUMERIC(10) NOT NULL,
  CARDINALITY_MAX     NUMERIC(10),
  BASED_DT_SC_ID      BIGINT
);

DROP TABLE IF EXISTS MODULE;
CREATE TABLE IF NOT EXISTS MODULE
(
  MODULE_ID    BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  MODULE       VARCHAR(100) NOT NULL,
  RELEASE_ID   BIGINT NOT NULL,
  NAMESPACE_ID BIGINT NOT NULL,
  VERSION_NUM  VARCHAR(45)
);

DROP TABLE IF EXISTS MODULE_DEP;
CREATE TABLE IF NOT EXISTS MODULE_DEP
(
  MODULE_DEP_ID       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  DEPENDENCY_TYPE     NUMERIC(10) NOT NULL,
  DEPENDING_MODULE_ID BIGINT NOT NULL,
  DEPENDED_MODULE_ID  BIGINT NOT NULL
);

DROP TABLE IF EXISTS NAMESPACE;
CREATE TABLE IF NOT EXISTS NAMESPACE
(
  NAMESPACE_ID          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  URI                   VARCHAR(100) NOT NULL,
  PREFIX                VARCHAR(45),
  DESCRIPTION           CLOB,
  IS_STD_NMSP           CHAR(1) NOT NULL,
  OWNER_USER_ID         BIGINT NOT NULL,
  CREATED_BY            BIGINT NOT NULL,
  LAST_UPDATED_BY       BIGINT NOT NULL,
  CREATION_TIMESTAMP    TIMESTAMP WITH TIME ZONE NOT NULL,
  LAST_UPDATE_TIMESTAMP TIMESTAMP WITH TIME ZONE NOT NULL
);

DROP TABLE IF EXISTS RELEASE;
CREATE TABLE IF NOT EXISTS RELEASE
(
  RELEASE_ID   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  RELEASE_NUM  VARCHAR(45),
  RELEASE_NOTE CLOB,
  NAMESPACE_ID BIGINT NOT NULL
);

DROP TABLE IF EXISTS TOP_LEVEL_ABIE;
CREATE TABLE IF NOT EXISTS TOP_LEVEL_ABIE
(
  TOP_LEVEL_ABIE_ID BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  ABIE_ID           BIGINT,
  OWNER_USER_ID     BIGINT NOT NULL,
  STATE             NUMERIC(10)
);

DROP TABLE IF EXISTS XBT;
CREATE TABLE IF NOT EXISTS XBT
(
  XBT_ID            BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
  NAME              VARCHAR(45),
  BUILTIN_TYPE      VARCHAR(45),
  SUBTYPE_OF_XBT_ID BIGINT
);


ALTER TABLE ABIE ADD CONSTRAINT ABIE_FK1 FOREIGN KEY (BASED_ACC_ID) REFERENCES ACC (ACC_ID);
ALTER TABLE ABIE ADD CONSTRAINT ABIE_FK2 FOREIGN KEY (BIZ_CTX_ID) REFERENCES BIZ_CTX (BIZ_CTX_ID);
ALTER TABLE ABIE ADD CONSTRAINT ABIE_FK3 FOREIGN KEY (CREATED_BY) REFERENCES APP_USER (APP_USER_ID);
ALTER TABLE ABIE ADD CONSTRAINT ABIE_FK4 FOREIGN KEY (LAST_UPDATED_BY) REFERENCES APP_USER (APP_USER_ID);
ALTER TABLE ABIE ADD CONSTRAINT ABIE_FK5 FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (CLIENT_ID);

ALTER TABLE ACC ADD CONSTRAINT ACC_FK1 FOREIGN KEY (BASED_ACC_ID) REFERENCES ACC (ACC_ID);
ALTER TABLE ACC ADD CONSTRAINT ACC_FK2 FOREIGN KEY (MODULE_ID) REFERENCES MODULE (MODULE_ID);
ALTER TABLE ACC ADD CONSTRAINT ACC_FK3 FOREIGN KEY (NAMESPACE_ID) REFERENCES NAMESPACE (NAMESPACE_ID);
ALTER TABLE ACC ADD CONSTRAINT ACC_FK4 FOREIGN KEY (CREATED_BY) REFERENCES APP_USER (APP_USER_ID);
ALTER TABLE ACC ADD CONSTRAINT ACC_FK5 FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER (APP_USER_ID);
ALTER TABLE ACC ADD CONSTRAINT ACC_FK6 FOREIGN KEY (LAST_UPDATED_BY) REFERENCES APP_USER (APP_USER_ID);
ALTER TABLE ACC ADD CONSTRAINT ACC_FK7 FOREIGN KEY (RELEASE_ID) REFERENCES RELEASE (RELEASE_ID);
ALTER TABLE ACC ADD CONSTRAINT ACC_FK8 FOREIGN KEY (CURRENT_ACC_ID) REFERENCES ACC (ACC_ID);

ALTER TABLE AGENCY_ID_LIST ADD CONSTRAINT AGENCY_ID_LIST_FK1 FOREIGN KEY (AGENCY_ID_LIST_VALUE_ID) REFERENCES AGENCY_ID_LIST_VALUE (AGENCY_ID_LIST_VALUE_ID);
ALTER TABLE AGENCY_ID_LIST ADD CONSTRAINT AGENCY_ID_LIST_FK2 FOREIGN KEY (MODULE_ID) REFERENCES MODULE (MODULE_ID);

ALTER TABLE ASBIE ADD CONSTRAINT ASBIE_FK1 FOREIGN KEY (FROM_ABIE_ID) REFERENCES ABIE (ABIE_ID);
ALTER TABLE ASBIE ADD CONSTRAINT ASBIE_FK2 FOREIGN KEY (TO_ASBIEP_ID) REFERENCES ASBIEP (ASBIEP_ID);
ALTER TABLE ASBIE ADD CONSTRAINT ASBIE_FK3 FOREIGN KEY (BASED_ASCC_ID) REFERENCES ASCC (ASCC_ID);
ALTER TABLE ASBIE ADD CONSTRAINT ASBIE_FK4 FOREIGN KEY (CREATED_BY) REFERENCES APP_USER (APP_USER_ID);
ALTER TABLE ASBIE ADD CONSTRAINT ASBIE_FK5 FOREIGN KEY (LAST_UPDATED_BY) REFERENCES APP_USER (APP_USER_ID);
ALTER TABLE ASBIE ADD CONSTRAINT ASBIE_FK6 FOREIGN KEY (OWNER_TOP_LEVEL_ABIE_ID) REFERENCES TOP_LEVEL_ABIE (TOP_LEVEL_ABIE_ID);

ALTER TABLE ASBIEP ADD CONSTRAINT ASBIEP_FK1 FOREIGN KEY (BASED_ASCCP_ID) REFERENCES ASCCP (ASCCP_ID);
ALTER TABLE ASBIEP ADD CONSTRAINT ASBIEP_FK2 FOREIGN KEY (ROLE_OF_ABIE_ID) REFERENCES ABIE (ABIE_ID);
ALTER TABLE ASBIEP ADD CONSTRAINT ASBIEP_FK3 FOREIGN KEY (CREATED_BY) REFERENCES APP_USER (APP_USER_ID);
ALTER TABLE ASBIEP ADD CONSTRAINT ASBIEP_FK4 FOREIGN KEY (LAST_UPDATED_BY) REFERENCES APP_USER (APP_USER_ID);
ALTER TABLE ASBIEP ADD CONSTRAINT ASBIEP_FK5 FOREIGN KEY (OWNER_TOP_LEVEL_ABIE_ID) REFERENCES APP_USER (APP_USER_ID);

ALTER TABLE ASCC ADD CONSTRAINT ASCC_FK1 FOREIGN KEY (FROM_ACC_ID) REFERENCES ACC (ACC_ID);
ALTER TABLE ASCC ADD CONSTRAINT ASCC_FK2 FOREIGN KEY (TO_ASCCP_ID) REFERENCES ASCCP (ASCCP_ID);
ALTER TABLE ASCC ADD CONSTRAINT ASCC_FK3 FOREIGN KEY (CREATED_BY) REFERENCES APP_USER (APP_USER_ID);
ALTER TABLE ASCC ADD CONSTRAINT ASCC_FK4 FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER (APP_USER_ID);
ALTER TABLE ASCC ADD CONSTRAINT ASCC_FK5 FOREIGN KEY (LAST_UPDATED_BY) REFERENCES APP_USER (APP_USER_ID);
ALTER TABLE ASCC ADD CONSTRAINT ASCC_FK6 FOREIGN KEY (RELEASE_ID) REFERENCES RELEASE (RELEASE_ID);
ALTER TABLE ASCC ADD CONSTRAINT ASCC_FK7 FOREIGN KEY (CURRENT_ASCC_ID) REFERENCES TOP_LEVEL_ABIE (TOP_LEVEL_ABIE_ID);

ALTER TABLE ASCCP ADD CONSTRAINT ASCCP_FK1 FOREIGN KEY (ROLE_OF_ACC_ID) REFERENCES ACC (ACC_ID);
ALTER TABLE ASCCP ADD CONSTRAINT ASCCP_FK2 FOREIGN KEY (CREATED_BY) REFERENCES APP_USER (APP_USER_ID);
ALTER TABLE ASCCP ADD CONSTRAINT ASCCP_FK3 FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER (APP_USER_ID);
ALTER TABLE ASCCP ADD CONSTRAINT ASCCP_FK4 FOREIGN KEY (LAST_UPDATED_BY) REFERENCES APP_USER (APP_USER_ID);
ALTER TABLE ASCCP ADD CONSTRAINT ASCCP_FK5 FOREIGN KEY (MODULE_ID) REFERENCES MODULE (MODULE_ID);
ALTER TABLE ASCCP ADD CONSTRAINT ASCCP_FK6 FOREIGN KEY (NAMESPACE_ID) REFERENCES NAMESPACE (NAMESPACE_ID);
ALTER TABLE ASCCP ADD CONSTRAINT ASCCP_FK7 FOREIGN KEY (RELEASE_ID) REFERENCES RELEASE (RELEASE_ID);
ALTER TABLE ASCCP ADD CONSTRAINT ASCCP_FK8 FOREIGN KEY (CURRENT_ASCCP_ID) REFERENCES ASCCP (ASCCP_ID);

ALTER TABLE BBIE ADD CONSTRAINT BBIE_FK1 FOREIGN KEY (BASED_BCC_ID) REFERENCES BCC (BCC_ID);
ALTER TABLE BBIE ADD CONSTRAINT BBIE_FK2 FOREIGN KEY (FROM_ABIE_ID) REFERENCES ABIE (ABIE_ID);
ALTER TABLE BBIE ADD CONSTRAINT BBIE_FK3 FOREIGN KEY (TO_BBIEP_ID) REFERENCES BBIEP (BBIEP_ID);
ALTER TABLE BBIE ADD CONSTRAINT BBIE_FK4 FOREIGN KEY (BDT_PRI_RESTRI_ID) REFERENCES BDT_PRI_RESTRI (BDT_PRI_RESTRI_ID);
ALTER TABLE BBIE ADD CONSTRAINT BBIE_FK5 FOREIGN KEY (CODE_LIST_ID) REFERENCES CODE_LIST (CODE_LIST_ID);
ALTER TABLE BBIE ADD CONSTRAINT BBIE_FK6 FOREIGN KEY (AGENCY_ID_LIST_ID) REFERENCES AGENCY_ID_LIST (AGENCY_ID_LIST_ID);
ALTER TABLE BBIE ADD CONSTRAINT BBIE_FK7 FOREIGN KEY (CREATED_BY) REFERENCES APP_USER (APP_USER_ID);
ALTER TABLE BBIE ADD CONSTRAINT BBIE_FK8 FOREIGN KEY (LAST_UPDATED_BY) REFERENCES APP_USER (APP_USER_ID);
ALTER TABLE BBIE ADD CONSTRAINT BBIE_FK9 FOREIGN KEY (OWNER_TOP_LEVEL_ABIE_ID) REFERENCES TOP_LEVEL_ABIE (TOP_LEVEL_ABIE_ID);

ALTER TABLE BBIEP ADD CONSTRAINT BBIEP_FK1 FOREIGN KEY (BASED_BCCP_ID) REFERENCES BCCP (BCCP_ID);
ALTER TABLE BBIEP ADD CONSTRAINT BBIEP_FK2 FOREIGN KEY (CREATED_BY) REFERENCES APP_USER (APP_USER_ID);
ALTER TABLE BBIEP ADD CONSTRAINT BBIEP_FK3 FOREIGN KEY (LAST_UPDATED_BY) REFERENCES APP_USER (APP_USER_ID);
ALTER TABLE BBIEP ADD CONSTRAINT BBIEP_FK4 FOREIGN KEY (OWNER_TOP_LEVEL_ABIE_ID) REFERENCES TOP_LEVEL_ABIE (TOP_LEVEL_ABIE_ID);

ALTER TABLE BBIE_SC ADD CONSTRAINT BBIE_SC_FK1 FOREIGN KEY (BBIE_ID) REFERENCES BBIE (BBIE_ID);
ALTER TABLE BBIE_SC ADD CONSTRAINT BBIE_SC_FK2 FOREIGN KEY (DT_SC_ID) REFERENCES DT_SC (DT_SC_ID);
ALTER TABLE BBIE_SC ADD CONSTRAINT BBIE_SC_FK3 FOREIGN KEY (DT_SC_PRI_RESTRI_ID) REFERENCES BDT_SC_PRI_RESTRI (BDT_SC_PRI_RESTRI_ID);
ALTER TABLE BBIE_SC ADD CONSTRAINT BBIE_SC_FK4 FOREIGN KEY (CODE_LIST_ID) REFERENCES CODE_LIST (CODE_LIST_ID);
ALTER TABLE BBIE_SC ADD CONSTRAINT BBIE_SC_FK5 FOREIGN KEY (AGENCY_ID_LIST_ID) REFERENCES AGENCY_ID_LIST (AGENCY_ID_LIST_ID);
ALTER TABLE BBIE_SC ADD CONSTRAINT BBIE_SC_FK6 FOREIGN KEY (OWNER_TOP_LEVEL_ABIE_ID) REFERENCES TOP_LEVEL_ABIE (TOP_LEVEL_ABIE_ID);

ALTER TABLE BCC ADD CONSTRAINT BCC_FK1 FOREIGN KEY (FROM_ACC_ID) REFERENCES ACC (ACC_ID);
ALTER TABLE BCC ADD CONSTRAINT BCC_FK2 FOREIGN KEY (TO_BCCP_ID) REFERENCES BCCP (BCCP_ID);
ALTER TABLE BCC ADD CONSTRAINT BCC_FK3 FOREIGN KEY (CREATED_BY) REFERENCES APP_USER (APP_USER_ID);
ALTER TABLE BCC ADD CONSTRAINT BCC_FK4 FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER (APP_USER_ID);
ALTER TABLE BCC ADD CONSTRAINT BCC_FK5 FOREIGN KEY (LAST_UPDATED_BY) REFERENCES APP_USER (APP_USER_ID);
ALTER TABLE BCC ADD CONSTRAINT BCC_FK6 FOREIGN KEY (RELEASE_ID) REFERENCES RELEASE (RELEASE_ID);
ALTER TABLE BCC ADD CONSTRAINT BCC_FK7 FOREIGN KEY (CURRENT_BCC_ID) REFERENCES BCC (BCC_ID);

ALTER TABLE BCCP ADD CONSTRAINT BCCP_FK1 FOREIGN KEY (BDT_ID) REFERENCES DT (DT_ID);
ALTER TABLE BCCP ADD CONSTRAINT BCCP_FK2 FOREIGN KEY (MODULE_ID) REFERENCES MODULE (MODULE_ID);
ALTER TABLE BCCP ADD CONSTRAINT BCCP_FK3 FOREIGN KEY (NAMESPACE_ID) REFERENCES NAMESPACE (NAMESPACE_ID);
ALTER TABLE BCCP ADD CONSTRAINT BCCP_FK4 FOREIGN KEY (CREATED_BY) REFERENCES APP_USER (APP_USER_ID);
ALTER TABLE BCCP ADD CONSTRAINT BCCP_FK5 FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER (APP_USER_ID);
ALTER TABLE BCCP ADD CONSTRAINT BCCP_FK6 FOREIGN KEY (LAST_UPDATED_BY) REFERENCES APP_USER (APP_USER_ID);
ALTER TABLE BCCP ADD CONSTRAINT BCCP_FK7 FOREIGN KEY (RELEASE_ID) REFERENCES RELEASE (RELEASE_ID);
ALTER TABLE BCCP ADD CONSTRAINT BCCP_FK8 FOREIGN KEY (CURRENT_BCCP_ID) REFERENCES BCCP (BCCP_ID);

ALTER TABLE BDT_PRI_RESTRI ADD CONSTRAINT BDT_PRI_RESTRI_FK1 FOREIGN KEY (BDT_ID) REFERENCES DT (DT_ID);
ALTER TABLE BDT_PRI_RESTRI ADD CONSTRAINT BDT_PRI_RESTRI_FK2 FOREIGN KEY (CDT_AWD_PRI_XPS_TYPE_MAP_ID) REFERENCES CDT_AWD_PRI_XPS_TYPE_MAP (CDT_AWD_PRI_XPS_TYPE_MAP_ID);
ALTER TABLE BDT_PRI_RESTRI ADD CONSTRAINT BDT_PRI_RESTRI_FK3 FOREIGN KEY (CODE_LIST_ID) REFERENCES CODE_LIST (CODE_LIST_ID);
ALTER TABLE BDT_PRI_RESTRI ADD CONSTRAINT BDT_PRI_RESTRI_FK4 FOREIGN KEY (AGENCY_ID_LIST_ID) REFERENCES AGENCY_ID_LIST (AGENCY_ID_LIST_ID);

ALTER TABLE BDT_SC_PRI_RESTRI ADD CONSTRAINT BDT_SC_PRI_RESTRI_FK1 FOREIGN KEY (BDT_SC_ID) REFERENCES DT_SC (DT_SC_ID);
ALTER TABLE BDT_SC_PRI_RESTRI ADD CONSTRAINT BDT_SC_PRI_RESTRI_FK2 FOREIGN KEY (CDT_SC_AWD_PRI_XPS_TYPE_MAP_ID) REFERENCES CDT_SC_AWD_PRI_XPS_TYPE_MAP (CDT_SC_AWD_PRI_XPS_TYPE_MAP_ID);
ALTER TABLE BDT_SC_PRI_RESTRI ADD CONSTRAINT BDT_SC_PRI_RESTRI_FK3 FOREIGN KEY (CODE_LIST_ID) REFERENCES CODE_LIST (CODE_LIST_ID);
ALTER TABLE BDT_SC_PRI_RESTRI ADD CONSTRAINT BDT_SC_PRI_RESTRI_FK4 FOREIGN KEY (AGENCY_ID_LIST_ID) REFERENCES AGENCY_ID_LIST (AGENCY_ID_LIST_ID);

ALTER TABLE BIE_USER_EXT_REVISION ADD CONSTRAINT BIE_USER_EXT_REVISION_FK1 FOREIGN KEY (TOP_LEVEL_ABIE_ID) REFERENCES TOP_LEVEL_ABIE (TOP_LEVEL_ABIE_ID);
ALTER TABLE BIE_USER_EXT_REVISION ADD CONSTRAINT BIE_USER_EXT_REVISION_FK2 FOREIGN KEY (EXT_ABIE_ID) REFERENCES ABIE (ABIE_ID);
ALTER TABLE BIE_USER_EXT_REVISION ADD CONSTRAINT BIE_USER_EXT_REVISION_FK3 FOREIGN KEY (EXT_ACC_ID) REFERENCES ACC (ACC_ID);
ALTER TABLE BIE_USER_EXT_REVISION ADD CONSTRAINT BIE_USER_EXT_REVISION_FK4 FOREIGN KEY (USER_EXT_ACC_ID) REFERENCES ACC (ACC_ID);

ALTER TABLE BIZ_CTX ADD CONSTRAINT BIZ_CTX_FK1 FOREIGN KEY (CREATED_BY) REFERENCES APP_USER (APP_USER_ID);
ALTER TABLE BIZ_CTX ADD CONSTRAINT BIZ_CTX_FK2 FOREIGN KEY (LAST_UPDATED_BY) REFERENCES APP_USER (APP_USER_ID);

ALTER TABLE BIZ_CTX_VALUE ADD CONSTRAINT BIZ_CTX_VALUE_FK1 FOREIGN KEY (BIZ_CTX_ID) REFERENCES BIZ_CTX (BIZ_CTX_ID);
ALTER TABLE BIZ_CTX_VALUE ADD CONSTRAINT BIZ_CTX_VALUE_FK2 FOREIGN KEY (CTX_SCHEME_VALUE_ID) REFERENCES CTX_SCHEME_VALUE (CTX_SCHEME_VALUE_ID);

ALTER TABLE BLOB_CONTENT ADD CONSTRAINT BLOB_CONTENT_FK1 FOREIGN KEY (RELEASE_ID) REFERENCES RELEASE (RELEASE_ID);
ALTER TABLE BLOB_CONTENT ADD CONSTRAINT BLOB_CONTENT_FK2 FOREIGN KEY (MODULE_ID) REFERENCES MODULE (MODULE_ID);

ALTER TABLE CDT_AWD_PRI_XPS_TYPE_MAP ADD CONSTRAINT CDT_AWD_PRI_XPS_TYPE_MAP_FK1 FOREIGN KEY (CDT_AWD_PRI_ID) REFERENCES CDT_AWD_PRI (CDT_AWD_PRI_ID);
ALTER TABLE CDT_AWD_PRI_XPS_TYPE_MAP ADD CONSTRAINT CDT_AWD_PRI_XPS_TYPE_MAP_FK2 FOREIGN KEY (XBT_ID) REFERENCES XBT (XBT_ID);

ALTER TABLE CDT_SC_AWD_PRI ADD CONSTRAINT CDT_SC_AWD_PRI_FK1 FOREIGN KEY (CDT_SC_ID) REFERENCES DT_SC (DT_SC_ID);
ALTER TABLE CDT_SC_AWD_PRI ADD CONSTRAINT CDT_SC_AWD_PRI_FK2 FOREIGN KEY (CDT_PRI_ID) REFERENCES CDT_PRI (CDT_PRI_ID);

ALTER TABLE CDT_SC_AWD_PRI_XPS_TYPE_MAP ADD CONSTRAINT CDT_SC_AWD_PRI_XPS_TYPE_MAP_FK1 FOREIGN KEY (CDT_SC_AWD_PRI_ID) REFERENCES CDT_SC_AWD_PRI (CDT_SC_AWD_PRI_ID);
ALTER TABLE CDT_SC_AWD_PRI_XPS_TYPE_MAP ADD CONSTRAINT CDT_SC_AWD_PRI_XPS_TYPE_MAP_FK2 FOREIGN KEY (XBT_ID) REFERENCES XBT (XBT_ID);

ALTER TABLE CODE_LIST ADD CONSTRAINT CODE_LIST_FK1 FOREIGN KEY (AGENCY_ID) REFERENCES AGENCY_ID_LIST_VALUE (AGENCY_ID_LIST_VALUE_ID);
ALTER TABLE CODE_LIST ADD CONSTRAINT CODE_LIST_FK2 FOREIGN KEY (BASED_CODE_LIST_ID) REFERENCES CODE_LIST (CODE_LIST_ID);
ALTER TABLE CODE_LIST ADD CONSTRAINT CODE_LIST_FK3 FOREIGN KEY (MODULE_ID) REFERENCES MODULE (MODULE_ID);
ALTER TABLE CODE_LIST ADD CONSTRAINT CODE_LIST_FK4 FOREIGN KEY (CREATED_BY) REFERENCES APP_USER (APP_USER_ID);
ALTER TABLE CODE_LIST ADD CONSTRAINT CODE_LIST_FK5 FOREIGN KEY (LAST_UPDATED_BY) REFERENCES APP_USER (APP_USER_ID);

ALTER TABLE CODE_LIST_VALUE ADD CONSTRAINT CODE_LIST_VALUE_FK1 FOREIGN KEY (CODE_LIST_ID) REFERENCES CODE_LIST (CODE_LIST_ID);

ALTER TABLE CTX_SCHEME ADD CONSTRAINT CTX_SCHEME_FK1 FOREIGN KEY (CTX_CATEGORY_ID) REFERENCES CTX_CATEGORY (CTX_CATEGORY_ID);
ALTER TABLE CTX_SCHEME ADD CONSTRAINT CTX_SCHEME_FK2 FOREIGN KEY (CREATED_BY) REFERENCES APP_USER (APP_USER_ID);
ALTER TABLE CTX_SCHEME ADD CONSTRAINT CTX_SCHEME_FK3 FOREIGN KEY (LAST_UPDATED_BY) REFERENCES APP_USER (APP_USER_ID);

ALTER TABLE CTX_SCHEME_VALUE ADD CONSTRAINT CTX_SCHEME_VALUE_FK1 FOREIGN KEY (OWNER_CTX_SCHEME_ID) REFERENCES CTX_SCHEME (CTX_SCHEME_ID);

ALTER TABLE DT ADD CONSTRAINT DT_FK1 FOREIGN KEY (PREVIOUS_VERSION_DT_ID) REFERENCES DT (DT_ID);
ALTER TABLE DT ADD CONSTRAINT DT_FK2 FOREIGN KEY (BASED_DT_ID) REFERENCES DT (DT_ID);
ALTER TABLE DT ADD CONSTRAINT DT_FK3 FOREIGN KEY (MODULE_ID) REFERENCES MODULE (MODULE_ID);
ALTER TABLE DT ADD CONSTRAINT DT_FK4 FOREIGN KEY (CREATED_BY) REFERENCES APP_USER (APP_USER_ID);
ALTER TABLE DT ADD CONSTRAINT DT_FK5 FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER (APP_USER_ID);
ALTER TABLE DT ADD CONSTRAINT DT_FK6 FOREIGN KEY (LAST_UPDATED_BY) REFERENCES APP_USER (APP_USER_ID);
ALTER TABLE DT ADD CONSTRAINT DT_FK7 FOREIGN KEY (RELEASE_ID) REFERENCES RELEASE (RELEASE_ID);
ALTER TABLE DT ADD CONSTRAINT DT_FK8 FOREIGN KEY (CURRENT_BDT_ID) REFERENCES DT (DT_ID);

ALTER TABLE DT_SC ADD CONSTRAINT DT_SC_FK1 FOREIGN KEY (OWNER_DT_ID) REFERENCES DT (DT_ID);
ALTER TABLE DT_SC ADD CONSTRAINT DT_SC_FK2 FOREIGN KEY (BASED_DT_SC_ID) REFERENCES DT_SC (DT_SC_ID);

ALTER TABLE MODULE ADD CONSTRAINT MODULE_FK1 FOREIGN KEY (RELEASE_ID) REFERENCES RELEASE (RELEASE_ID);
ALTER TABLE MODULE ADD CONSTRAINT MODULE_FK2 FOREIGN KEY (NAMESPACE_ID) REFERENCES NAMESPACE (NAMESPACE_ID);

ALTER TABLE MODULE_DEP ADD CONSTRAINT MODULE_DEP_FK1 FOREIGN KEY (DEPENDING_MODULE_ID) REFERENCES MODULE (MODULE_ID);
ALTER TABLE MODULE_DEP ADD CONSTRAINT MODULE_DEP_FK2 FOREIGN KEY (DEPENDED_MODULE_ID) REFERENCES MODULE (MODULE_ID);

ALTER TABLE NAMESPACE ADD CONSTRAINT NAMESPACE_FK1 FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER (APP_USER_ID);
ALTER TABLE NAMESPACE ADD CONSTRAINT NAMESPACE_FK2 FOREIGN KEY (CREATED_BY) REFERENCES APP_USER (APP_USER_ID);
ALTER TABLE NAMESPACE ADD CONSTRAINT NAMESPACE_FK3 FOREIGN KEY (LAST_UPDATED_BY) REFERENCES APP_USER (APP_USER_ID);

ALTER TABLE RELEASE ADD CONSTRAINT RELEASE_FK1 FOREIGN KEY (NAMESPACE_ID) REFERENCES NAMESPACE (NAMESPACE_ID);

ALTER TABLE TOP_LEVEL_ABIE ADD CONSTRAINT TOP_LEVEL_ABIE_FK1 FOREIGN KEY (ABIE_ID) REFERENCES APP_USER (APP_USER_ID);
ALTER TABLE TOP_LEVEL_ABIE ADD CONSTRAINT TOP_LEVEL_ABIE_FK2 FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER (APP_USER_ID);

ALTER TABLE XBT ADD CONSTRAINT XBT_FK1 FOREIGN KEY (SUBTYPE_OF_XBT_ID) REFERENCES XBT (XBT_ID);