--------------------------------------------------------
-- DROP ALL SEQUENCES
--------------------------------------------------------
DROP SEQUENCE BOD_ID_SEQ;
DROP SEQUENCE ABIE_ID_SEQ;
DROP SEQUENCE ACC_ID_SEQ;
DROP SEQUENCE AGENCY_ID_LIST_ID_SEQ;
DROP SEQUENCE AGENCY_ID_LIST_VALUE_ID_SEQ;
DROP SEQUENCE APP_USER_ID_SEQ;
DROP SEQUENCE ASBIE_ID_SEQ;
DROP SEQUENCE ASBIEP_ID_SEQ;
DROP SEQUENCE ASCC_ID_SEQ;
DROP SEQUENCE ASCCP_ID_SEQ;
DROP SEQUENCE BBIE_ID_SEQ;
DROP SEQUENCE BBIE_SC_ID_SEQ;
DROP SEQUENCE BBIEP_ID_SEQ;
DROP SEQUENCE BCC_ID_SEQ;
DROP SEQUENCE BCCP_ID_SEQ;
DROP SEQUENCE BDT_PRI_RESTRI_ID_SEQ;
DROP SEQUENCE BDT_SC_PRI_RESTRI_ID_SEQ;
DROP SEQUENCE BIE_USER_EXT_REVISION_ID_SEQ;
DROP SEQUENCE BIZ_CTX_ID_SEQ;
DROP SEQUENCE BIZ_CTX_VALUE_ID_SEQ;
DROP SEQUENCE BLOB_CONTENT_ID_SEQ;
DROP SEQUENCE CDT_AWD_PRI_ID_SEQ;
DROP SEQUENCE CDT_AWD_PRI_XPS_TYP_MAP_ID_SEQ;
DROP SEQUENCE CDT_PRI_ID_SEQ;
DROP SEQUENCE CDT_SC_AW_PR_XPS_TYP_MP_ID_SEQ;
DROP SEQUENCE CDT_SC_AWD_PRI_ID_SEQ;
DROP SEQUENCE CLIENT_ID_SEQ;
DROP SEQUENCE CODE_LIST_ID_SEQ;
DROP SEQUENCE CODE_LIST_VALUE_ID_SEQ;
DROP SEQUENCE CTX_CATEGORY_ID_SEQ;
DROP SEQUENCE CTX_SCHEME_ID_SEQ;
DROP SEQUENCE CTX_SCHEME_VALUE_ID_SEQ;
DROP SEQUENCE DT_ID_SEQ;
DROP SEQUENCE DT_SC_ID_SEQ;
DROP SEQUENCE MODULE_DEP_ID_SEQ;
DROP SEQUENCE MODULE_ID_SEQ;
DROP SEQUENCE NAMESPACE_ID_SEQ;
DROP SEQUENCE RELEASE_ID_SEQ;
DROP SEQUENCE XBT_ID_SEQ;

-- -----------------------------------------------------
-- DROP ALL TABLES
-- -----------------------------------------------------
DROP TABLE BLOB_CONTENT;
DROP TABLE BIE_USER_EXT_REVISION;
DROP TABLE BBIE_SC;
DROP TABLE BIZ_CTX_VALUE;
DROP TABLE CTX_SCHEME_VALUE;
DROP TABLE CLASSIFICATION_CTX_SCHEME;
DROP TABLE CTX_CATEGORY;
DROP TABLE CODE_LIST_VALUE;
DROP TABLE ASBIE;
DROP TABLE ASCC;
DROP TABLE ASBIEP;
DROP TABLE ASCCP;
DROP TABLE BDT_SC_PRI_RESTRI;
DROP TABLE CDT_SC_AWD_PRI_XPS_TYPE_MAP;
DROP TABLE BBIE;
DROP TABLE BDT_PRI_RESTRI;
DROP TABLE CODE_LIST;
ALTER TABLE AGENCY_ID_LIST
  DROP CONSTRAINT AGENCY_ID_LIST_AGENCY_ID_FK;
DROP TABLE AGENCY_ID_LIST_VALUE;
DROP TABLE AGENCY_ID_LIST;
DROP TABLE BBIEP;
ALTER TABLE BOD
  DROP CONSTRAINT BOD_TOP_LEVEL_ABIE_ID_FK;
DROP TABLE ABIE;
DROP TABLE BOD;
DROP TABLE CLIENT;
DROP TABLE BIZ_CTX;
DROP TABLE BCC;
DROP TABLE ACC;
DROP TABLE BCCP;
DROP TABLE CDT_SC_AWD_PRI;
DROP TABLE DT_SC;
DROP TABLE CDT_AWD_PRI_XPS_TYPE_MAP;
DROP TABLE CDT_AWD_PRI;
DROP TABLE CDT_PRI;
DROP TABLE XBT;
DROP TABLE DT;
DROP TABLE MODULE_DEP;
DROP TABLE MODULE;
DROP TABLE RELEASE;
DROP TABLE NAMESPACE;
DROP TABLE APP_USER;

-- -----------------------------------------------------
-- TABLE APP_USER
-- -----------------------------------------------------
CREATE TABLE APP_USER (
  APP_USER_ID               NUMBER(10)    NOT NULL,
  LOGIN_ID                  VARCHAR2(45)  NOT NULL,
  PASSWORD                  VARCHAR2(100) NOT NULL,
  NAME                      VARCHAR2(100) NULL,
  ORGANIZATION              VARCHAR2(100) NULL,
  OAGIS_DEVELOPER_INDICATOR NUMBER(3)     NOT NULL,

  CONSTRAINT APP_USER_PK PRIMARY KEY (APP_USER_ID)
);

CREATE UNIQUE INDEX APP_USER_UK1 ON APP_USER (LOGIN_ID ASC);

CREATE SEQUENCE APP_USER_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 NOCYCLE;

-- -----------------------------------------------------
-- TABLE NAMESPACE
-- -----------------------------------------------------
CREATE TABLE NAMESPACE (
  NAMESPACE_ID          NUMBER(10)    NOT NULL,
  URI                   VARCHAR2(100) NOT NULL,
  PREFIX                VARCHAR2(45)  NULL,
  DESCRIPTION           VARCHAR2(200) NULL,
  IS_STD_NMSP           NUMBER(3)     NOT NULL,
  OWNER_USER_ID         NUMBER(10)    NOT NULL,
  CREATED_BY            NUMBER(10)    NOT NULL,
  LAST_UPDATED_BY       NUMBER(10)    NOT NULL,
  CREATION_TIMESTAMP    TIMESTAMP     NOT NULL,
  LAST_UPDATE_TIMESTAMP TIMESTAMP     NOT NULL,

  CONSTRAINT NAMESPACE_PK PRIMARY KEY (NAMESPACE_ID),
  CONSTRAINT NAMESPACE_OWNER_USER_ID_FK FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER (APP_USER_ID),
  CONSTRAINT NAMESPACE_CREATED_BY_FK FOREIGN KEY (CREATED_BY) REFERENCES APP_USER (APP_USER_ID),
  CONSTRAINT NAMESPACE_LAST_UPDATED_BY_FK FOREIGN KEY (LAST_UPDATED_BY) REFERENCES APP_USER (APP_USER_ID)
);

CREATE SEQUENCE NAMESPACE_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 NOCYCLE;

-- -----------------------------------------------------
-- TABLE RELEASE
-- -----------------------------------------------------
CREATE TABLE RELEASE (
  RELEASE_ID   NUMBER(10)   NOT NULL,
  RELEASE_NUM  VARCHAR2(45) NOT NULL,
  RELEASE_NOTE CLOB         NULL,
  NAMESPACE_ID NUMBER(10)   NOT NULL,

  CONSTRAINT RELEASE_PK PRIMARY KEY (RELEASE_ID),
  CONSTRAINT RELEASE_NAMESPACE_ID_FK FOREIGN KEY (NAMESPACE_ID) REFERENCES NAMESPACE (NAMESPACE_ID)
);

CREATE SEQUENCE RELEASE_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 NOCYCLE;

-- -----------------------------------------------------
-- TABLE MODULE
-- -----------------------------------------------------
CREATE TABLE MODULE (
  MODULE_ID    NUMBER(10)    NOT NULL,
  MODULE       VARCHAR2(100) NOT NULL,
  RELEASE_ID   NUMBER(10)    NOT NULL,
  NAMESPACE_ID NUMBER(10)    NOT NULL,

  CONSTRAINT MODULE_PK PRIMARY KEY (MODULE_ID),
  CONSTRAINT MODULE_RELEASE_ID_FK FOREIGN KEY (RELEASE_ID) REFERENCES RELEASE (RELEASE_ID),
  CONSTRAINT MODULE_NAMESPACE_ID_FK FOREIGN KEY (NAMESPACE_ID) REFERENCES NAMESPACE (NAMESPACE_ID)
);

CREATE SEQUENCE MODULE_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 NOCYCLE;

-- -----------------------------------------------------
-- TABLE MODULE_DEP
-- -----------------------------------------------------
CREATE TABLE MODULE_DEP (
  MODULE_DEP_ID       NUMBER(10) NOT NULL,
  DEPENDENCY_TYPE     NUMBER(10) NOT NULL,
  DEPENDING_MODULE_ID NUMBER(10) NOT NULL,
  DEPENDED_MODULE_ID  NUMBER(10) NOT NULL,

  CONSTRAINT MODULE_DEP_PK PRIMARY KEY (MODULE_DEP_ID),
  CONSTRAINT MODULE_DEPENDING_MODULE_ID_FK FOREIGN KEY (DEPENDING_MODULE_ID) REFERENCES MODULE (MODULE_ID),
  CONSTRAINT MODULE_DEPENDED_MODULE_ID_FK FOREIGN KEY (DEPENDED_MODULE_ID) REFERENCES MODULE (MODULE_ID)
);

CREATE SEQUENCE MODULE_DEP_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 NOCYCLE;

-- -----------------------------------------------------
-- TABLE DT
-- -----------------------------------------------------
CREATE TABLE DT (
  DT_ID                        NUMBER(10)    NOT NULL,
  GUID                         VARCHAR2(41)  NOT NULL,
  TYPE                         NUMBER(10)    NOT NULL,
  VERSION_NUM                  VARCHAR2(45)  NOT NULL,
  PREVIOUS_VERSION_DT_ID       NUMBER(10)    NULL,
  DATA_TYPE_TERM               VARCHAR2(45)  NULL,
  QUALIFIER                    VARCHAR2(100) NULL,
  BASED_DT_ID                  NUMBER(10)    NULL,
  DEN                          VARCHAR2(200) NOT NULL,
  CONTENT_COMPONENT_DEN        VARCHAR2(200) NULL,
  DEFINITION                   CLOB          NULL,
  CONTENT_COMPONENT_DEFINITION CLOB          NULL,
  REVISION_DOC                 CLOB          NULL,
  STATE                        NUMBER(10)    NULL,
  MODULE_ID                    NUMBER(10)    NULL,
  CREATED_BY                   NUMBER(10)    NOT NULL,
  OWNER_USER_ID                NUMBER(10)    NOT NULL,
  LAST_UPDATED_BY              NUMBER(10)    NOT NULL,
  CREATION_TIMESTAMP           TIMESTAMP     NOT NULL,
  LAST_UPDATE_TIMESTAMP        TIMESTAMP     NOT NULL,
  REVISION_NUM                 NUMBER(10)    NOT NULL,
  REVISION_TRACKING_NUM        NUMBER(10)    NOT NULL,
  REVISION_ACTION              NUMBER(3)     NULL,
  RELEASE_ID                   NUMBER(10)    NULL,
  CURRENT_BDT_ID               NUMBER(10)    NULL,
  IS_DEPRECATED                NUMBER(3)     NOT NULL,

  CONSTRAINT DT_PK PRIMARY KEY (DT_ID),
  CONSTRAINT DT_PREVIOUS_VERSION_DT_ID_FK FOREIGN KEY (PREVIOUS_VERSION_DT_ID) REFERENCES DT (DT_ID),
  CONSTRAINT DT_BASED_DT_ID_FK FOREIGN KEY (BASED_DT_ID) REFERENCES DT (DT_ID),
  CONSTRAINT DT_MODULE_ID_FK FOREIGN KEY (MODULE_ID) REFERENCES MODULE (MODULE_ID),
  CONSTRAINT DT_CREATED_BY_FK FOREIGN KEY (CREATED_BY) REFERENCES APP_USER (APP_USER_ID),
  CONSTRAINT DT_OWNER_USER_ID_FK FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER (APP_USER_ID),
  CONSTRAINT DT_LAST_UPDATED_BY_FK FOREIGN KEY (LAST_UPDATED_BY) REFERENCES APP_USER (APP_USER_ID),
  CONSTRAINT DT_RELEASE_ID_FK FOREIGN KEY (RELEASE_ID) REFERENCES RELEASE (RELEASE_ID),
  CONSTRAINT DT_CURRENT_BDT_ID_FK FOREIGN KEY (CURRENT_BDT_ID) REFERENCES DT (DT_ID)
);

CREATE UNIQUE INDEX DT_UK1 ON DT (GUID);

CREATE SEQUENCE DT_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 NOCYCLE;

-- -----------------------------------------------------
-- TABLE XBT
-- -----------------------------------------------------
CREATE TABLE XBT (
  XBT_ID            NUMBER(10)   NOT NULL,
  NAME              VARCHAR2(45) NULL,
  BUILTIN_TYPE      VARCHAR2(45) NULL,
  SUBTYPE_OF_XBT_ID NUMBER(10)   NULL,

  CONSTRAINT XBT_PK PRIMARY KEY (XBT_ID),
  CONSTRAINT XBT_SUBTYPE_OF_XBT_ID_FK FOREIGN KEY (SUBTYPE_OF_XBT_ID) REFERENCES XBT (XBT_ID)
);

CREATE UNIQUE INDEX XBT_UK1 ON XBT (NAME ASC);
CREATE UNIQUE INDEX XBT_UK2 ON XBT (BUILTIN_TYPE ASC);

CREATE SEQUENCE XBT_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 NOCYCLE;

-- -----------------------------------------------------
-- TABLE CDT_PRI
-- -----------------------------------------------------
CREATE TABLE CDT_PRI (
  CDT_PRI_ID NUMBER(10)   NOT NULL,
  NAME       VARCHAR2(45) NOT NULL,

  CONSTRAINT CDT_PRI_PK PRIMARY KEY (CDT_PRI_ID)
);

CREATE UNIQUE INDEX CDT_PRI_UK1 ON CDT_PRI (NAME ASC);

CREATE SEQUENCE CDT_PRI_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 NOCYCLE;

-- -----------------------------------------------------
-- TABLE CDT_AWD_PRI
-- -----------------------------------------------------
CREATE TABLE CDT_AWD_PRI (
  CDT_AWD_PRI_ID NUMBER(10) NOT NULL,
  CDT_ID         NUMBER(10) NOT NULL,
  CDT_PRI_ID     NUMBER(10) NOT NULL,
  IS_DEFAULT     NUMBER(3)  NOT NULL,

  CONSTRAINT CDT_AWD_PRI_PK PRIMARY KEY (CDT_AWD_PRI_ID),
  CONSTRAINT CDT_AWD_PRI_CDT_ID_FK FOREIGN KEY (CDT_ID) REFERENCES DT (DT_ID),
  CONSTRAINT CDT_AWD_PRI_CDT_PRI_ID_FK FOREIGN KEY (CDT_PRI_ID) REFERENCES CDT_PRI (CDT_PRI_ID)
);

CREATE SEQUENCE CDT_AWD_PRI_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 NOCYCLE;

-- -----------------------------------------------------
-- TABLE CDT_AWD_PRI_XPS_TYPE_MAP
-- -----------------------------------------------------
CREATE TABLE CDT_AWD_PRI_XPS_TYPE_MAP (
  CDT_AWD_PRI_XPS_TYPE_MAP_ID NUMBER(10) NOT NULL,
  CDT_AWD_PRI_ID              NUMBER(10) NOT NULL,
  XBT_ID                      NUMBER(10) NOT NULL,

  CONSTRAINT CAPXTM_PK PRIMARY KEY (CDT_AWD_PRI_XPS_TYPE_MAP_ID),
  CONSTRAINT CAPXTM_CDT_AWD_PRI_ID_FK FOREIGN KEY (CDT_AWD_PRI_ID) REFERENCES CDT_AWD_PRI (CDT_AWD_PRI_ID),
  CONSTRAINT CAPXTM_XBT_ID_FK FOREIGN KEY (XBT_ID) REFERENCES XBT (XBT_ID)
);

CREATE SEQUENCE CDT_AWD_PRI_XPS_TYP_MAP_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 NOCYCLE;

-- -----------------------------------------------------
-- TABLE DT_SC
-- -----------------------------------------------------
CREATE TABLE DT_SC (
  DT_SC_ID            NUMBER(10)   NOT NULL,
  GUID                VARCHAR2(41) NOT NULL,
  PROPERTY_TERM       VARCHAR2(60) NULL,
  REPRESENTATION_TERM VARCHAR2(20) NULL,
  DEFINITION          CLOB         NULL,
  OWNER_DT_ID         NUMBER(10)   NOT NULL,
  MIN_CARDINALITY     NUMBER(10)   NOT NULL,
  MAX_CARDINALITY     NUMBER(10)   NULL,
  BASED_DT_SC_ID      NUMBER(10)   NULL,

  CONSTRAINT DT_SC_PK PRIMARY KEY (DT_SC_ID),
  CONSTRAINT DT_SC_OWNER_DT_ID_FK FOREIGN KEY (OWNER_DT_ID) REFERENCES DT (DT_ID),
  CONSTRAINT DT_SC_BASED_DT_SC_ID_FK FOREIGN KEY (BASED_DT_SC_ID) REFERENCES DT_SC (DT_SC_ID)
);

CREATE UNIQUE INDEX DT_SC_UK1 ON DT_SC (GUID);

CREATE SEQUENCE DT_SC_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 NOCYCLE;

-- -----------------------------------------------------
-- TABLE CDT_SC_AWD_PRI
-- -----------------------------------------------------
CREATE TABLE CDT_SC_AWD_PRI (
  CDT_SC_AWD_PRI_ID NUMBER(10) NOT NULL,
  CDT_SC_ID         NUMBER(10) NOT NULL,
  CDT_PRI_ID        NUMBER(10) NOT NULL,
  IS_DEFAULT        NUMBER(3)  NOT NULL,

  CONSTRAINT CDT_SC_AWD_PRI_PK PRIMARY KEY (CDT_SC_AWD_PRI_ID),
  CONSTRAINT CDT_SC_ID_FK FOREIGN KEY (CDT_SC_ID) REFERENCES DT_SC (DT_SC_ID),
  CONSTRAINT CDT_PRI_ID_FK FOREIGN KEY (CDT_PRI_ID) REFERENCES CDT_PRI (CDT_PRI_ID)
);

CREATE SEQUENCE CDT_SC_AWD_PRI_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 NOCYCLE;

-- -----------------------------------------------------
-- TABLE BCCP
-- -----------------------------------------------------
CREATE TABLE BCCP (
  BCCP_ID               NUMBER(10)     NOT NULL,
  GUID                  VARCHAR2(41)   NOT NULL,
  PROPERTY_TERM         VARCHAR2(60)   NOT NULL,
  REPRESENTATION_TERM   VARCHAR2(20)   NOT NULL,
  BDT_ID                NUMBER(10)     NOT NULL,
  DEN                   VARCHAR2(200)  NOT NULL,
  DEFINITION            CLOB           NULL,
  MODULE_ID             NUMBER(10)     NULL,
  NAMESPACE_ID          NUMBER(10)     NULL,
  IS_DEPRECATED         NUMBER(3)      NOT NULL,
  CREATED_BY            NUMBER(10)     NOT NULL,
  OWNER_USER_ID         NUMBER(10)     NOT NULL,
  LAST_UPDATED_BY       NUMBER(10)     NOT NULL,
  CREATION_TIMESTAMP    TIMESTAMP      NOT NULL,
  LAST_UPDATE_TIMESTAMP TIMESTAMP      NOT NULL,
  STATE                 NUMBER(10)     NOT NULL,
  REVISION_NUM          NUMBER(10)     NOT NULL,
  REVISION_TRACKING_NUM NUMBER(10)     NOT NULL,
  REVISION_ACTION       NUMBER(10)     NULL,
  RELEASE_ID            NUMBER(10)     NULL,
  CURRENT_BCCP_ID       NUMBER(10)     NULL,
  IS_NILLABLE           NUMBER(3)      NOT NULL,
  DEFAULT_VALUE         VARCHAR2(4000) NULL,

  CONSTRAINT BCCP_PK PRIMARY KEY (BCCP_ID),
  CONSTRAINT BCCP_BDT_ID_FK FOREIGN KEY (BDT_ID) REFERENCES DT (DT_ID),
  CONSTRAINT BCCP_MODULE_ID_FK FOREIGN KEY (MODULE_ID) REFERENCES MODULE (MODULE_ID),
  CONSTRAINT BCCP_NAMESPACE_ID_FK FOREIGN KEY (NAMESPACE_ID) REFERENCES NAMESPACE (NAMESPACE_ID),
  CONSTRAINT BCCP_CREATED_BY_FK FOREIGN KEY (CREATED_BY) REFERENCES APP_USER (APP_USER_ID),
  CONSTRAINT BCCP_OWNER_USER_ID_FK FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER (APP_USER_ID),
  CONSTRAINT BCCP_LAST_UPDATED_BY_FK FOREIGN KEY (LAST_UPDATED_BY) REFERENCES APP_USER (APP_USER_ID),
  CONSTRAINT BCCP_RELEASE_ID_FK FOREIGN KEY (RELEASE_ID) REFERENCES RELEASE (RELEASE_ID),
  CONSTRAINT BCCP_CURRENT_BCCP_ID_FK FOREIGN KEY (CURRENT_BCCP_ID) REFERENCES BCCP (BCCP_ID)
);

CREATE UNIQUE INDEX BCCP_SC_UK1 ON BCCP (GUID);
CREATE UNIQUE INDEX BCCP_SC_UK2 ON BCCP (PROPERTY_TERM, BDT_ID);

CREATE SEQUENCE BCCP_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 NOCYCLE;

-- -----------------------------------------------------
-- TABLE ACC
-- -----------------------------------------------------
CREATE TABLE ACC (
  ACC_ID                 NUMBER(10)    NOT NULL,
  GUID                   VARCHAR2(41)  NOT NULL,
  OBJECT_CLASS_TERM      VARCHAR2(100) NOT NULL,
  DEN                    VARCHAR2(200) NOT NULL,
  DEFINITION             CLOB          NULL,
  BASED_ACC_ID           NUMBER(10)    NULL,
  OBJECT_CLASS_QUALIFIER VARCHAR2(100) NULL,
  OAGIS_COMPONENT_TYPE   NUMBER(10)    NULL,
  MODULE_ID              NUMBER(10)    NULL,
  NAMESPACE_ID           NUMBER(10)    NULL,
  CREATED_BY             NUMBER(10)    NOT NULL,
  OWNER_USER_ID          NUMBER(10)    NOT NULL,
  LAST_UPDATED_BY        NUMBER(10)    NOT NULL,
  CREATION_TIMESTAMP     TIMESTAMP     NOT NULL,
  LAST_UPDATE_TIMESTAMP  TIMESTAMP     NOT NULL,
  STATE                  NUMBER(10)    NOT NULL,
  REVISION_NUM           NUMBER(10)    NOT NULL,
  REVISION_TRACKING_NUM  NUMBER(10)    NOT NULL,
  REVISION_ACTION        NUMBER(3)     NULL,
  RELEASE_ID             NUMBER(10)    NULL,
  CURRENT_ACC_ID         NUMBER(10)    NULL,
  IS_DEPRECATED          NUMBER(3)     NOT NULL,
  IS_ABSTRACT            NUMBER(3)     NOT NULL,

  CONSTRAINT ACC_PK PRIMARY KEY (ACC_ID),
  CONSTRAINT ACC_BASED_ACC_ID_FK FOREIGN KEY (BASED_ACC_ID) REFERENCES ACC (ACC_ID),
  CONSTRAINT ACC_MODULE_ID_FK FOREIGN KEY (MODULE_ID) REFERENCES MODULE (MODULE_ID),
  CONSTRAINT ACC_NAMESPACE_ID_FK FOREIGN KEY (NAMESPACE_ID) REFERENCES NAMESPACE (NAMESPACE_ID),
  CONSTRAINT ACC_CREATED_BY_FK FOREIGN KEY (CREATED_BY) REFERENCES APP_USER (APP_USER_ID),
  CONSTRAINT ACC_OWNER_USER_ID_FK FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER (APP_USER_ID),
  CONSTRAINT ACC_LAST_UPDATED_BY_FK FOREIGN KEY (LAST_UPDATED_BY) REFERENCES APP_USER (APP_USER_ID),
  CONSTRAINT ACC_RELEASE_ID_FK FOREIGN KEY (RELEASE_ID) REFERENCES RELEASE (RELEASE_ID),
  CONSTRAINT ACC_CURRENT_ACC_ID_FK FOREIGN KEY (CURRENT_ACC_ID) REFERENCES ACC (ACC_ID)
);

CREATE UNIQUE INDEX ACC_UK1 ON ACC (GUID);

CREATE SEQUENCE ACC_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 NOCYCLE;

-- -----------------------------------------------------
-- TABLE BCC
-- -----------------------------------------------------
CREATE TABLE BCC (
  BCC_ID                NUMBER(10)     NOT NULL,
  GUID                  VARCHAR2(41)   NULL,
  CARDINALITY_MIN       NUMBER(10)     NOT NULL,
  CARDINALITY_MAX       NUMBER(10)     NULL,
  TO_BCCP_ID            NUMBER(10)     NOT NULL,
  FROM_ACC_ID           NUMBER(10)     NOT NULL,
  SEQ_KEY               NUMBER(10)     NULL,
  ENTITY_TYPE           NUMBER(10)     NULL,
  DEN                   VARCHAR2(200)  NOT NULL,
  DEFINITION            CLOB           NULL,
  CREATED_BY            NUMBER(10)     NOT NULL,
  OWNER_USER_ID         NUMBER(10)     NOT NULL,
  LAST_UPDATED_BY       NUMBER(10)     NOT NULL,
  CREATION_TIMESTAMP    TIMESTAMP      NOT NULL,
  LAST_UPDATE_TIMESTAMP TIMESTAMP      NOT NULL,
  STATE                 NUMBER(10)     NOT NULL,
  REVISION_NUM          NUMBER(10)     NOT NULL,
  REVISION_TRACKING_NUM NUMBER(10)     NOT NULL,
  REVISION_ACTION       NUMBER(3)      NULL,
  RELEASE_ID            NUMBER(10)     NULL,
  CURRENT_BCC_ID        NUMBER(10)     NULL,
  IS_DEPRECATED         NUMBER(3)      NOT NULL,
  IS_NILLABLE           NUMBER(3)      NOT NULL,
  DEFAULT_VALUE         VARCHAR2(4000) NULL,

  CONSTRAINT BCC_PK PRIMARY KEY (BCC_ID),
  CONSTRAINT BCC_TO_BCCP_ID_FK FOREIGN KEY (TO_BCCP_ID) REFERENCES BCCP (BCCP_ID),
  CONSTRAINT BCC_FROM_ACC_ID_FK FOREIGN KEY (FROM_ACC_ID) REFERENCES ACC (ACC_ID),
  CONSTRAINT BCC_CREATED_BY_FK FOREIGN KEY (CREATED_BY) REFERENCES APP_USER (APP_USER_ID),
  CONSTRAINT BCC_OWNER_USER_ID_FK FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER (APP_USER_ID),
  CONSTRAINT BCC_LAST_UPDATED_BY_FK FOREIGN KEY (LAST_UPDATED_BY) REFERENCES APP_USER (APP_USER_ID),
  CONSTRAINT BCC_RELEASE_ID_FK FOREIGN KEY (RELEASE_ID) REFERENCES RELEASE (RELEASE_ID),
  CONSTRAINT BCC_CURRENT_BCC_ID_FK FOREIGN KEY (CURRENT_BCC_ID) REFERENCES BCC (BCC_ID)
);

CREATE UNIQUE INDEX BCC_UK1 ON BCC (GUID, FROM_ACC_ID, TO_BCCP_ID);

CREATE SEQUENCE BCC_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 NOCYCLE;

-- -----------------------------------------------------
-- TABLE BIZ_CTX
-- -----------------------------------------------------
CREATE TABLE BIZ_CTX (
  BIZ_CTX_ID            NUMBER(10)    NOT NULL,
  GUID                  VARCHAR2(41)  NOT NULL,
  NAME                  VARCHAR2(100) NULL,
  CREATED_BY            NUMBER(10)    NOT NULL,
  LAST_UPDATED_BY       NUMBER(10)    NOT NULL,
  CREATION_TIMESTAMP    TIMESTAMP     NOT NULL,
  LAST_UPDATE_TIMESTAMP TIMESTAMP     NOT NULL,

  CONSTRAINT BIZ_CTX_PK PRIMARY KEY (BIZ_CTX_ID),
  CONSTRAINT BIZ_CTX_CREATED_BY_FK FOREIGN KEY (CREATED_BY) REFERENCES APP_USER (APP_USER_ID),
  CONSTRAINT BIZ_CTX_LAST_UPDATED_BY_FK FOREIGN KEY (LAST_UPDATED_BY) REFERENCES APP_USER (APP_USER_ID)
);

CREATE UNIQUE INDEX BIZ_CTX_UK1 ON BIZ_CTX (GUID);

CREATE SEQUENCE BIZ_CTX_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 NOCYCLE;

-- -----------------------------------------------------
-- TABLE CLIENT
-- -----------------------------------------------------
CREATE TABLE CLIENT (
  CLIENT_ID NUMBER(10)    NOT NULL,
  NAME      VARCHAR2(200) NULL,

  CONSTRAINT CLIENT_PK PRIMARY KEY (CLIENT_ID)
);

CREATE SEQUENCE CLIENT_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 NOCYCLE;

-- -----------------------------------------------------
-- TABLE BOD
-- -----------------------------------------------------
CREATE TABLE BOD (
  BOD_ID            NUMBER(10) NOT NULL,
  BIZ_CTX_ID        NUMBER(10) NOT NULL,
  TOP_LEVEL_ABIE_ID NUMBER(10) NULL,
  STATE             NUMBER(10) NULL,

  CONSTRAINT BOD_PK PRIMARY KEY (BOD_ID),
  CONSTRAINT BOD_BIZ_CTX_ID_FK FOREIGN KEY (BIZ_CTX_ID) REFERENCES BIZ_CTX (BIZ_CTX_ID)
);

CREATE SEQUENCE BOD_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 NOCYCLE;

-- -----------------------------------------------------
-- TABLE ABIE
-- -----------------------------------------------------
CREATE TABLE ABIE (
  ABIE_ID               NUMBER(10)    NOT NULL,
  GUID                  VARCHAR2(41)  NOT NULL,
  BASED_ACC_ID          NUMBER(10)    NOT NULL,
  DEFINITION            CLOB          NULL,
  CREATED_BY            NUMBER(10)    NOT NULL,
  LAST_UPDATED_BY       NUMBER(10)    NOT NULL,
  CREATION_TIMESTAMP    TIMESTAMP     NOT NULL,
  LAST_UPDATE_TIMESTAMP TIMESTAMP     NOT NULL,
  CLIENT_ID             NUMBER(10)    NULL,
  VERSION               VARCHAR2(45)  NULL,
  STATUS                VARCHAR2(45)  NULL,
  REMARK                VARCHAR2(225) NULL,
  BIZ_TERM              VARCHAR2(225) NULL,
  BOD_ID                NUMBER(10)    NOT NULL,

  CONSTRAINT ABIE_PK PRIMARY KEY (ABIE_ID),
  CONSTRAINT ABIE_BASED_ACC_ID_FK FOREIGN KEY (BASED_ACC_ID) REFERENCES ACC (ACC_ID),
  CONSTRAINT ABIE_CREATED_BY_FK FOREIGN KEY (CREATED_BY) REFERENCES APP_USER (APP_USER_ID),
  CONSTRAINT ABIE_LAST_UPDATED_BY_FK FOREIGN KEY (LAST_UPDATED_BY) REFERENCES APP_USER (APP_USER_ID),
  CONSTRAINT ABIE_CLIENT_ID_FK FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (CLIENT_ID),
  CONSTRAINT ABIE_BOD_ID_FK FOREIGN KEY (BOD_ID) REFERENCES BOD (BOD_ID)
);

ALTER TABLE BOD
  ADD
  CONSTRAINT BOD_TOP_LEVEL_ABIE_ID_FK FOREIGN KEY (TOP_LEVEL_ABIE_ID) REFERENCES ABIE (ABIE_ID);

CREATE UNIQUE INDEX ABIE_UK1 ON ABIE (GUID);

CREATE SEQUENCE ABIE_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 2000 NOCYCLE;

-- -----------------------------------------------------
-- TABLE BBIEP
-- -----------------------------------------------------
CREATE TABLE BBIEP (
  BBIEP_ID              NUMBER(10)    NOT NULL,
  GUID                  VARCHAR2(41)  NOT NULL,
  BASED_BCCP_ID         NUMBER(10)    NOT NULL,
  DEFINITION            CLOB          NULL,
  REMARK                VARCHAR2(225) NULL,
  BIZ_TERM              VARCHAR2(225) NULL,
  CREATED_BY            NUMBER(10)    NOT NULL,
  LAST_UPDATED_BY       NUMBER(10)    NOT NULL,
  CREATION_TIMESTAMP    TIMESTAMP     NOT NULL,
  LAST_UPDATE_TIMESTAMP TIMESTAMP     NOT NULL,
  BOD_ID                NUMBER(10)    NOT NULL,

  CONSTRAINT BBIEP_PK PRIMARY KEY (BBIEP_ID),
  CONSTRAINT BBIEP_BASED_BCCP_ID_FK FOREIGN KEY (BASED_BCCP_ID) REFERENCES BCCP (BCCP_ID),
  CONSTRAINT BBIEP_CREATED_BY_FK FOREIGN KEY (CREATED_BY) REFERENCES APP_USER (APP_USER_ID),
  CONSTRAINT BBIEP_LAST_UPDATED_BY_FK FOREIGN KEY (LAST_UPDATED_BY) REFERENCES APP_USER (APP_USER_ID),
  CONSTRAINT BBIEP_BOD_ID_FK FOREIGN KEY (BOD_ID) REFERENCES BOD (BOD_ID)
);

CREATE UNIQUE INDEX BBIEP_UK1 ON BBIEP (GUID);

CREATE SEQUENCE BBIEP_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 2000 NOCYCLE;

-- -----------------------------------------------------
-- TABLE AGENCY_ID_LIST
-- -----------------------------------------------------
CREATE TABLE AGENCY_ID_LIST (
  AGENCY_ID_LIST_ID NUMBER(10)    NOT NULL,
  GUID              VARCHAR2(41)  NOT NULL,
  ENUM_TYPE_GUID    VARCHAR2(41)  NOT NULL,
  NAME              VARCHAR2(100) NULL,
  LIST_ID           VARCHAR2(10)  NULL,
  AGENCY_ID         NUMBER(10)    NULL,
  VERSION_ID        VARCHAR2(10)  NULL,
  MODULE_ID         NUMBER(10)    NOT NULL,
  DEFINITION        CLOB          NULL,

  CONSTRAINT AGENCY_ID_LIST_PK PRIMARY KEY (AGENCY_ID_LIST_ID),
  CONSTRAINT AGENCY_ID_LIST_MODULE_ID_FK FOREIGN KEY (MODULE_ID) REFERENCES MODULE (MODULE_ID)
);

CREATE UNIQUE INDEX AGENCY_ID_LIST_UK1 ON AGENCY_ID_LIST (GUID);
CREATE UNIQUE INDEX AGENCY_ID_LIST_UK2 ON AGENCY_ID_LIST (ENUM_TYPE_GUID ASC);

CREATE SEQUENCE AGENCY_ID_LIST_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 NOCYCLE;

-- -----------------------------------------------------
-- TABLE AGENCY_ID_LIST_VALUE
-- -----------------------------------------------------
CREATE TABLE AGENCY_ID_LIST_VALUE (
  AGENCY_ID_LIST_VALUE_ID NUMBER(10)    NOT NULL,
  VALUE                   VARCHAR2(150) NOT NULL,
  NAME                    VARCHAR2(150) NULL,
  DEFINITION              CLOB          NULL,
  OWNER_LIST_ID           NUMBER(10)    NOT NULL,

  CONSTRAINT AILV_PK PRIMARY KEY (AGENCY_ID_LIST_VALUE_ID),
  CONSTRAINT AILV_OWNER_LIST_ID_FK FOREIGN KEY (OWNER_LIST_ID) REFERENCES AGENCY_ID_LIST (AGENCY_ID_LIST_ID)
);

ALTER TABLE AGENCY_ID_LIST
  ADD
  CONSTRAINT AGENCY_ID_LIST_AGENCY_ID_FK FOREIGN KEY (AGENCY_ID) REFERENCES AGENCY_ID_LIST_VALUE (AGENCY_ID_LIST_VALUE_ID);

CREATE SEQUENCE AGENCY_ID_LIST_VALUE_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 NOCYCLE;

-- -----------------------------------------------------
-- TABLE CODE_LIST
-- -----------------------------------------------------
CREATE TABLE CODE_LIST (
  CODE_LIST_ID          NUMBER(10)    NOT NULL,
  GUID                  VARCHAR2(41)  NOT NULL,
  ENUM_TYPE_GUID        VARCHAR2(41)  NULL,
  NAME                  VARCHAR2(100) NULL,
  LIST_ID               VARCHAR2(100) NOT NULL,
  AGENCY_ID             NUMBER(10)    NULL,
  VERSION_ID            VARCHAR2(10)  NOT NULL,
  DEFINITION            CLOB          NULL,
  REMARK                VARCHAR2(225) NULL,
  DEFINITION_SOURCE     VARCHAR2(100) NULL,
  BASED_CODE_LIST_ID    NUMBER(10)    NULL,
  EXTENSIBLE_INDICATOR  NUMBER(3)     NOT NULL,
  MODULE_ID             NUMBER(10)    NULL,
  CREATED_BY            NUMBER(10)    NOT NULL,
  LAST_UPDATED_BY       NUMBER(10)    NOT NULL,
  CREATION_TIMESTAMP    TIMESTAMP     NOT NULL,
  LAST_UPDATE_TIMESTAMP TIMESTAMP     NOT NULL,
  STATE                 VARCHAR2(10)  NOT NULL,

  CONSTRAINT CODE_LIST_PK PRIMARY KEY (CODE_LIST_ID),
  CONSTRAINT CODE_LIST_AGENCY_ID_FK FOREIGN KEY (AGENCY_ID) REFERENCES AGENCY_ID_LIST_VALUE (AGENCY_ID_LIST_VALUE_ID),
  CONSTRAINT CODE_LIST_BASED_CL_ID_FK FOREIGN KEY (BASED_CODE_LIST_ID) REFERENCES CODE_LIST (CODE_LIST_ID),
  CONSTRAINT CODE_LIST_MODULE_ID_FK FOREIGN KEY (MODULE_ID) REFERENCES MODULE (MODULE_ID),
  CONSTRAINT CODE_LIST_CREATED_BY_FK FOREIGN KEY (CREATED_BY) REFERENCES APP_USER (APP_USER_ID),
  CONSTRAINT CODE_LIST_LAST_UPDATED_BY_FK FOREIGN KEY (LAST_UPDATED_BY) REFERENCES APP_USER (APP_USER_ID)
);

CREATE UNIQUE INDEX CODE_LIST_UK1 ON CODE_LIST (GUID);
CREATE UNIQUE INDEX CODE_LIST_UK2 ON CODE_LIST (ENUM_TYPE_GUID ASC);

CREATE SEQUENCE CODE_LIST_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 NOCYCLE;

-- -----------------------------------------------------
-- TABLE BDT_PRI_RESTRI
-- -----------------------------------------------------
CREATE TABLE BDT_PRI_RESTRI (
  BDT_PRI_RESTRI_ID           NUMBER(10) NOT NULL,
  BDT_ID                      NUMBER(10) NOT NULL,
  CDT_AWD_PRI_XPS_TYPE_MAP_ID NUMBER(10) NULL,
  CODE_LIST_ID                NUMBER(10) NULL,
  IS_DEFAULT                  NUMBER(3)  NOT NULL,
  AGENCY_ID_LIST_ID           NUMBER(10) NULL,

  CONSTRAINT BPR_PK PRIMARY KEY (BDT_PRI_RESTRI_ID),
  CONSTRAINT BPR_BDT_ID_FK FOREIGN KEY (BDT_ID) REFERENCES DT (DT_ID),
  CONSTRAINT BPR_CAPXTM_ID_FK FOREIGN KEY (CDT_AWD_PRI_XPS_TYPE_MAP_ID) REFERENCES CDT_AWD_PRI_XPS_TYPE_MAP (CDT_AWD_PRI_XPS_TYPE_MAP_ID),
  CONSTRAINT BPR_CODE_LIST_ID_FK FOREIGN KEY (CODE_LIST_ID) REFERENCES CODE_LIST (CODE_LIST_ID),
  CONSTRAINT BPR_AGENCY_ID_LIST_ID_FK FOREIGN KEY (AGENCY_ID_LIST_ID) REFERENCES AGENCY_ID_LIST (AGENCY_ID_LIST_ID)
);

CREATE SEQUENCE BDT_PRI_RESTRI_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 NOCYCLE;

-- -----------------------------------------------------
-- TABLE BBIE
-- -----------------------------------------------------
CREATE TABLE BBIE (
  BBIE_ID               NUMBER(10)     NOT NULL,
  GUID                  VARCHAR2(41)   NOT NULL,
  BASED_BCC_ID          NUMBER(10)     NOT NULL,
  FROM_ABIE_ID          NUMBER(10)     NOT NULL,
  TO_BBIEP_ID           NUMBER(10)     NOT NULL,
  BDT_PRI_RESTRI_ID     NUMBER(10)     NULL,
  CODE_LIST_ID          NUMBER(10)     NULL,
  CARDINALITY_MIN       NUMBER(10)     NOT NULL,
  CARDINALITY_MAX       NUMBER(10)     NULL,
  DEFAULT_VALUE         VARCHAR2(4000) NULL,
  IS_NILLABLE           NUMBER(3)      NOT NULL,
  FIXED_VALUE           VARCHAR2(4000) NULL,
  IS_NULL               NUMBER(3)      NOT NULL,
  DEFINITION            CLOB           NULL,
  REMARK                VARCHAR2(225)  NULL,
  CREATED_BY            NUMBER(10)     NOT NULL,
  LAST_UPDATED_BY       NUMBER(10)     NOT NULL,
  CREATION_TIMESTAMP    TIMESTAMP      NOT NULL,
  LAST_UPDATE_TIMESTAMP TIMESTAMP      NOT NULL,
  SEQ_KEY               NUMBER(10)     NOT NULL,
  IS_USED               NUMBER(3)      NOT NULL,
  BOD_ID                NUMBER(10)     NOT NULL,

  CONSTRAINT BBIE_PK PRIMARY KEY (BBIE_ID),
  CONSTRAINT BBIE_BASED_BCC_ID_FK FOREIGN KEY (BASED_BCC_ID) REFERENCES BCC (BCC_ID),
  CONSTRAINT BBIE_FROM_ABIE_ID_FK FOREIGN KEY (FROM_ABIE_ID) REFERENCES ABIE (ABIE_ID),
  CONSTRAINT BBIE_TO_BBIEP_ID_FK FOREIGN KEY (TO_BBIEP_ID) REFERENCES BBIEP (BBIEP_ID),
  CONSTRAINT BBIE_BDT_PRI_RESTRI_ID_FK FOREIGN KEY (BDT_PRI_RESTRI_ID) REFERENCES BDT_PRI_RESTRI (BDT_PRI_RESTRI_ID),
  CONSTRAINT BBIE_CODE_LIST_ID_FK FOREIGN KEY (CODE_LIST_ID) REFERENCES CODE_LIST (CODE_LIST_ID),
  CONSTRAINT BBIE_CREATED_BY_FK FOREIGN KEY (CREATED_BY) REFERENCES APP_USER (APP_USER_ID),
  CONSTRAINT BBIE_LAST_UPDATED_BY_FK FOREIGN KEY (LAST_UPDATED_BY) REFERENCES APP_USER (APP_USER_ID),
  CONSTRAINT BBIE_BOD_ID_FK FOREIGN KEY (BOD_ID) REFERENCES BOD (BOD_ID)
);

CREATE UNIQUE INDEX BBIE_UK1 ON BBIE (GUID, FROM_ABIE_ID, TO_BBIEP_ID);

CREATE SEQUENCE BBIE_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 2000 NOCYCLE;

-- -----------------------------------------------------
-- TABLE CDT_SC_AWD_PRI_XPS_TYPE_MAP
-- -----------------------------------------------------
CREATE TABLE CDT_SC_AWD_PRI_XPS_TYPE_MAP (
  CDT_SC_AWD_PRI_XPS_TYPE_MAP_ID NUMBER(10) NOT NULL,
  CDT_SC_AWD_PRI                 NUMBER(10) NOT NULL,
  XBT_ID                         NUMBER(10) NOT NULL,

  CONSTRAINT CSAPXTM_PK PRIMARY KEY (CDT_SC_AWD_PRI_XPS_TYPE_MAP_ID),
  CONSTRAINT CSAPXTM_CSAP_FK FOREIGN KEY (CDT_SC_AWD_PRI) REFERENCES CDT_SC_AWD_PRI (CDT_SC_AWD_PRI_ID),
  CONSTRAINT CSAPXTM_XBT_ID_FK FOREIGN KEY (XBT_ID) REFERENCES XBT (XBT_ID)
);

CREATE SEQUENCE CDT_SC_AW_PR_XPS_TYP_MP_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 NOCYCLE;

-- -----------------------------------------------------
-- TABLE BDT_SC_PRI_RESTRI
-- -----------------------------------------------------
CREATE TABLE BDT_SC_PRI_RESTRI (
  BDT_SC_PRI_RESTRI_ID           NUMBER(10) NOT NULL,
  BDT_SC_ID                      NUMBER(10) NOT NULL,
  CDT_SC_AWD_PRI_XPS_TYPE_MAP_ID NUMBER(10) NULL,
  CODE_LIST_ID                   NUMBER(10) NULL,
  IS_DEFAULT                     NUMBER(3)  NOT NULL,
  AGENCY_ID_LIST_ID              NUMBER(10) NULL,

  CONSTRAINT BSPR_PK PRIMARY KEY (BDT_SC_PRI_RESTRI_ID),
  CONSTRAINT BSPR_BDT_SC_ID_FK FOREIGN KEY (BDT_SC_ID) REFERENCES DT_SC (DT_SC_ID),
  CONSTRAINT BSPR_CSAPXTM_ID_FK FOREIGN KEY (CDT_SC_AWD_PRI_XPS_TYPE_MAP_ID) REFERENCES CDT_SC_AWD_PRI_XPS_TYPE_MAP (CDT_SC_AWD_PRI_XPS_TYPE_MAP_ID),
  CONSTRAINT BSPR_CODE_LIST_ID_FK FOREIGN KEY (CODE_LIST_ID) REFERENCES CODE_LIST (CODE_LIST_ID),
  CONSTRAINT BSPR_AGENCY_ID_LIST_ID_FK FOREIGN KEY (AGENCY_ID_LIST_ID) REFERENCES AGENCY_ID_LIST (AGENCY_ID_LIST_ID)
);

CREATE SEQUENCE BDT_SC_PRI_RESTRI_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 NOCYCLE;

-- -----------------------------------------------------
-- TABLE ASCCP
-- -----------------------------------------------------
CREATE TABLE ASCCP (
  ASCCP_ID              NUMBER(10)    NOT NULL,
  GUID                  VARCHAR2(41)  NOT NULL,
  PROPERTY_TERM         VARCHAR2(60)  NULL,
  DEFINITION            CLOB          NULL,
  ROLE_OF_ACC_ID        NUMBER(10)    NULL,
  DEN                   VARCHAR2(200) NULL,
  CREATED_BY            NUMBER(10)    NOT NULL,
  OWNER_USER_ID         NUMBER(10)    NOT NULL,
  LAST_UPDATED_BY       NUMBER(10)    NOT NULL,
  CREATION_TIMESTAMP    TIMESTAMP     NOT NULL,
  LAST_UPDATE_TIMESTAMP TIMESTAMP     NOT NULL,
  STATE                 NUMBER(10)    NOT NULL,
  MODULE_ID             NUMBER(10)    NULL,
  NAMESPACE_ID          NUMBER(10)    NULL,
  REUSABLE_INDICATOR    NUMBER(3)     NULL,
  IS_DEPRECATED         NUMBER(3)     NOT NULL,
  REVISION_NUM          NUMBER(10)    NOT NULL,
  REVISION_TRACKING_NUM NUMBER(10)    NOT NULL,
  REVISION_ACTION       NUMBER(3)     NULL,
  RELEASE_ID            NUMBER(10)    NULL,
  CURRENT_ASCCP_ID      NUMBER(10)    NULL,
  IS_NILLABLE           NUMBER(3)     NOT NULL,

  CONSTRAINT ASCCP_PK PRIMARY KEY (ASCCP_ID),
  CONSTRAINT ASCCP_ROLE_OF_ACC FOREIGN KEY (ROLE_OF_ACC_ID) REFERENCES ACC (ACC_ID),
  CONSTRAINT ASCCP_CREATED_BY_FK FOREIGN KEY (CREATED_BY) REFERENCES APP_USER (APP_USER_ID),
  CONSTRAINT ASCCP_OWNER_USER_ID_FK FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER (APP_USER_ID),
  CONSTRAINT ASCCP_LAST_UPDATED_BY_FK FOREIGN KEY (LAST_UPDATED_BY) REFERENCES APP_USER (APP_USER_ID),
  CONSTRAINT ASCCP_MODULE_ID_FK FOREIGN KEY (MODULE_ID) REFERENCES MODULE (MODULE_ID),
  CONSTRAINT ASCCP_NAMESPACE_ID_FK FOREIGN KEY (NAMESPACE_ID) REFERENCES NAMESPACE (NAMESPACE_ID),
  CONSTRAINT ASCCP_RELEASED_ID_FK FOREIGN KEY (RELEASE_ID) REFERENCES RELEASE (RELEASE_ID),
  CONSTRAINT ASCCP_CURRENT_ASCCP_ID_FK FOREIGN KEY (CURRENT_ASCCP_ID) REFERENCES ASCCP (ASCCP_ID)
);

CREATE UNIQUE INDEX ASCCP_UK1 ON ASCCP (GUID);

CREATE SEQUENCE ASCCP_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 NOCYCLE;

-- -----------------------------------------------------
-- TABLE ASBIEP
-- -----------------------------------------------------
CREATE TABLE ASBIEP (
  ASBIEP_ID             NUMBER(10)    NOT NULL,
  GUID                  VARCHAR2(41)  NOT NULL,
  BASED_ASCCP_ID        NUMBER(10)    NOT NULL,
  ROLE_OF_ABIE_ID       NUMBER(10)    NOT NULL,
  DEFINITION            CLOB          NULL,
  REMARK                VARCHAR2(225) NULL,
  BIZ_TERM              VARCHAR2(225) NULL,
  CREATED_BY            NUMBER(10)    NOT NULL,
  LAST_UPDATED_BY       NUMBER(10)    NOT NULL,
  CREATION_TIMESTAMP    TIMESTAMP     NOT NULL,
  LAST_UPDATE_TIMESTAMP TIMESTAMP     NOT NULL,
  BOD_ID                NUMBER(10)    NOT NULL,

  CONSTRAINT ASBIEP_PK PRIMARY KEY (ASBIEP_ID),
  CONSTRAINT ASBIEP_BASED_ASCCP_ID FOREIGN KEY (BASED_ASCCP_ID) REFERENCES ASCCP (ASCCP_ID),
  CONSTRAINT ASBIEP_ROLE_OF_ABIE_ID FOREIGN KEY (ROLE_OF_ABIE_ID) REFERENCES ABIE (ABIE_ID),
  CONSTRAINT ASBIEP_CREATED_BY_FK FOREIGN KEY (CREATED_BY) REFERENCES APP_USER (APP_USER_ID),
  CONSTRAINT ASBIEP_LAST_UPDATED_BY_FK FOREIGN KEY (LAST_UPDATED_BY) REFERENCES APP_USER (APP_USER_ID),
  CONSTRAINT ASBIEP_BOD_ID_FK FOREIGN KEY (BOD_ID) REFERENCES BOD (BOD_ID)
);

CREATE UNIQUE INDEX ASBIEP_UK1 ON ASBIEP (GUID);

CREATE SEQUENCE ASBIEP_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 2000 NOCYCLE;

-- -----------------------------------------------------
-- TABLE ASCC
-- -----------------------------------------------------
CREATE TABLE ASCC (
  ASCC_ID               NUMBER(10)    NOT NULL,
  GUID                  VARCHAR2(41)  NOT NULL,
  CARDINALITY_MIN       NUMBER(10)    NOT NULL,
  CARDINALITY_MAX       NUMBER(10)    NOT NULL,
  SEQ_KEY               NUMBER(10)    NOT NULL,
  FROM_ACC_ID           NUMBER(10)    NOT NULL,
  TO_ASCCP_ID           NUMBER(10)    NOT NULL,
  DEN                   VARCHAR2(200) NOT NULL,
  DEFINITION            CLOB          NULL,
  IS_DEPRECATED         NUMBER(3)     NOT NULL,
  CREATED_BY            NUMBER(10)    NOT NULL,
  OWNER_USER_ID         NUMBER(10)    NOT NULL,
  LAST_UPDATED_BY       NUMBER(10)    NOT NULL,
  CREATION_TIMESTAMP    TIMESTAMP     NOT NULL,
  LAST_UPDATE_TIMESTAMP TIMESTAMP     NOT NULL,
  STATE                 NUMBER(10)    NOT NULL,
  REVISION_NUM          NUMBER(10)    NOT NULL,
  REVISION_TRACKING_NUM NUMBER(10)    NOT NULL,
  REVISION_ACTION       NUMBER(3)     NULL,
  RELEASE_ID            NUMBER(10)    NULL,
  CURRENT_ASCC_ID       NUMBER(10)    NULL,

  CONSTRAINT ASCC_PK PRIMARY KEY (ASCC_ID),
  CONSTRAINT ASCC_FROM_ACC_ID_FK FOREIGN KEY (FROM_ACC_ID) REFERENCES ACC (ACC_ID),
  CONSTRAINT ASCC_TO_ASCCP_ID_FK FOREIGN KEY (TO_ASCCP_ID) REFERENCES ASCCP (ASCCP_ID),
  CONSTRAINT ASCC_CREATED_BY_FK FOREIGN KEY (CREATED_BY) REFERENCES APP_USER (APP_USER_ID),
  CONSTRAINT ASCC_OWNER_USER_ID_FK FOREIGN KEY (OWNER_USER_ID) REFERENCES APP_USER (APP_USER_ID),
  CONSTRAINT ASCC_LAST_UPDATED_BY_FK FOREIGN KEY (LAST_UPDATED_BY) REFERENCES APP_USER (APP_USER_ID),
  CONSTRAINT ASCC_RELEASE_ID_FK FOREIGN KEY (RELEASE_ID) REFERENCES RELEASE (RELEASE_ID),
  CONSTRAINT ASCC_CURRENT_ASCC_ID_FK FOREIGN KEY (CURRENT_ASCC_ID) REFERENCES ASCC (ASCC_ID)
);

CREATE UNIQUE INDEX ASCC_UK1 ON ASCC (GUID, FROM_ACC_ID, TO_ASCCP_ID);

CREATE SEQUENCE ASCC_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 NOCYCLE;

-- -----------------------------------------------------
-- TABLE ASBIE
-- -----------------------------------------------------
CREATE TABLE ASBIE (
  ASBIE_ID              NUMBER(10)    NOT NULL,
  GUID                  VARCHAR2(41)  NOT NULL,
  FROM_ABIE_ID          NUMBER(10)    NOT NULL,
  TO_ASBIEP_ID          NUMBER(10)    NOT NULL,
  BASED_ASCC            NUMBER(10)    NOT NULL,
  DEFINITION            CLOB          NULL,
  CARDINALITY_MIN       NUMBER(10)    NOT NULL,
  CARDINALITY_MAX       NUMBER(10)    NOT NULL,
  IS_NILLABLE           NUMBER(3)     NOT NULL,
  REMARK                VARCHAR2(225) NULL,
  CREATED_BY            NUMBER(10)    NOT NULL,
  LAST_UPDATED_BY       NUMBER(10)    NOT NULL,
  CREATION_TIMESTAMP    TIMESTAMP     NOT NULL,
  LAST_UPDATE_TIMESTAMP TIMESTAMP     NOT NULL,
  SEQ_KEY               NUMBER(10)    NOT NULL,
  IS_USED               NUMBER(3)     NOT NULL,
  BOD_ID                NUMBER(10)    NOT NULL,

  CONSTRAINT ASBIE_PK PRIMARY KEY (ASBIE_ID),
  CONSTRAINT ASBIE_FROM_ABIE_ID FOREIGN KEY (FROM_ABIE_ID) REFERENCES ABIE (ABIE_ID),
  CONSTRAINT ASBIE_TO_ASBIEP_ID_FK FOREIGN KEY (TO_ASBIEP_ID) REFERENCES ASBIEP (ASBIEP_ID),
  CONSTRAINT ASBIE_BASED_ASCC_ID_FK FOREIGN KEY (BASED_ASCC) REFERENCES ASCC (ASCC_ID),
  CONSTRAINT ASBIE_CREATED_BY_FK FOREIGN KEY (CREATED_BY) REFERENCES APP_USER (APP_USER_ID),
  CONSTRAINT ASBIE_LAST_UPDATED_BY_FK FOREIGN KEY (LAST_UPDATED_BY) REFERENCES APP_USER (APP_USER_ID),
  CONSTRAINT ASBIE_BOD_ID_FK FOREIGN KEY (BOD_ID) REFERENCES BOD (BOD_ID)
);

CREATE UNIQUE INDEX ASBIE_UK1 ON ASBIE (GUID, FROM_ABIE_ID, TO_ASBIEP_ID);

CREATE SEQUENCE ASBIE_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 2000 NOCYCLE;

-- -----------------------------------------------------
-- TABLE CODE_LIST_VALUE
-- -----------------------------------------------------
CREATE TABLE CODE_LIST_VALUE (
  CODE_LIST_VALUE_ID  NUMBER(10)    NOT NULL,
  CODE_LIST_ID        NUMBER(10)    NOT NULL,
  VALUE               VARCHAR2(100) NOT NULL,
  NAME                VARCHAR2(100) NULL,
  DEFINITION          CLOB          NULL,
  DEFINITION_SOURCE   VARCHAR2(100) NULL,
  USED_INDICATOR      NUMBER(3)     NOT NULL,
  LOCKED_INDICATOR    NUMBER(3)     NOT NULL,
  EXTENSION_INDICATOR NUMBER(3)     NOT NULL,

  CONSTRAINT CLV_PK PRIMARY KEY (CODE_LIST_VALUE_ID),
  CONSTRAINT CLV_CODE_LIST_ID_FK FOREIGN KEY (CODE_LIST_ID) REFERENCES CODE_LIST (CODE_LIST_ID)
);

CREATE SEQUENCE CODE_LIST_VALUE_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 NOCYCLE;

-- -----------------------------------------------------
-- TABLE CTX_CATEGORY
-- -----------------------------------------------------
CREATE TABLE CTX_CATEGORY (
  CTX_CATEGORY_ID NUMBER(10)   NOT NULL,
  GUID            VARCHAR2(41) NOT NULL,
  NAME            VARCHAR2(45) NULL,
  DESCRIPTION     CLOB         NULL,

  CONSTRAINT CTX_CATEGORY_PK PRIMARY KEY (CTX_CATEGORY_ID)
);

CREATE UNIQUE INDEX CTX_CATEGORY_UK1 ON CTX_CATEGORY (GUID);

CREATE SEQUENCE CTX_CATEGORY_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 NOCYCLE;

-- -----------------------------------------------------
-- TABLE CLASSIFICATION_CTX_SCHEME
-- -----------------------------------------------------
CREATE TABLE CLASSIFICATION_CTX_SCHEME (
  CLASSIFICATION_CTX_SCHEME_ID NUMBER(10)    NOT NULL,
  GUID                         VARCHAR2(41)  NOT NULL,
  SCHEME_ID                    VARCHAR2(45)  NOT NULL,
  SCHEME_NAME                  VARCHAR2(255) NULL,
  DESCRIPTION                  CLOB          NULL,
  SCHEME_AGENCY_ID             VARCHAR2(45)  NOT NULL,
  SCHEME_VERSION_ID            VARCHAR2(45)  NOT NULL,
  CTX_CATEGORY_ID              NUMBER(10)    NOT NULL,
  CREATED_BY                   NUMBER(10)    NOT NULL,
  LAST_UPDATED_BY              NUMBER(10)    NOT NULL,
  CREATION_TIMESTAMP           TIMESTAMP     NOT NULL,
  LAST_UPDATE_TIMESTAMP        TIMESTAMP     NOT NULL,

  CONSTRAINT CTX_SCHEME_PK PRIMARY KEY (CLASSIFICATION_CTX_SCHEME_ID),
  CONSTRAINT CTX_SCHEME_CTX_CAT_ID_FK FOREIGN KEY (CTX_CATEGORY_ID) REFERENCES CTX_CATEGORY (CTX_CATEGORY_ID),
  CONSTRAINT CTX_SCHEME_CREATED_BY_FK FOREIGN KEY (CREATED_BY) REFERENCES APP_USER (APP_USER_ID),
  CONSTRAINT CTX_SCHEME_LAST_UPDATED_BY_FK FOREIGN KEY (LAST_UPDATED_BY) REFERENCES APP_USER (APP_USER_ID)
);

CREATE UNIQUE INDEX CTX_SCHEME_UK1 ON CLASSIFICATION_CTX_SCHEME (GUID);

CREATE SEQUENCE CTX_SCHEME_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 NOCYCLE;

-- -----------------------------------------------------
-- TABLE CTX_SCHEME_VALUE
-- -----------------------------------------------------
CREATE TABLE CTX_SCHEME_VALUE (
  CTX_SCHEME_VALUE_ID NUMBER(10)   NOT NULL,
  GUID                VARCHAR2(41) NOT NULL,
  VALUE               VARCHAR2(45) NOT NULL,
  MEANING             CLOB         NULL,
  OWNER_CTX_SCHEME_ID NUMBER(10)   NULL,

  CONSTRAINT CSV_PK PRIMARY KEY (CTX_SCHEME_VALUE_ID),
  CONSTRAINT CSV_OWNER_CTX_SCHEME_ID_FK FOREIGN KEY (OWNER_CTX_SCHEME_ID) REFERENCES CLASSIFICATION_CTX_SCHEME (CLASSIFICATION_CTX_SCHEME_ID)
);

CREATE UNIQUE INDEX CTX_SCHEME_VALUE_UK1 ON CTX_SCHEME_VALUE (GUID);

CREATE SEQUENCE CTX_SCHEME_VALUE_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 NOCYCLE;

-- -----------------------------------------------------
-- TABLE BIZ_CTX_VALUE
-- -----------------------------------------------------
CREATE TABLE BIZ_CTX_VALUE (
  BIZ_CTX_VALUE_ID    NUMBER(10) NOT NULL,
  BIZ_CTX_ID          NUMBER(10) NOT NULL,
  CTX_SCHEME_VALUE_ID NUMBER(10) NOT NULL,

  CONSTRAINT BIZ_CTX_VALUE_PK PRIMARY KEY (BIZ_CTX_VALUE_ID),
  CONSTRAINT BIZ_CTX_VALUE_BIZ_CTX_ID_FK FOREIGN KEY (BIZ_CTX_ID) REFERENCES BIZ_CTX (BIZ_CTX_ID),
  CONSTRAINT BIZ_CTX_VALUE_CSV_ID_FK FOREIGN KEY (CTX_SCHEME_VALUE_ID) REFERENCES CTX_SCHEME_VALUE (CTX_SCHEME_VALUE_ID)
);

CREATE SEQUENCE BIZ_CTX_VALUE_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 NOCYCLE;

-- -----------------------------------------------------
-- TABLE BBIE_SC
-- -----------------------------------------------------
CREATE TABLE BBIE_SC (
  BBIE_SC_ID          NUMBER(10)     NOT NULL,
  BBIE_ID             NUMBER(10)     NOT NULL,
  DT_SC_ID            NUMBER(10)     NOT NULL,
  DT_SC_PRI_RESTRI_ID NUMBER(10)     NULL,
  CODE_LIST_ID        NUMBER(10)     NULL,
  AGENCY_ID_LIST_ID   NUMBER(10)     NULL,
  MIN_CARDINALITY     NUMBER(10)     NOT NULL,
  MAX_CARDINALITY     NUMBER(10)     NULL,
  DEFAULT_VALUE       VARCHAR2(4000) NULL,
  FIXED_VALUE         VARCHAR2(4000) NULL,
  DEFINITION          CLOB           NULL,
  REMARK              VARCHAR2(225)  NULL,
  BIZ_TERM            VARCHAR2(225)  NULL,
  IS_USED             NUMBER(3)      NOT NULL,
  BOD_ID              NUMBER(10)     NOT NULL,

  CONSTRAINT BBIE_SC_PK PRIMARY KEY (BBIE_SC_ID),
  CONSTRAINT BBIE_BBIE_ID_FK FOREIGN KEY (BBIE_ID) REFERENCES BBIE (BBIE_ID),
  CONSTRAINT BBIE_SC_DT_SC_ID_FK FOREIGN KEY (DT_SC_ID) REFERENCES DT_SC (DT_SC_ID),
  CONSTRAINT BBIE_SC_DT_SC_PRI_RESTRI_ID_FK FOREIGN KEY (DT_SC_PRI_RESTRI_ID) REFERENCES BDT_SC_PRI_RESTRI (BDT_SC_PRI_RESTRI_ID),
  CONSTRAINT BBIE_SC_CODE_LIST_ID_FK FOREIGN KEY (CODE_LIST_ID) REFERENCES CODE_LIST (CODE_LIST_ID),
  CONSTRAINT BBIE_SC_AGENCY_ID_LIST_ID_FK FOREIGN KEY (AGENCY_ID_LIST_ID) REFERENCES AGENCY_ID_LIST (AGENCY_ID_LIST_ID),
  CONSTRAINT BBIE_SC_BOD_ID_FK FOREIGN KEY (BOD_ID) REFERENCES BOD (BOD_ID)
);

CREATE SEQUENCE BBIE_SC_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 2000 NOCYCLE;

-- -----------------------------------------------------
-- TABLE BIE_USER_EXT_REVISION
-- -----------------------------------------------------
CREATE TABLE BIE_USER_EXT_REVISION (
  BIE_USER_EXT_REVISION_ID NUMBER(10) NOT NULL,
  TOP_LEVEL_ABIE_ID        NUMBER(10) NOT NULL,
  EXT_ABIE_ID              NUMBER(10) NULL,
  EXT_ACC_ID               NUMBER(10) NOT NULL,
  USER_EXT_ACC_ID          NUMBER(10) NOT NULL,
  REVISED_INDICATOR        NUMBER(3)  NOT NULL,

  CONSTRAINT BUER_PK PRIMARY KEY (BIE_USER_EXT_REVISION_ID),
  CONSTRAINT BUER_TOP_LEVEL_ABIE_ID_FK FOREIGN KEY (TOP_LEVEL_ABIE_ID) REFERENCES ABIE (ABIE_ID),
  CONSTRAINT BUER_EXT_ABIE_ID_FK FOREIGN KEY (EXT_ABIE_ID) REFERENCES ABIE (ABIE_ID),
  CONSTRAINT BUER_EXT_ACC_ID_FK FOREIGN KEY (EXT_ACC_ID) REFERENCES ACC (ACC_ID),
  CONSTRAINT BUER_USER_EXT_ACC_ID_FK FOREIGN KEY (USER_EXT_ACC_ID) REFERENCES ACC (ACC_ID)
);

CREATE SEQUENCE BIE_USER_EXT_REVISION_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 NOCYCLE;

-- -----------------------------------------------------
-- TABLE BLOB_CONTENT
-- -----------------------------------------------------
CREATE TABLE BLOB_CONTENT (
  BLOB_CONTENT_ID NUMBER(10) NOT NULL,
  CONTENT         BLOB       NOT NULL,
  RELEASE_ID      NUMBER(10) NOT NULL,
  MODULE_ID       NUMBER(10) NOT NULL,

  CONSTRAINT BLOB_CONTENT_PK PRIMARY KEY (BLOB_CONTENT_ID),
  CONSTRAINT BLOB_CONTENT_RELEASE_ID_FK FOREIGN KEY (RELEASE_ID) REFERENCES RELEASE (RELEASE_ID),
  CONSTRAINT BLOB_CONTENT_MODULE_ID_FK FOREIGN KEY (MODULE_ID) REFERENCES MODULE (MODULE_ID)
);

CREATE SEQUENCE BLOB_CONTENT_ID_SEQ
MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 NOCYCLE;