spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_DATABASE:oagi}?useSSL=false
    username: ${DB_USERNAME:oagi}
    password: ${DB_PASSWORD:oagi}

  jooq:
    sql-dialect: mysql


logging:
  level:
    org.springframework: INFO
    org.springframework.security: DEBUG
    org.springframework.websocket: DEBUG
    org.springframework.messaging: DEBUG
    org.jooq: DEBUG
    org.oagi.score: DEBUG