CREATE TABLE `agency_id_list_value_manifest`
(
    `agency_id_list_value_manifest_id`             bigint(20) unsigned NOT NULL AUTO_INCREMENT COMMENT 'An internal, primary database key of a AGENCY_ID_LIST_VALUE_MANIFEST record.',
    `release_id`                                   bigint(20) unsigned NOT NULL COMMENT 'Foreign key to the RELEASE table.',
    `agency_id_list_value_id`                      bigint(20) unsigned NOT NULL COMMENT 'Foreign key to the AGENCY_ID_LIST_VALUE table.',
    `agency_id_list_manifest_id`                   bigint(20) unsigned NOT NULL COMMENT 'Foreign key to the AGENCY_ID_LIST_MANIFEST table.',
    `based_agency_id_list_value_manifest_id`       bigint(20) unsigned DEFAULT NULL COMMENT 'A self-reference to the AGENCY_ID_LIST_VALUE_MANIFEST record that this record is based on (its base/supertype from which it was derived).',
    `conflict`                                     tinyint(1) NOT NULL DEFAULT 0 COMMENT 'This indicates that there is a conflict between self and relationship.',
    `replacement_agency_id_list_value_manifest_id` bigint(20) unsigned DEFAULT NULL COMMENT 'This refers to a replacement manifest if the record is deprecated.',
    `prev_agency_id_list_value_manifest_id`        bigint(20) unsigned DEFAULT NULL COMMENT 'A self-reference to the corresponding AGENCY_ID_LIST_VALUE_MANIFEST record in the previous release (revision chain). NULL for the first revision.',
    `next_agency_id_list_value_manifest_id`        bigint(20) unsigned DEFAULT NULL COMMENT 'A self-reference to the corresponding AGENCY_ID_LIST_VALUE_MANIFEST record in the next release (revision chain). NULL for the latest revision.',
    PRIMARY KEY (`agency_id_list_value_manifest_id`),
    KEY                                            `agency_id_list_value_manifest_agency_id_list_value_id_fk` (`agency_id_list_value_id`),
    KEY                                            `agency_id_list_value_manifest_release_id_fk` (`release_id`),
    KEY                                            `agency_id_list_value_manifest_agency_id_list_manifest_id_fk` (`agency_id_list_manifest_id`),
    KEY                                            `agency_id_list_value_manifest_prev_agency_id_list_value_manif_fk` (`prev_agency_id_list_value_manifest_id`),
    KEY                                            `agency_id_list_value_manifest_next_agency_id_list_value_manif_fk` (`next_agency_id_list_value_manifest_id`),
    KEY                                            `agency_id_list_value_replacement_agency_id_list_manif_fk` (`replacement_agency_id_list_value_manifest_id`),
    KEY                                            `agency_id_list_value_manifest_based_agency_id_list_val_mnf_id_fk` (`based_agency_id_list_value_manifest_id`),
    CONSTRAINT `agency_id_list_value_manifest_agency_id_list_manifest_id_fk` FOREIGN KEY (`agency_id_list_manifest_id`) REFERENCES `agency_id_list_manifest` (`agency_id_list_manifest_id`),
    CONSTRAINT `agency_id_list_value_manifest_agency_id_list_value_id_fk` FOREIGN KEY (`agency_id_list_value_id`) REFERENCES `agency_id_list_value` (`agency_id_list_value_id`),
    CONSTRAINT `agency_id_list_value_manifest_based_agency_id_list_val_mnf_id_fk` FOREIGN KEY (`based_agency_id_list_value_manifest_id`) REFERENCES `agency_id_list_value_manifest` (`agency_id_list_value_manifest_id`),
    CONSTRAINT `agency_id_list_value_manifest_next_agency_id_list_value_manif_fk` FOREIGN KEY (`next_agency_id_list_value_manifest_id`) REFERENCES `agency_id_list_value_manifest` (`agency_id_list_value_manifest_id`),
    CONSTRAINT `agency_id_list_value_manifest_prev_agency_id_list_value_manif_fk` FOREIGN KEY (`prev_agency_id_list_value_manifest_id`) REFERENCES `agency_id_list_value_manifest` (`agency_id_list_value_manifest_id`),
    CONSTRAINT `agency_id_list_value_manifest_release_id_fk` FOREIGN KEY (`release_id`) REFERENCES `release` (`release_id`),
    CONSTRAINT `agency_id_list_value_replacement_agency_id_list_manif_fk` FOREIGN KEY (`replacement_agency_id_list_value_manifest_id`) REFERENCES `agency_id_list_value_manifest` (`agency_id_list_value_manifest_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='A release-specific handle to an AGENCY_ID_LIST_VALUE record, pinning a value within an agency identification list to a RELEASE and to its owning AGENCY_ID_LIST_MANIFEST. It carries the revision chain, referencing the corresponding AGENCY_ID_LIST_VALUE_MANIFEST records in the previous and next releases.';