package org.oagi.srt.persistence.dao.mysql;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

import org.chanchan.common.persistence.db.BfPersistenceException;
import org.chanchan.common.persistence.db.DBAgent;
import org.oagi.srt.common.QueryCondition;
import org.oagi.srt.common.SRTObject;
import org.oagi.srt.persistence.dao.SRTDAO;
import org.oagi.srt.persistence.dao.SRTDAOException;
import org.oagi.srt.persistence.dto.ASBIEVO;

/**
*
* @author Jaehun Lee
* @version 1.0
*
*/

public class ASBIEMysqlDAO extends SRTDAO{
	private final String _tableName = "asbie";

	private final String _FIND_ALL_ASBIE_STATEMENT = 
			"SELECT ASBIE_ID, Assoc_From_ABIE_ID, Assoc_To_ASBIEP_ID, Based_ASCC, Assoc_Description, Property_Description, Cardinality_Min, Cardinality_Max FROM "
					+ _tableName;

	private final String _FIND_ASBIE_STATEMENT = 
			"SELECT ASBIE_ID, Assoc_From_ABIE_ID, Assoc_To_ASBIEP_ID, Based_ASCC, Assoc_Description, Property_Description, Cardinality_Min, Cardinality_Max FROM "
					+ _tableName;
	
	private final String _INSERT_ASBIE_STATEMENT = 
			"INSERT INTO " + _tableName + " (Assoc_From_ABIE_ID, Assoc_To_ASBIEP_ID, Based_ASCC, Assoc_Description, Property_Description, Cardinality_Min, Cardinality_Max)"
					+ " VALUES (?, ?, ?, ?, ?, ?, ?)";

	private final String _UPDATE_ASBIE_STATEMENT = 
			"UPDATE " + _tableName
			+ " SET ASBIE_ID = ?, Assoc_From_ABIE_ID = ?, Assoc_To_ASBIEP_ID = ?, Based_ASCC = ?, Assoc_Description = ?, Property_Description = ?, Cardinality_Min = ?, "
			+ "Cardinality_Max = ?";

	private final String _DELETE_ASBIE_STATEMENT = 
			"DELETE FROM " + _tableName + " WHERE ASBIE_ID = ?";

	public boolean insertObject(SRTObject obj) throws SRTDAOException {
		DBAgent tx = new DBAgent();
		ASBIEVO asbievo = (ASBIEVO)obj;
		try {
			Connection conn = tx.open();
			PreparedStatement ps = null;
			ps = conn.prepareStatement(_INSERT_ASBIE_STATEMENT);
			ps.setInt(1, asbievo.getAssocFromABIEID());
			ps.setInt(2, asbievo.getAssocToASBIEPID());
			ps.setInt(3, asbievo.getBasedASCC());
			ps.setString(4, asbievo.getAssocDescription());
			ps.setString(5, asbievo.getPropertyDescription());
			ps.setInt(6, asbievo.getCardinalityMin());
			ps.setInt(7, asbievo.getCardinalityMax());

			ps.executeUpdate();

			ResultSet tableKeys = ps.getGeneratedKeys();
			tableKeys.next();
			//int autoGeneratedID = tableKeys.getInt(1);
			ps.close();
			tx.commit();
		} catch (BfPersistenceException e) {
			tx.rollback();
			throw new SRTDAOException(SRTDAOException.DAO_INSERT_ERROR, e);
		} catch (SQLException e) {
			e.printStackTrace();
			tx.rollback();
			throw new SRTDAOException(SRTDAOException.SQL_EXECUTION_FAILED, e);
		} finally {
			tx.close();
		}
		return true;
	}

	public SRTObject findObject(QueryCondition qc) throws SRTDAOException {
		DBAgent tx = new DBAgent();
		PreparedStatement ps = null;
		ResultSet rs = null;
		ASBIEVO asbievo = new ASBIEVO();
		try {
			Connection conn = tx.open();
			String sql = _FIND_ASBIE_STATEMENT;

			String WHERE_OR_AND = " WHERE ";
			int nCond = qc.getSize();
			if (nCond > 0) {
				for (int n = 0; n < nCond; n++) {
					sql += WHERE_OR_AND + qc.getField(n) + " = ?";
					WHERE_OR_AND = " AND ";
				}
			}
			ps = conn.prepareStatement(sql);
			if (nCond > 0) {
				for (int n = 0; n < nCond; n++) {
					Object value = qc.getValue(n);
					if (value instanceof String) {
						ps.setString(n+1, (String) value);
					} else if (value instanceof Integer) {
						ps.setInt(n+1, ((Integer) value).intValue());
					}
				}
			}

			rs = ps.executeQuery();
			if (rs.next()) {
				asbievo.setASBIEID(rs.getInt("ASBIE_ID"));
				asbievo.setAssocFromABIEID(rs.getInt("Assoc_From_ABIE_ID"));
				asbievo.setAssocToASBIEPID(rs.getInt("Assoc_To_ASBIEP_ID"));
				asbievo.setBasedASCC(rs.getInt("Based_ASCC"));
				asbievo.setAssocDescription(rs.getString("Assoc_Description"));
				asbievo.setPropertyDescription(rs.getString("Property_Description"));
				asbievo.setCardinalityMin(rs.getInt("Cardinality_Min"));
				asbievo.setCardinalityMax(rs.getInt("Cardinality_Max"));
			}
			tx.commit();
			conn.close();
		} catch (BfPersistenceException e) {
			throw new SRTDAOException(SRTDAOException.DAO_FIND_ERROR, e);
		} catch (SQLException e) {
			throw new SRTDAOException(SRTDAOException.SQL_EXECUTION_FAILED, e);
		} finally {
			if(ps != null) {
				try {
					ps.close();
				} catch (SQLException e) {}
			}
			if(rs != null) {
				try {
					rs.close();
				} catch (SQLException e) {}
			}
			tx.close();
		}
		return asbievo;
	}

	public ArrayList<SRTObject> findObjects() throws SRTDAOException {
		ArrayList<SRTObject> list = new ArrayList<SRTObject>();

		DBAgent tx = new DBAgent();
		PreparedStatement ps = null;
		ResultSet rs = null;
		try {
			Connection conn = tx.open();
			String sql = _FIND_ALL_ASBIE_STATEMENT;
			ps = conn.prepareStatement(sql);
			rs = ps.executeQuery();
			while (rs.next()) {
				ASBIEVO asbievo = new ASBIEVO();
				asbievo.setASBIEID(rs.getInt("ASBIE_ID"));
				asbievo.setAssocFromABIEID(rs.getInt("Assoc_From_ABIE_ID"));
				asbievo.setAssocToASBIEPID(rs.getInt("Assoc_To_ASBIEP_ID"));
				asbievo.setBasedASCC(rs.getInt("Based_ASCC"));
				asbievo.setAssocDescription(rs.getString("Assoc_Description"));
				asbievo.setPropertyDescription(rs.getString("Property_Description"));
				asbievo.setCardinalityMin(rs.getInt("Cardinality_Min"));
				asbievo.setCardinalityMax(rs.getInt("Cardinality_Max"));
				list.add(asbievo);
			}
			tx.commit();
			conn.close();
		} catch (BfPersistenceException e) {
			throw new SRTDAOException(SRTDAOException.DAO_FIND_ERROR, e);
		} catch (SQLException e) {
			throw new SRTDAOException(SRTDAOException.SQL_EXECUTION_FAILED, e);
		} finally {
			if(ps != null) {
				try {
					ps.close();
				} catch (SQLException e) {}
			}
			if(rs != null) {
				try {
					rs.close();
				} catch (SQLException e) {}
			}
			tx.close();
		}

		return list;
	}

	public boolean updateObject(SRTObject obj) throws SRTDAOException {
		DBAgent tx = new DBAgent();
		ASBIEVO asbievo = (ASBIEVO)obj;
		PreparedStatement ps = null;
		try {
			Connection conn = tx.open();

			ps = conn.prepareStatement(_UPDATE_ASBIE_STATEMENT);
			
			ps.setInt(1, asbievo.getAssocFromABIEID());
			ps.setInt(2, asbievo.getAssocToASBIEPID());
			ps.setInt(3, asbievo.getBasedASCC());
			ps.setString(4, asbievo.getAssocDescription());
			ps.setString(5, asbievo.getPropertyDescription());
			ps.setInt(6, asbievo.getCardinalityMin());
			ps.setInt(7, asbievo.getCardinalityMax());
			ps.executeUpdate();

			tx.commit();
		} catch (BfPersistenceException e) {
			tx.rollback(e);
			throw new SRTDAOException(SRTDAOException.DAO_UPDATE_ERROR, e);
		} catch (SQLException e) {
			tx.rollback(e);
			throw new SRTDAOException(SRTDAOException.SQL_EXECUTION_FAILED, e);
		} finally {
			if(ps != null) {
				try {
					ps.close();
				} catch (SQLException e) {}
			}
			tx.close();
		}

		return true;
	}

	public boolean deleteObject(SRTObject obj) throws SRTDAOException {
		ASBIEVO asbievo = (ASBIEVO)obj;

		DBAgent tx = new DBAgent();
		PreparedStatement ps = null;
		try {
			Connection conn = tx.open();

			ps = conn.prepareStatement(_DELETE_ASBIE_STATEMENT);
			ps.setInt(1, asbievo.getASBIEID());
			ps.executeUpdate();

			tx.commit();
		} catch (BfPersistenceException e) {
			tx.rollback(e);
			throw new SRTDAOException(SRTDAOException.DAO_DELETE_ERROR, e);
		} catch (SQLException e) {
			tx.rollback(e);
			throw new SRTDAOException(SRTDAOException.SQL_EXECUTION_FAILED, e);
		} finally {
			if(ps != null) {
				try {
					ps.close();
				} catch (SQLException e) {}
			}
			tx.close();
		}

		return true;

	}

	@Override
	public ArrayList<SRTObject> findObjects(QueryCondition qc)
			throws SRTDAOException {
		// TODO Auto-generated method stub
		return null;
	}
}
