package org.oagi.srt.persistence.dao.mysql;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

import org.chanchan.common.persistence.db.BfPersistenceException;
import org.chanchan.common.persistence.db.DBAgent;
import org.oagi.srt.common.QueryCondition;
import org.oagi.srt.common.SRTObject;
import org.oagi.srt.persistence.dao.SRTDAO;
import org.oagi.srt.persistence.dao.SRTDAOException;
import org.oagi.srt.persistence.dto.NamespaceVO;

/**
 *
 * @author Jaehun Lee
 * @version 1.0
 *
 */
public class NamespaceMysqlDAO extends SRTDAO {

	private final String _tableName = "namespace";

	private final String _FIND_ALL_NAMESPACE_STATEMENT = 
			"SELECT namespace_id, uri, prefix, prescription, owner_user_id, "
					+ "created_by, last_updated_by, creation_timestamp, last_updated_timestamp"
					+ " FROM " + _tableName;

	private final String _FIND_NAMESPACE_STATEMENT = 
			"SELECT namespace_id, uri, prefix, prescription, owner_user_id, "
					+ "created_by, last_updated_by, creation_timestamp, last_updated_timestamp"
					+ " FROM " + _tableName;
	
	private final String _INSERT_NAMESPACE_STATEMENT = 
			"INSERT INTO " + _tableName + " (uri, prefix, prescription, owner_user_id, "
					+ "created_by, last_updated_by, creation_timestamp, last_updated_timestamp) "
					+ "VALUES (?, ?, ?, ?, ?, ?, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)";

	private final String _UPDATE_NAMESPACE_STATEMENT = 
			"UPDATE " + _tableName
			+ " SET Last_Update_Timestamp = CURRENT_TIMESTAMP, uri = ?, prefix = ?, prescription = ?, owner_user_id = ?, "
			+ "created_by = ?, last_updated_by = ?, creation_timestamp = ? WHERE namespace_id = ?";

	@Override
	public int findMaxId() throws SRTDAOException {
		// TODO Auto-generated method stub
		return 0;
	}
	
	private final String _DELETE_NAMESPACE_STATEMENT = 
			"DELETE FROM " + _tableName + " WHERE namespace_id = ?";

	public int insertObject(SRTObject obj) throws SRTDAOException {
		DBAgent tx = new DBAgent();
		NamespaceVO namespaceVO = (NamespaceVO)obj;
		try {
			Connection conn = tx.open();
			PreparedStatement ps = null;
			ps = conn.prepareStatement(_INSERT_NAMESPACE_STATEMENT);
			ps.setString(1, namespaceVO.getUri());
			ps.setString(2, namespaceVO.getPrefix());
			ps.setString(3, namespaceVO.getPrescription());
			ps.setInt(4, namespaceVO.getOwneruserID());
			ps.setInt(5, namespaceVO.getCreatedByUserId());
			ps.setInt(6, namespaceVO.getLastUpdatedByUserId());
			ps.executeUpdate();

			//ResultSet tableKeys = ps.getGeneratedKeys();
			//tableKeys.next();
			//int autoGeneratedID = tableKeys.getInt(1);

			ps.close();
			tx.commit();
		} catch (BfPersistenceException e) {
			tx.rollback();
			throw new SRTDAOException(SRTDAOException.DAO_INSERT_ERROR, e);
		} catch (SQLException e) {
			e.printStackTrace();
			tx.rollback();
			throw new SRTDAOException(SRTDAOException.SQL_EXECUTION_FAILED, e);
		} finally {
			tx.close();
		}
		return 1;
	}

	public SRTObject findObject(QueryCondition qc) throws SRTDAOException {
		DBAgent tx = new DBAgent();
		PreparedStatement ps = null;
		ResultSet rs = null;
		NamespaceVO namespaceVO = null;
		Connection conn = null;
		
		try {
			conn = tx.open();
			String sql = _FIND_NAMESPACE_STATEMENT;

			String WHERE_OR_AND = " WHERE ";
			int nCond = qc.getSize();
			if (nCond > 0) {
				for (int n = 0; n < nCond; n++) {
					sql += WHERE_OR_AND + qc.getField(n) + " = ?";
					WHERE_OR_AND = " AND ";
				}
			}
			
			int nCond2 = qc.getLikeSize();
			if (nCond2 > 0) {
				for (int n = 0; n < nCond2; n++) {
					sql += WHERE_OR_AND + qc.getLikeField(n) + " like ?";
					WHERE_OR_AND = " AND ";
				}
			}
			
			ps = conn.prepareStatement(sql);
			if (nCond > 0) {
				for (int n = 0; n < nCond; n++) {
					Object value = qc.getValue(n);
					if (value instanceof String) {
						ps.setString(n+1, (String) value);
					} else if (value instanceof Integer) {
						ps.setInt(n+1, ((Integer) value).intValue());
					}
				}
			}
			
			if (nCond2 > 0) {
				for (int n = 0; n < nCond2; n++) {
					Object value = qc.getLikeValue(n);
					if (value instanceof String) {
						ps.setString(nCond + n + 1, (String) value);
					} else if (value instanceof Integer) {
						ps.setInt(nCond + n + 1, ((Integer) value).intValue());
					}
				}
			}

			rs = ps.executeQuery();
			if (rs.next()) {
				namespaceVO = new NamespaceVO();
				namespaceVO.setNamespaceID(rs.getInt("namespace_id"));
				namespaceVO.setUri(rs.getString("uri"));
				namespaceVO.setPrefix(rs.getString("prefix"));
				namespaceVO.setPrescription(rs.getString("prescription"));
				namespaceVO.setOwneruserID(rs.getInt("owner_user_id"));
				namespaceVO.setCreatedByUserId(rs.getInt("Created_By"));
				namespaceVO.setLastUpdatedByUserId(rs.getInt("Last_Updated_By"));
				namespaceVO.setCreationTimestamp(rs.getTimestamp("Creation_Timestamp"));
				namespaceVO.setLastUpdateTimestamp(rs.getTimestamp("Last_Update_Timestamp"));
			}
			
			conn.close();
		} catch (BfPersistenceException e) {
			throw new SRTDAOException(SRTDAOException.DAO_FIND_ERROR, e);
		} catch (SQLException e) {
			throw new SRTDAOException(SRTDAOException.SQL_EXECUTION_FAILED, e);
		} finally {
			if(ps != null) {
				try {
					ps.close();
				} catch (SQLException e) {}
			}
			if(rs != null) {
				try {
					rs.close();
				} catch (SQLException e) {}
			}
			try {
				if(conn != null && !conn.isClosed())
					conn.close();
			} catch (SQLException e) {}
			tx.close();
		}
		return namespaceVO;
	}
	
	public SRTObject findObject(QueryCondition qc, Connection conn) throws SRTDAOException {
		PreparedStatement ps = null;
		ResultSet rs = null;
		NamespaceVO namespaceVO = null;
		
		try {
			String sql = _FIND_NAMESPACE_STATEMENT;

			String WHERE_OR_AND = " WHERE ";
			int nCond = qc.getSize();
			if (nCond > 0) {
				for (int n = 0; n < nCond; n++) {
					sql += WHERE_OR_AND + qc.getField(n) + " = ?";
					WHERE_OR_AND = " AND ";
				}
			}
			
			int nCond2 = qc.getLikeSize();
			if (nCond2 > 0) {
				for (int n = 0; n < nCond2; n++) {
					sql += WHERE_OR_AND + qc.getLikeField(n) + " like ?";
					WHERE_OR_AND = " AND ";
				}
			}
			
			ps = conn.prepareStatement(sql);
			if (nCond > 0) {
				for (int n = 0; n < nCond; n++) {
					Object value = qc.getValue(n);
					if (value instanceof String) {
						ps.setString(n+1, (String) value);
					} else if (value instanceof Integer) {
						ps.setInt(n+1, ((Integer) value).intValue());
					}
				}
			}
			
			if (nCond2 > 0) {
				for (int n = 0; n < nCond2; n++) {
					Object value = qc.getLikeValue(n);
					if (value instanceof String) {
						ps.setString(nCond + n + 1, (String) value);
					} else if (value instanceof Integer) {
						ps.setInt(nCond + n + 1, ((Integer) value).intValue());
					}
				}
			}

			rs = ps.executeQuery();
			if (rs.next()) {
				namespaceVO = new NamespaceVO();
				namespaceVO.setNamespaceID(rs.getInt("namespace_id"));
				namespaceVO.setUri(rs.getString("uri"));
				namespaceVO.setPrefix(rs.getString("prefix"));
				namespaceVO.setPrescription(rs.getString("prescription"));
				namespaceVO.setOwneruserID(rs.getInt("owner_user_id"));
				namespaceVO.setCreatedByUserId(rs.getInt("Created_By"));
				namespaceVO.setLastUpdatedByUserId(rs.getInt("Last_Updated_By"));
				namespaceVO.setCreationTimestamp(rs.getTimestamp("Creation_Timestamp"));
				namespaceVO.setLastUpdateTimestamp(rs.getTimestamp("Last_Update_Timestamp"));
			}
			
		} catch (SQLException e) {
			throw new SRTDAOException(SRTDAOException.SQL_EXECUTION_FAILED, e);
		} finally {
			if(ps != null) {
				try {
					ps.close();
				} catch (SQLException e) {}
			}
			if(rs != null) {
				try {
					rs.close();
				} catch (SQLException e) {}
			}
		}
		return namespaceVO;
	}
	
	public ArrayList<SRTObject> findObjects(QueryCondition qc) throws SRTDAOException {
		DBAgent tx = new DBAgent();
		PreparedStatement ps = null;
		ResultSet rs = null;
		ArrayList<SRTObject> list = new ArrayList<SRTObject>();
		try {
			Connection conn = tx.open();
			String sql = _FIND_NAMESPACE_STATEMENT;

			String WHERE_OR_AND = " WHERE ";
			int nCond = qc.getSize();
			if (nCond > 0) {
				for (int n = 0; n < nCond; n++) {
					sql += WHERE_OR_AND + qc.getField(n) + " = ?";
					WHERE_OR_AND = " AND ";
				}
			}
			ps = conn.prepareStatement(sql);
			if (nCond > 0) {
				for (int n = 0; n < nCond; n++) {
					Object value = qc.getValue(n);
					if (value instanceof String) {
						ps.setString(n+1, (String) value);
					} else if (value instanceof Integer) {
						ps.setInt(n+1, ((Integer) value).intValue());
					}
				}
			}

			rs = ps.executeQuery();
			while (rs.next()) {
				NamespaceVO namespaceVO = new NamespaceVO();
				namespaceVO.setNamespaceID(rs.getInt("namespace_id"));
				namespaceVO.setUri(rs.getString("uri"));
				namespaceVO.setPrefix(rs.getString("prefix"));
				namespaceVO.setPrescription(rs.getString("prescription"));
				namespaceVO.setOwneruserID(rs.getInt("owner_user_id"));
				namespaceVO.setCreatedByUserId(rs.getInt("Created_By"));
				namespaceVO.setLastUpdatedByUserId(rs.getInt("Last_Updated_By"));
				namespaceVO.setCreationTimestamp(rs.getTimestamp("Creation_Timestamp"));
				namespaceVO.setLastUpdateTimestamp(rs.getTimestamp("Last_Update_Timestamp"));
				list.add(namespaceVO);
			}
			conn.close();
		} catch (BfPersistenceException e) {
			throw new SRTDAOException(SRTDAOException.DAO_FIND_ERROR, e);
		} catch (SQLException e) {
			throw new SRTDAOException(SRTDAOException.SQL_EXECUTION_FAILED, e);
		} finally {
			if(ps != null) {
				try {
					ps.close();
				} catch (SQLException e) {}
			}
			if(rs != null) {
				try {
					rs.close();
				} catch (SQLException e) {}
			}
			tx.close();
		}
		return list;
	}

	public ArrayList<SRTObject> findObjects() throws SRTDAOException {
		ArrayList<SRTObject> list = new ArrayList<SRTObject>();

		DBAgent tx = new DBAgent();
		PreparedStatement ps = null;
		ResultSet rs = null;
		try {
			Connection conn = tx.open();
			String sql = _FIND_ALL_NAMESPACE_STATEMENT;
			ps = conn.prepareStatement(sql);
			rs = ps.executeQuery();
			while (rs.next()) {
				NamespaceVO namespaceVO = new NamespaceVO();
				namespaceVO.setNamespaceID(rs.getInt("namespace_id"));
				namespaceVO.setUri(rs.getString("uri"));
				namespaceVO.setPrefix(rs.getString("prefix"));
				namespaceVO.setPrescription(rs.getString("prescription"));
				namespaceVO.setOwneruserID(rs.getInt("owner_user_id"));
				namespaceVO.setCreatedByUserId(rs.getInt("Created_By"));
				namespaceVO.setLastUpdatedByUserId(rs.getInt("Last_Updated_By"));
				namespaceVO.setCreationTimestamp(rs.getTimestamp("Creation_Timestamp"));
				namespaceVO.setLastUpdateTimestamp(rs.getTimestamp("Last_Update_Timestamp"));
				list.add(namespaceVO);
			}
			conn.close();
		} catch (BfPersistenceException e) {
			throw new SRTDAOException(SRTDAOException.DAO_FIND_ERROR, e);
		} catch (SQLException e) {
			throw new SRTDAOException(SRTDAOException.SQL_EXECUTION_FAILED, e);
		} finally {
			if(ps != null) {
				try {
					ps.close();
				} catch (SQLException e) {}
			}
			if(rs != null) {
				try {
					rs.close();
				} catch (SQLException e) {}
			}
			tx.close();
		}

		return list;
	}

	public boolean updateObject(SRTObject obj) throws SRTDAOException {
		DBAgent tx = new DBAgent();
		NamespaceVO namespaceVO = (NamespaceVO)obj;
		PreparedStatement ps = null;
		try {
			Connection conn = tx.open();

			ps = conn.prepareStatement(_UPDATE_NAMESPACE_STATEMENT);

			ps.setString(1, namespaceVO.getUri());
			ps.setString(2, namespaceVO.getPrefix());
			ps.setString(3, namespaceVO.getPrescription());
			ps.setInt(4, namespaceVO.getOwneruserID());
			ps.setInt(5, namespaceVO.getCreatedByUserId());
			ps.setInt(6, namespaceVO.getLastUpdatedByUserId());
			ps.setTimestamp(7, namespaceVO.getCreationTimestamp());
			ps.executeUpdate();

			tx.commit();
		} catch (BfPersistenceException e) {
			tx.rollback(e);
			throw new SRTDAOException(SRTDAOException.DAO_UPDATE_ERROR, e);
		} catch (SQLException e) {
			tx.rollback(e);
			throw new SRTDAOException(SRTDAOException.SQL_EXECUTION_FAILED, e);
		} finally {
			if(ps != null) {
				try {
					ps.close();
				} catch (SQLException e) {}
			}
			tx.close();
		}

		return true;
	}

	public boolean deleteObject(SRTObject obj) throws SRTDAOException {
		NamespaceVO namespaceVO = (NamespaceVO)obj;

		DBAgent tx = new DBAgent();
		PreparedStatement ps = null;
		try {
			Connection conn = tx.open();

			ps = conn.prepareStatement(_DELETE_NAMESPACE_STATEMENT);
			ps.setInt(1, namespaceVO.getNamespaceID());
			ps.executeUpdate();

			tx.commit();
		} catch (BfPersistenceException e) {
			tx.rollback(e);
			throw new SRTDAOException(SRTDAOException.DAO_DELETE_ERROR, e);
		} catch (SQLException e) {
			tx.rollback(e);
			throw new SRTDAOException(SRTDAOException.SQL_EXECUTION_FAILED, e);
		} finally {
			if(ps != null) {
				try {
					ps.close();
				} catch (SQLException e) {}
			}
			tx.close();
		}

		return true;

	}

	public ArrayList<SRTObject> findObjects(QueryCondition qc, Connection conn)
			throws SRTDAOException {
		PreparedStatement ps = null;
		ResultSet rs = null;
		ArrayList<SRTObject> list = new ArrayList<SRTObject>();
		try {
			String sql = _FIND_NAMESPACE_STATEMENT;

			String WHERE_OR_AND = " WHERE ";
			int nCond = qc.getSize();
			if (nCond > 0) {
				for (int n = 0; n < nCond; n++) {
					sql += WHERE_OR_AND + qc.getField(n) + " = ?";
					WHERE_OR_AND = " AND ";
				}
			}
			
			int nCond2 = qc.getLikeSize();
			if (nCond2 > 0) {
				for (int n = 0; n < nCond2; n++) {
					sql += WHERE_OR_AND + qc.getLikeField(n) + " like ?";
					WHERE_OR_AND = " AND ";
				}
			}
			
			ps = conn.prepareStatement(sql);
			if (nCond > 0) {
				for (int n = 0; n < nCond; n++) {
					Object value = qc.getValue(n);
					if (value instanceof String) {
						ps.setString(n+1, (String) value);
					} else if (value instanceof Integer) {
						ps.setInt(n+1, ((Integer) value).intValue());
					}
				}
			}
			
			if (nCond2 > 0) {
				for (int n = 0; n < nCond2; n++) {
					Object value = qc.getLikeValue(n);
					if (value instanceof String) {
						ps.setString(nCond + n + 1, (String) value);
					} else if (value instanceof Integer) {
						ps.setInt(nCond + n + 1, ((Integer) value).intValue());
					}
				}
			}

			rs = ps.executeQuery();
			while (rs.next()) {
				NamespaceVO namespaceVO = new NamespaceVO();
				namespaceVO.setNamespaceID(rs.getInt("namespace_id"));
				namespaceVO.setUri(rs.getString("uri"));
				namespaceVO.setPrefix(rs.getString("prefix"));
				namespaceVO.setPrescription(rs.getString("prescription"));
				namespaceVO.setOwneruserID(rs.getInt("owner_user_id"));
				namespaceVO.setCreatedByUserId(rs.getInt("Created_By"));
				namespaceVO.setLastUpdatedByUserId(rs.getInt("Last_Updated_By"));
				namespaceVO.setCreationTimestamp(rs.getTimestamp("Creation_Timestamp"));
				namespaceVO.setLastUpdateTimestamp(rs.getTimestamp("Last_Update_Timestamp"));
				list.add(namespaceVO);
			}
			
		} catch (SQLException e) {
			throw new SRTDAOException(SRTDAOException.SQL_EXECUTION_FAILED, e);
		} finally {
			if(ps != null) {
				try {
					ps.close();
				} catch (SQLException e) {}
			}
			if(rs != null) {
				try {
					rs.close();
				} catch (SQLException e) {}
			}
		}
		return list;
	}

	@Override
	public ArrayList<SRTObject> findObjects(Connection conn)
			throws SRTDAOException {
		PreparedStatement ps = null;
		ResultSet rs = null;
		ArrayList<SRTObject> list = new ArrayList<SRTObject>();
		
		try {
			String sql = _FIND_ALL_NAMESPACE_STATEMENT;
			ps = conn.prepareStatement(sql);
			rs = ps.executeQuery();
			while (rs.next()) {
				NamespaceVO namespaceVO = new NamespaceVO();
				namespaceVO.setNamespaceID(rs.getInt("namespace_id"));
				namespaceVO.setUri(rs.getString("uri"));
				namespaceVO.setPrefix(rs.getString("prefix"));
				namespaceVO.setPrescription(rs.getString("prescription"));
				namespaceVO.setOwneruserID(rs.getInt("owner_user_id"));
				namespaceVO.setCreatedByUserId(rs.getInt("Created_By"));
				namespaceVO.setLastUpdatedByUserId(rs.getInt("Last_Updated_By"));
				namespaceVO.setCreationTimestamp(rs.getTimestamp("Creation_Timestamp"));
				namespaceVO.setLastUpdateTimestamp(rs.getTimestamp("Last_Update_Timestamp"));
				list.add(namespaceVO);
			}
		} catch (SQLException e) {
			throw new SRTDAOException(SRTDAOException.SQL_EXECUTION_FAILED, e);
		} finally {
			if(ps != null) {
				try {
					ps.close();
				} catch (SQLException e) {}
			}
			if(rs != null) {
				try {
					rs.close();
				} catch (SQLException e) {}
			}
		}
		return list;
	}

	@Override
	public int insertObject(SRTObject obj, Connection conn)
			throws SRTDAOException {
		// TODO Auto-generated method stub
		return 0;
	}
}
