/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.gateway.http.common.repository.jooq.entity.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.oagi.score.gateway.http.common.repository.jooq.entity.tables.TextTemplate;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TextTemplateRecord extends UpdatableRecordImpl<TextTemplateRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.text_template.text_template_id</code>.
     */
    public void setTextTemplateId(ULong value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.text_template.text_template_id</code>.
     */
    public ULong getTextTemplateId() {
        return (ULong) get(0);
    }

    /**
     * Setter for <code>oagi.text_template.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.text_template.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>oagi.text_template.subject</code>.
     */
    public void setSubject(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.text_template.subject</code>.
     */
    public String getSubject() {
        return (String) get(2);
    }

    /**
     * Setter for <code>oagi.text_template.content_type</code>.
     */
    public void setContentType(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>oagi.text_template.content_type</code>.
     */
    public String getContentType() {
        return (String) get(3);
    }

    /**
     * Setter for <code>oagi.text_template.template</code>.
     */
    public void setTemplate(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>oagi.text_template.template</code>.
     */
    public String getTemplate() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<ULong> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached TextTemplateRecord
     */
    public TextTemplateRecord() {
        super(TextTemplate.TEXT_TEMPLATE);
    }

    /**
     * Create a detached, initialised TextTemplateRecord
     */
    public TextTemplateRecord(ULong textTemplateId, String name, String subject, String contentType, String template) {
        super(TextTemplate.TEXT_TEMPLATE);

        setTextTemplateId(textTemplateId);
        setName(name);
        setSubject(subject);
        setContentType(contentType);
        setTemplate(template);
        resetTouchedOnNotNull();
    }
}
